# IGN LiDAR HD - Minimal Processing Configuration
# Fast processing with minimal enrichment for quick results
# Date: October 16, 2025
# Version: 3.0.0

# Use this configuration for:
# - Quick prototyping and testing
# - Memory-constrained environments
# - Fast iteration during development

config_version: "3.0.0"
project_name: "ign_lidar_minimal"

# ============================================================================
# Processing Mode
# ============================================================================

mode: "patches" # Only generate patches, no enrichment

# ============================================================================
# Input/Output
# ============================================================================

input:
  data_dir: "data/raw/lidar"
  tile_pattern: "*.laz"
  crs: "EPSG:2154"

output:
  base_dir: "data/processed"
  format: "npz" # Faster than LAZ for patches
  save_enriched: false # Skip enriched LAZ output
  save_patches: true
  save_statistics: false

cache:
  base_dir: "cache"
  enabled: false # Disable cache for minimal setup

# ============================================================================
# Processing - Optimized for Speed
# ============================================================================

processing:
  num_workers: 2 # Conservative for stability
  max_tiles: null
  batch_size: "auto"
  prefetch_factor: 1 # Minimal prefetching
  pin_memory: false

# ============================================================================
# Data Sources - ALL DISABLED
# ============================================================================

data_sources:
  bd_topo:
    enabled: false
  bd_foret:
    enabled: false
  rpg:
    enabled: false
  cadastre:
    enabled: false

# ============================================================================
# Features - Minimal Set
# ============================================================================

features:
  geometric:
    enabled: true
    k_neighbors: 10 # Reduced for speed
    search_radius: null

    compute:
      height: true
      normals: true
      curvature: false # Skip expensive computation
      planarity: false
      linearity: false
      sphericity: false
      verticality: false

  spectral:
    rgb:
      enabled: false # Skip RGB processing
    nir:
      enabled: false
    ndvi:
      enabled: false

# ============================================================================
# Classification - Basic Only
# ============================================================================

classification:
  methods:
    geometric: true
    ndvi: false
    ground_truth: false # No external data
    forest_types: false
    crop_types: false

  priority_order:
    - ground
    - vegetation
    - building

  post_processing:
    enabled: false # Skip post-processing

# ============================================================================
# Export - Patches Only
# ============================================================================

export:
  laz:
    enabled: false
  geojson:
    enabled: false
  csv:
    enabled: false
  patches:
    enabled: true
    patch_size: 50
    stride: 25
    min_points: 100
    output_format: "npz"

# ============================================================================
# Skip Checker - Disabled for Minimal
# ============================================================================

skip_checker:
  enabled: false
# ============================================================================
# Usage
# ============================================================================

# Run with:
#   ign-lidar-hd process --config configs/presets/minimal.yaml
#
# Expect:
# - Fastest processing speed
# - Minimal disk usage
# - No external data dependencies
# - Basic geometric features only
