# ============================================================================
# IGN LiDAR HD - RTX 3080 Hardware Configuration V5.1
# ============================================================================
# Optimized configuration for NVIDIA RTX 3080
# VRAM: 10GB GDDR6X | CUDA Cores: 8704 | Memory Bandwidth: 760 GB/s
#
# Usage:
#   ign-lidar-hd process --config-name rtx3080
#   ign-lidar-hd process --config-path ign_lidar/configs/hardware --config-name rtx3080
#
# Expected performance: ~70-80% GPU utilization, ~2-3 min per tile
# Version: 5.1.0
# Date: October 18, 2025
# ============================================================================

# Configuration metadata
config_version: "5.1.0"
config_type: "hardware_profile"
hardware_target: "rtx3080"

# Inherit from V5 base configurations
defaults:
  - ../config
  - _self_

# Override for RTX 3080 optimization (smaller VRAM)
processor:
  use_gpu: true

  # RTX 3080 optimized GPU settings (conservative due to 10GB VRAM)
  gpu_batch_size: 10_000_000 # 10M points (~8-9GB VRAM usage)
  gpu_memory_target: 0.85 # 85% VRAM utilization (~8.5GB)
  gpu_streams: 6 # Reduced for smaller VRAM

  # ============================================================================
  # CUDA Optimizations - RTX 3080 (ENABLED - Oct 17, 2025)
  # ============================================================================
  use_cuda_streams: true # Triple-buffering for +20-30% throughput
  enable_memory_pooling: true # Important for memory management
  enable_pipeline_optimization: true # Overlapped computation/transfer
  auto_optimize: true # Auto-tune for RTX 3080

  # RTX 3080 optimized settings (conservative for 10GB VRAM)
  chunk_size: 3_000_000 # 3M points per chunk (10GB VRAM)
  vram_limit_gb: 8.5 # Leave 1.5GB for system
  cleanup_frequency: 15 # More frequent cleanup (smaller VRAM)

  # Ground truth processing
  ground_truth_method: "gpu_chunked" # Force GPU chunked
  ground_truth_chunk_size: 3_000_000 # 3M points per chunk (smaller)

  # Reclassification
  reclassification_mode: "gpu" # Force GPU reclassification
  reclassification_chunk_size: 3_000_000

  # RTX 3080 specific optimizations (legacy - replaced by CUDA settings above)
  enable_async_transfers: true # High memory bandwidth
  enable_mixed_precision: false # Disabled for stability on smaller VRAM
  adaptive_chunk_sizing: true # Dynamic adaptation crucial

features:
  # Reduced parameters for 10GB VRAM constraint
  k_neighbors: 16 # Slightly reduced from default 20
  search_radius: 0.8 # Reduced search radius
  mode: "asprs_classes" # Balanced feature set

monitoring:
  # Enhanced monitoring for VRAM constraints
  enable_gpu_monitoring: true
  enable_performance_metrics: true
  log_level: "INFO"

optimization:
  level: "balanced" # More conservative than RTX 4080
  memory_management: "conservative" # Careful VRAM management

# ============================================================================
# RTX 3080 Performance Notes
# ============================================================================
#
# Recommended for:
# - Standard workstations
# - Moderate batch processing
# - Cost-effective high performance
#
# Expected performance:
# - Features: ~40-60s per tile
# - Ground truth: ~20-30s per tile
# - Total: ~2-3 minutes per tile
#
# Memory usage:
# - Base features: ~6-7GB VRAM
# - Ground truth: ~3-4GB VRAM
# - Peak usage: ~8-9GB VRAM (85% of 10GB)
#
# VRAM limitations:
# - Cannot handle very large tiles without chunking
# - Mixed precision disabled for stability
# - Smaller batch sizes required
#
