# ============================================================================
# Configuration Example: is_ground Feature with DTM Augmentation
# ============================================================================
# 
# This configuration demonstrates how to use the "is_ground" binary feature
# with DTM (Digital Terrain Model) augmentation support.
#
# The is_ground feature:
# - Provides a binary indicator (0/1) for ground vs non-ground points
# - Supports synthetic ground points from DTM augmentation
# - Useful for height computation, classification validation, and ML training
#
# Author: IGN LiDAR HD Development Team
# Date: October 25, 2025
# ============================================================================

# Input/Output
input_dir: "/path/to/input/tiles"
output_dir: "/path/to/output"

# Processor Configuration
processor:
  # Processing mode
  lod_level: "ASPRS"
  processing_mode: "patches_only"
  
  # GPU settings
  use_gpu: false
  use_feature_computer: true  # Use Phase 4 unified computer
  
  # Patch settings
  patch_size: 150.0
  num_points: 16384
  
  # DTM Augmentation (adds synthetic ground points in gaps)
  augment_ground: true  # Enable DTM ground augmentation
  
# Feature Configuration
features:
  # Feature mode
  mode: "asprs_classes"  # Includes is_ground feature by default
  
  # Neighborhood parameters
  k_neighbors: 30
  search_radius: 3.0
  
  # is_ground feature settings
  compute_is_ground: true  # Enable is_ground feature computation
  
  # Synthetic ground handling
  include_synthetic_ground: true  # Include DTM-augmented points in is_ground
  # Set to false to exclude synthetic points (only natural LiDAR ground)
  
  # Spectral features (optional)
  use_rgb: false
  use_infrared: false
  compute_ndvi: false

# DTM Configuration (RGE ALTI)
dtm:
  enabled: true
  resolution: 1.0  # 1m resolution DTM
  use_wcs: true
  prefer_lidar_hd: true  # Prefer LiDAR-derived DTM over photogrammetry
  
  # Augmentation strategy
  augmentation:
    strategy: "intelligent"  # Only add where needed (under buildings/vegetation)
    spacing: 2.0  # Grid spacing for synthetic points (meters)
    
    # Priority areas
    augment_vegetation: true  # Add ground under vegetation
    augment_buildings: true   # Add ground under buildings
    augment_gaps: true        # Fill coverage gaps
    
    # Validation
    validate_against_neighbors: true
    max_height_difference: 5.0  # Max difference from nearby ground (meters)

# Ground Truth Configuration (BD TOPO)
data_sources:
  bd_topo:
    buildings: true
    roads: true
    vegetation: true
    water: true
    railways: true

# ============================================================================
# Usage Example
# ============================================================================
#
# Process tiles and compute is_ground feature:
#
#   python -m ign_lidar.cli.main \
#     --config examples/feature_examples/config_is_ground_feature.yaml
#
# The is_ground feature will be included in output patches/tiles:
# - Value 1: Ground point (ASPRS class 2, natural or DTM-augmented)
# - Value 0: Non-ground point (buildings, vegetation, etc.)
#
# With DTM augmentation enabled, the feature will include:
# - Natural LiDAR ground points (from original data)
# - Synthetic ground points (from RGE ALTI DTM in gaps)
#
# Statistics logged during processing show:
# - Total ground points and percentage
# - DTM contribution (synthetic points count and percentage)
#
# ============================================================================
# Use Cases
# ============================================================================
#
# 1. Height Computation:
#    - Use is_ground to identify ground reference points
#    - Compute height_above_ground more accurately
#    - Better under vegetation and buildings
#
# 2. Classification Validation:
#    - Check ground/non-ground separation quality
#    - Assess impact of DTM augmentation
#    - Validate classification accuracy
#
# 3. Machine Learning:
#    - Binary ground indicator as input feature
#    - Helps models learn ground/non-ground distinction
#    - Improves classification of low objects (curbs, low walls)
#
# 4. Ground Coverage Analysis:
#    - Identify areas with sparse ground points
#    - Evaluate need for DTM augmentation
#    - Assess ground point density distribution
#
# ============================================================================
