# Building Features Configuration
#
# Optimized for building extraction and classification

mode: full
k_neighbors: 20

# Feature flags - focus on geometric
include_extra: true # Height, verticality critical for buildings
use_rgb: false # Optional for buildings
use_infrared: false
compute_ndvi: false

# Sampling
sampling_method: random
normalize_xyz: false
normalize_features: false

# GPU settings
gpu_batch_size: 1000000
use_gpu_chunked: true
