# Minimal Features Configuration
#
# Fast processing with essential features only

mode: minimal
k_neighbors: 10

# Feature flags - minimal set
include_extra: false
use_rgb: false
use_infrared: false
compute_ndvi: false

# PointNet++ settings
sampling_method: random # Faster than FPS
normalize_xyz: false
normalize_features: false

# GPU settings
gpu_batch_size: 1000000
use_gpu_chunked: true
