# Migrated from v5.1 to v4.0 on 2025-11-29T11:00:05.447885
# Original file: config_training_fast_50m_v3.2.yaml
# Migration tool: IGN LiDAR HD ConfigMigrator v4.0

config_version: 4.0.0
config_name: migrated
input_dir: /path/to/your/laz/tiles
output_dir: /path/to/output
mode: lod2
processing_mode: both
use_gpu: true
num_workers: 0
patch_size: 50.0
num_points: 32000
patch_overlap: 0.1
architecture: hybrid
features:
  mode: standard
  k_neighbors: 30
  search_radius: 2.5
  use_rgb: true
  use_nir: true
  compute_ndvi: true
  multi_scale: false
  scales: null
optimizations:
  enabled: true
  async_io: true
  async_workers: 2
  tile_cache_size: 3
  batch_processing: true
  batch_size: 4
  gpu_pooling: true
  gpu_pool_max_size_gb: 4.0
  print_stats: true
advanced:
  ground_truth: &id001
    rgb:
      enabled: true
      source: orthophoto
      resolution: 0.2
      cache_enabled: true
    nir:
      enabled: true
      source: irc
      cache_enabled: true
data_sources: *id001
output:
  format: npz
  processing_mode: both
  save_stats: true
  save_metadata: true
  compression: null
monitoring:
  enable_performance_monitoring: true
  enable_real_time: true
  log_level: INFO
