# Full Features Configuration
#
# Complete feature set for high-quality results

mode: full
k_neighbors: 20

# Feature flags - all enabled
include_extra: true # Height stats, verticality, etc.
use_rgb: true # IGN orthophotos
use_infrared: false # NIR (slower)
compute_ndvi: false # NDVI (requires infrared)

# Architectural style features
include_architectural_style: false # Add architectural style feature
style_encoding: constant # constant (int32), onehot (13-dim), multihot (13-dim weighted)
style_from_building_features: false # Infer style from building geometry

# PointNet++ settings
sampling_method: random
normalize_xyz: false
normalize_features: false

# GPU settings
gpu_batch_size: 1000000
use_gpu_chunked: true
