# LOD2 Features Configuration
#
# Essential feature set for LOD2 building classification
# Optimized for basic building detection with ~12 features

mode: lod2 # LOD2_SIMPLIFIED mode
k_neighbors: 20 # Standard k for LOD2 (balanced between accuracy and speed)

# Feature flags - LOD2 essentials
include_extra: false # Don't compute additional geometric features beyond LOD2
use_rgb: true # RGB colors for classification
use_infrared: false # NIR not required for basic LOD2
compute_ndvi: false # NDVI not required for basic LOD2

# Architectural style features (optional)
include_architectural_style: false # Set to true if needed
style_encoding: constant # Memory-efficient constant encoding
style_from_building_features: false # Set to true to infer from building geometry

# Search method
# Use radius search to avoid scan line artifacts in aerial LiDAR
search_radius: null # Set to value (e.g., 1.5) to use radius search instead of k_neighbors

# PointNet++ settings
sampling_method: random # Faster than FPS for LOD2
normalize_xyz: false
normalize_features: false

# GPU settings
gpu_batch_size: 1000000 # 1M points per batch
use_gpu_chunked: true # Process in chunks for memory efficiency

# ============================================================================
# LOD2 FEATURE SET (~12 features)
# ============================================================================
# This configuration computes the following features:
#
# Coordinates (3):
#   - x, y, z: Point coordinates
#
# Geometric Features (5):
#   - normal_z: Verticality indicator (from surface normal)
#   - planarity: Flat surface detection (roofs, walls)
#   - linearity: Edge detection (building corners, ridges)
#   - height_above_ground: Height feature for vertical separation
#   - verticality: Wall detection score
#
# Spectral Features (4):
#   - red, green, blue: RGB colors
#   - ndvi: Vegetation index (if compute_ndvi=true and NIR available)
#
# Total: ~12 features
# ============================================================================
