# Vegetation Features Configuration
#
# Optimized for vegetation segmentation

mode: full
k_neighbors: 20

# Feature flags - RGB + NIR for NDVI
include_extra: true
use_rgb: true # Color helps distinguish vegetation
use_infrared: true # NIR critical for vegetation
compute_ndvi: true # NDVI index

# Sampling
sampling_method: random
normalize_xyz: false
normalize_features: true # Important for multi-modal features

# GPU settings
gpu_batch_size: 1000000
use_gpu_chunked: true
