# ========================================================================
# ASPRS Patches Generation - 150m Scale
# ========================================================================
# Purpose: Generate 150m x 150m training patches from enriched ASPRS tiles
#
# Scale: 150m - Large context for urban scenes
# Points: 32,768 per patch
# Augmentations: 3
# ========================================================================

defaults:
  - processor: default
  - features: full
  - preprocess: disabled
  - stitching: enabled
  - output: default
  - _self_

input_dir: /mnt/d/ign/preprocessed/asprs/enriched_tiles
output_dir: /mnt/d/ign/patches/asprs/150m

processor:
  skip_existing: true
  lod_level: ASPRS
  architecture: hybrid
  use_gpu: true
  num_workers: 4

  # Patch extraction - 150m scale
  patch_size: 150.0
  patch_overlap: 0.10 # 10% overlap (15m)
  num_points: 32768 # 32k points per patch

  augment: true
  num_augmentations: 3
  augmentation_types:
    - rotation
    - flip
    - jitter

  pin_memory: true

features:
  mode: precomputed

preprocess:
  enabled: false

stitching:
  enabled: true
  buffer_size: 15.0 # 15m buffer
  auto_detect_neighbors: true
  auto_download_neighbors: false
  cache_enabled: true
  cache_dir: /mnt/d/ign/cache/neighbors

output:
  format: npz,laz # NPZ for training, LAZ for visualization
  processing_mode: patches_only
  save_stats: true
  save_metadata: true
  compression: false # No compression for NPZ (faster training)

  split_data: true
  train_split: 0.70
  val_split: 0.15
  test_split: 0.15
  organize_by_split: true

quality:
  min_points_per_patch: 16384
  min_classes_per_patch: 2
  max_ground_ratio: 0.95

logging:
  level: INFO
  log_file: /mnt/d/ign/logs/asprs_patches_150m.log
  progress_bar: true
