# ============================================================================
# V5 Base Configuration: Features (Simplified)
# ============================================================================
# Clean, simplified feature configuration for V5 system.

features:
  # Feature computation mode
  mode: "lod2"  # Options: minimal, lod2, lod3, asprs_classes, full
  
  # Core geometric parameters
  k_neighbors: 20
  search_radius: 1.0
  
  # Essential features
  compute_normals: true
  compute_curvature: true  
  compute_height: true
  compute_geometric: true
  
  # Spectral features
  use_rgb: false
  use_infrared: false
  compute_ndvi: false
  
  # Advanced features
  compute_architectural: false
  architectural_styles: false
  
  # V5 Optimization settings
  enable_caching: true
  enable_auto_tuning: true
  cache_max_size: 50
  
  # GPU settings
  use_gpu: true
  gpu_batch_size: 8000000
  
  # Quality control
  validate_features: true
  handle_nan_values: true
