# ============================================================================
# IGN LiDAR HD - Base Ground Truth Configuration v4.0
# ============================================================================
# Base configuration for ground truth data integration and classification
# Handles BD TOPO, cadastre, and other external data sources
#
# Usage:
#   defaults:
#     - base/ground_truth
#
# Override specific settings in your config:
#   ground_truth:
#     bd_topo:
#       enabled: true
#       include_buildings: true
# ============================================================================

# @package ground_truth
ground_truth:
  # Enable ground truth processing
  enabled: true

  # Processing method
  method: "auto" # Options: auto, gpu_chunked, gpu, cpu
  chunk_size: 2_000_000 # Chunk size for processing

  # BD TOPO configuration
  bd_topo:
    enabled: false # Enable/disable BD TOPO

    # Feature categories
    features:
      buildings: false # ASPRS Class 6 (Buildings)
      roads: false # ASPRS Class 11 (Roads)
      railways: false # ASPRS Class 11 (Railways)
      water: false # ASPRS Class 9 (Water)
      vegetation: false # ASPRS Classes 3,4,5 (Vegetation)
      bridges: false # ASPRS Class 17 (Bridges)
      parking: false # ASPRS Class 11 (Parking areas)
      cemeteries: false # ASPRS Class 2 (Ground/Cemeteries)
      power_lines: false # ASPRS Class 14 (Power lines)
      sports: false # ASPRS Class 11 (Sports facilities)

    # Buffer parameters
    parameters:
      road_width_fallback: 4.0 # Default road width (m)
      railway_width_fallback: 3.5 # Default railway width (m)
      power_line_buffer: 2.0 # Power line buffer (m)
      building_buffer: 0.0 # Building outline buffer (m)
      water_buffer: 0.5 # Water body buffer (m)

    # Classification mapping
    classification_mapping:
      buildings: 6 # ASPRS Building
      roads: 11 # ASPRS Road
      railways: 11 # ASPRS Road (railways)
      water: 9 # ASPRS Water
      low_vegetation: 3 # ASPRS Low vegetation
      medium_vegetation: 4 # ASPRS Medium vegetation
      high_vegetation: 5 # ASPRS High vegetation
      bridges: 17 # ASPRS Bridge
      power_lines: 14 # ASPRS Power lines

  # Cadastre configuration
  cadastre:
    enabled: false # Enable/disable cadastre
    group_by_parcel: false # Group buildings by parcel
    include_building_outlines: true # Use building outlines
    parcel_buffer: 0.0 # Buffer around parcels

  # BD Forêt configuration
  bd_foret:
    enabled: false # Enable/disable BD Forêt
    vegetation_types: ["all"] # Vegetation types to include
    confidence_threshold: 0.8 # Confidence threshold

  # RPG (Agricultural registry) configuration
  rpg:
    enabled: false # Enable/disable RPG
    year: 2024 # RPG year to use
    crop_categories: ["all"] # Crop categories to include

  # Orthophoto configuration
  orthophoto:
    rgb_enabled: true # RGB orthophotos
    nir_enabled: false # NIR orthophotos
    resolution: 0.2 # Target resolution (m/pixel)

  # Ground truth integration
  integration:
    method: "priority_based" # Options: priority_based, voting, confidence_weighted

    # Priority order (higher number = higher priority)
    priority:
      bd_topo: 100 # Highest priority
      cadastre: 80
      bd_foret: 60
      rpg: 40
      geometric_rules: 20 # Lowest priority

    # Conflict resolution
    conflict_resolution:
      method: "highest_priority" # Options: highest_priority, voting, blend
      confidence_threshold: 0.7 # Minimum confidence for assignment

  # Quality control
  quality_control:
    enabled: true # Enable quality control
    validate_geometries: true # Validate ground truth geometries
    check_coverage: true # Check ground truth coverage
    min_coverage_ratio: 0.1 # Minimum coverage ratio

  # Performance settings
  performance:
    use_gpu: true # Use GPU acceleration
    parallel_workers: 1 # Number of parallel workers
    cache_ground_truth: true # Cache ground truth data
    spatial_indexing: true # Use spatial indexing

  # Output settings
  output:
    save_ground_truth_mask: false # Save ground truth mask
    save_confidence_map: false # Save confidence map
    save_statistics: true # Save ground truth statistics
