# ============================================================================
# V5 Base Configuration: Output (Simplified)
# ============================================================================
# Clean output configuration focused on essential settings.

output:
  # Primary output format
  format: "laz"  # Options: laz, las, hdf5
  
  # Output modes
  save_enriched: true   # Enriched LAZ with classifications
  save_patches: false   # ML training patches
  save_metadata: true   # Processing metadata
  save_stats: true      # Classification statistics
  
  # Compression
  compression: null     # Auto-detection
  
  # Validation
  validate_output: true
