# ============================================================================
# IGN LiDAR HD - Base Preprocessing Configuration v4.0
# ============================================================================
# Base configuration for LiDAR point cloud preprocessing operations
# Includes outlier removal, noise filtering, and data cleaning
#
# Usage:
#   defaults:
#     - base/preprocessing
#
# Override specific settings in your config:
#   preprocess:
#     enabled: true
#     statistical_outlier_removal:
#       std_threshold: 1.5  # More aggressive
# ============================================================================

# @package preprocess
preprocess:
  # Enable preprocessing pipeline
  enabled: true

  # Statistical outlier removal (removes sparse outliers)
  statistical_outlier_removal:
    enabled: true
    k_neighbors: 12 # Number of neighbors to consider
    std_threshold: 2.0 # Standard deviation threshold

  # Radius outlier removal (removes isolated points)
  radius_outlier_removal:
    enabled: false # Disabled by default (slower)
    radius: 1.0 # Search radius in meters
    min_neighbors: 5 # Minimum neighbors within radius

  # Noise filtering (for noisy acquisitions)
  noise_filtering:
    enabled: false # Disabled by default
    method: "bilateral" # Options: bilateral, gaussian, median
    sigma_spatial: 0.5 # Spatial sigma for bilateral filter
    sigma_intensity: 0.1 # Intensity sigma for bilateral filter

  # Ground point refinement
  ground_refinement:
    enabled: false # Disabled by default
    method: "pmf" # Progressive Morphological Filter
    max_window_size: 33 # Maximum window size
    slope: 0.7 # Slope threshold
    max_distance: 2.5 # Maximum distance from ground

  # Return filtering (for multi-return data)
  return_filtering:
    enabled: false # Disabled by default
    keep_first_only: false # Keep only first returns
    keep_last_only: false # Keep only last returns
    filter_single_returns: false # Filter single returns

  # Classification code cleaning
  classification_cleaning:
    enabled: true # Clean non-standard classification codes
    remap_unknown_to_unclassified: true # Map unknown codes to unclassified (1)
    preserve_asprs_codes: true # Preserve standard ASPRS codes

  # Intensity normalization
  intensity_normalization:
    enabled: false # Disabled by default
    method: "histogram_equalization" # Options: minmax, zscore, histogram_equalization
    target_range: [0, 255] # Target intensity range

  # Coordinate normalization
  coordinate_normalization:
    enabled: false # Disabled by default (handled in features)
    center_to_origin: false # Center point cloud to origin
    scale_to_unit_cube: false # Scale to unit cube

  # Memory and performance settings
  chunk_size: 1_000_000 # Process in chunks for large tiles
  use_gpu: true # Use GPU acceleration when available
  parallel_workers: 1 # Number of parallel workers

  # Validation and quality control
  validate_outputs: true # Validate preprocessing results
  save_preprocessing_stats: true # Save preprocessing statistics
  log_removed_points: true # Log number of removed points
