# ============================================================================
# IGN LiDAR HD - Base Stitching Configuration v4.0
# ============================================================================
# Base configuration for tile stitching and seamless point cloud merging
# Handles overlapping regions, buffer management, and edge artifacts
#
# Usage:
#   defaults:
#     - base/stitching
#
# Override specific settings in your config:
#   stitching:
#     enabled: true
#     buffer_size: 5.0  # 5m buffer
# ============================================================================

# @package stitching
stitching:
  # Enable tile stitching
  enabled: false # Disabled by default for performance

  # Buffer management
  buffer_size: 2.0 # Buffer size in meters around tile edges
  overlap_threshold: 0.1 # Minimum overlap to consider for stitching

  # Neighbor detection
  auto_detect_neighbors: true # Automatically detect neighboring tiles
  neighbor_search_radius: 10.0 # Search radius for neighbor detection

  # Edge processing
  edge_processing:
    enabled: true # Process tile edges specially
    edge_buffer: 1.0 # Buffer around tile edges
    smooth_transitions: true # Smooth transitions between tiles
    remove_edge_artifacts: true # Remove processing artifacts at edges

  # Overlap resolution
  overlap_resolution:
    method: "distance_weighted" # Options: distance_weighted, priority_based, blend
    distance_weighting_power: 2.0 # Power for distance weighting
    priority_source: "acquisition_time" # Priority source for overlap resolution

  # Seam processing
  seam_processing:
    enabled: true # Enable seam processing
    seam_detection_threshold: 0.5 # Threshold for seam detection
    seam_smoothing: true # Smooth seams between tiles
    feather_distance: 1.0 # Feathering distance for smooth transitions

  # Classification harmonization
  classification_harmonization:
    enabled: true # Harmonize classifications across tiles
    voting_radius: 0.5 # Radius for classification voting
    min_consensus: 0.6 # Minimum consensus for classification

  # Feature harmonization
  feature_harmonization:
    enabled: false # Disabled by default (expensive)
    normalize_across_tiles: true # Normalize features across tiles
    feature_blending: true # Blend features at tile boundaries

  # Output settings
  output_format: "unified" # Options: unified, tiled, both
  preserve_original_tiles: false # Keep original tiles after stitching
  validate_stitching: true # Validate stitching results

  # Performance settings
  chunk_size: 2_000_000 # Chunk size for processing
  use_gpu: true # Use GPU acceleration
  parallel_processing: true # Enable parallel processing
  memory_limit: "75%" # Memory limit percentage

  # Quality control
  quality_checks:
    enabled: true # Enable quality checks
    check_point_density: true # Check point density consistency
    check_classification_consistency: true # Check classification consistency
    check_feature_continuity: true # Check feature continuity
    max_density_variation: 0.3 # Maximum allowed density variation

  # Advanced options
  advanced:
    use_spatial_indexing: true # Use spatial indexing for performance
    cache_neighbor_data: true # Cache neighbor tile data
    progressive_stitching: false # Progressive stitching for large areas
    hierarchical_processing: false # Hierarchical processing for very large datasets
