# ============================================================================
# Hardware Profile: NVIDIA RTX 4090 (24GB VRAM)
# ============================================================================
# Optimized for: RTX 4090, RTX 4090D (24GB Ada Lovelace)
#
# Specifications:
# - VRAM: 24GB GDDR6X
# - CUDA Cores: 16,384
# - Tensor Cores: 512 (4th gen)
# - Memory Bandwidth: 1,008 GB/s
# - Architecture: Ada Lovelace (SM 8.9)
#
# Performance (20M point tile):
# - Feature computation: ~1.5-2 minutes
# - Total processing: ~6-10 minutes
#
# Usage:
#   ign-lidar-hd process --config-name profiles/gpu_rtx4090 \
#     input_dir=/data output_dir=/output
# ============================================================================

defaults:
  - /base_complete

config_name: "gpu_rtx4090"
config_description: "NVIDIA RTX 4090 24GB Profile"

# ============================================================================
# GPU SETTINGS - Aggressive (24GB VRAM)
# ============================================================================
processor:
  use_gpu: true
  gpu_batch_size: 16_000_000 # 16M points per batch
  gpu_memory_target: 0.90 # Use 90% of VRAM (aggressive)
  gpu_streams: 8 # 8 CUDA streams (Ada Lovelace optimization)
  vram_limit_gb: 22 # Leave 2GB headroom

  # FAISS configuration for large batches
  faiss_gpu_threshold: 30_000_000 # Allow very large GPU FAISS
  faiss_allow_large_gpu: true # Override safety checks
  faiss_estimated_temp_memory_gb: 6.0 # More temp memory

  num_workers: 1 # Single worker optimal for GPU
  chunk_size: 16_000_000
  ground_truth_chunk_size: 16_000_000
  cleanup_frequency: 5 # Less frequent cleanup (more VRAM)

  reclassification:
    chunk_size: 12_000_000

# ============================================================================
# FEATURES
# ============================================================================
features:
  gpu_batch_size: 14_000_000 # Slightly smaller for feature ops
  neighbor_query_batch_size: 14_000_000
  feature_batch_size: 10_000_000

# ============================================================================
# GROUND TRUTH
# ============================================================================
ground_truth:
  method: "gpu"
  chunk_size: 14_000_000

# ============================================================================
# OPTIMIZATIONS
# ============================================================================
optimizations:
  max_workers: 1
  enable_parallel_processing: false # Single worker for GPU

# ============================================================================
# EXPECTED PERFORMANCE
# ============================================================================
# Processing 20M point tile:
# - Feature computation: ~1.5-2 min
# - Ground truth: ~1 min
# - Classification: ~30-45 sec
# - I/O: ~2-3 min
# - Total: ~6-10 min
#
# Memory usage:
# - System RAM: 18-24GB
# - VRAM: 18-22GB
#
# Throughput: ~120-160M points/min
# ============================================================================
