# ============================================================================
# Hardware Profile: NVIDIA RTX 4080 (16GB VRAM)
# ============================================================================
# Optimized for: RTX 4080, RTX 4070 Ti Super (16GB Ada Lovelace)
#
# Specifications:
# - VRAM: 16GB GDDR6X
# - CUDA Cores: 9,728
# - Tensor Cores: 304 (4th gen)
# - Memory Bandwidth: 736 GB/s
# - Architecture: Ada Lovelace (SM 8.9)
#
# Performance (20M point tile):
# - Feature computation: ~2-3 minutes
# - Total processing: ~8-14 minutes
#
# Usage:
#   ign-lidar-hd process --config-name profiles/gpu_rtx4080 \
#     input_dir=/data output_dir=/output
# ============================================================================

defaults:
  - /base_complete

config_name: "gpu_rtx4080"
config_description: "NVIDIA RTX 4080 16GB Profile"

# ============================================================================
# GPU SETTINGS - Balanced (16GB VRAM)
# ============================================================================
processor:
  use_gpu: true
  gpu_batch_size: 8_000_000 # 8M points per batch
  gpu_memory_target: 0.85 # Use 85% of VRAM (balanced)
  gpu_streams: 6 # 6 CUDA streams
  vram_limit_gb: 14 # Leave 2GB headroom

  # FAISS configuration
  faiss_gpu_threshold: 25_000_000 # Allow large GPU FAISS
  faiss_allow_large_gpu: true
  faiss_estimated_temp_memory_gb: 4.0

  num_workers: 1
  chunk_size: 8_000_000
  ground_truth_chunk_size: 8_000_000
  cleanup_frequency: 3

  reclassification:
    chunk_size: 6_000_000

# ============================================================================
# FEATURES
# ============================================================================
features:
  gpu_batch_size: 8_000_000
  neighbor_query_batch_size: 8_000_000
  feature_batch_size: 6_000_000

# ============================================================================
# GROUND TRUTH
# ============================================================================
ground_truth:
  method: "gpu"
  chunk_size: 8_000_000

# ============================================================================
# OPTIMIZATIONS
# ============================================================================
optimizations:
  max_workers: 1
  enable_parallel_processing: false
# ============================================================================
# EXPECTED PERFORMANCE
# ============================================================================
# Processing 20M point tile:
# - Feature computation: ~2-3 min
# - Ground truth: ~1-2 min
# - Classification: ~30-60 sec
# - I/O: ~2-3 min
# - Total: ~8-14 min
#
# Memory usage:
# - System RAM: 20-26GB
# - VRAM: 10-14GB
#
# Throughput: ~80-100M points/min
# ============================================================================
