# ============================================================================
# Hardware Profile: NVIDIA RTX 3060 (8GB VRAM)
# ============================================================================
# Optimized for: RTX 3060 8GB, RTX 3060 Ti 8GB (Ampere)
#
# Specifications:
# - VRAM: 8GB GDDR6
# - CUDA Cores: 3,584-4,864
# - Tensor Cores: 112-152 (3rd gen)
# - Memory Bandwidth: 360-448 GB/s
# - Architecture: Ampere (SM 8.6)
#
# Performance (20M point tile):
# - Feature computation: ~5-7 minutes
# - Total processing: ~18-25 minutes
#
# Usage:
#   ign-lidar-hd process --config-name profiles/gpu_rtx3060 \
#     input_dir=/data output_dir=/output
# ============================================================================

defaults:
  - /base_complete

config_name: "gpu_rtx3060"
config_description: "NVIDIA RTX 3060 8GB Profile"

# ============================================================================
# GPU SETTINGS - Very Conservative (8GB VRAM)
# ============================================================================
processor:
  use_gpu: true
  gpu_batch_size: 4_000_000 # 4M points per batch
  gpu_memory_target: 0.75 # Use 75% of VRAM (very conservative)
  gpu_streams: 3 # 3 CUDA streams
  vram_limit_gb: 6 # Leave 2GB headroom

  # FAISS configuration
  faiss_gpu_threshold: 15_000_000 # Standard threshold
  faiss_allow_large_gpu: false
  faiss_estimated_temp_memory_gb: 2.0

  num_workers: 1
  chunk_size: 4_000_000
  ground_truth_chunk_size: 4_000_000
  cleanup_frequency: 1 # Cleanup every tile

  reclassification:
    chunk_size: 3_000_000

# ============================================================================
# FEATURES
# ============================================================================
features:
  gpu_batch_size: 4_000_000
  neighbor_query_batch_size: 4_000_000
  feature_batch_size: 3_000_000

# ============================================================================
# GROUND TRUTH
# ============================================================================
ground_truth:
  method: "gpu"
  chunk_size: 4_000_000

# ============================================================================
# OPTIMIZATIONS
# ============================================================================
optimizations:
  max_workers: 1
  enable_parallel_processing: false
# ============================================================================
# EXPECTED PERFORMANCE
# ============================================================================
# Processing 20M point tile:
# - Feature computation: ~5-7 min
# - Ground truth: ~3-4 min
# - Classification: ~2-3 min
# - I/O: ~2-3 min
# - Total: ~18-25 min
#
# Memory usage:
# - System RAM: 14-20GB
# - VRAM: 5-6GB
#
# Throughput: ~40-50M points/min
# ============================================================================
