# CPU Fast Processor Configuration
#
# Speed-optimized CPU processing (reduced quality)

lod_level: LOD2
architecture: pointnet++ # pointnet++, octree, transformer, sparse_conv, hybrid, multi

use_gpu: false
num_workers: -1 # Use all available CPU cores

# Smaller patches for speed
patch_size: 100.0
patch_overlap: 0.05 # Reduced overlap
num_points: 4096 # Fewer points per patch

augment: false
num_augmentations: 0

batch_size: auto
prefetch_factor: 2
pin_memory: false
