# Default Processor Configuration
#
# CPU-based processing with sensible defaults

# LOD level for classification
lod_level: LOD2 # LOD2 or LOD3

# Architecture configuration
architecture: pointnet++ # pointnet++, octree, transformer, sparse_conv, hybrid, multi

# Hardware configuration
use_gpu: false
num_workers: 4

# Patch configuration
patch_size: 150.0 # Size in meters
patch_overlap: 0.1 # 10% overlap
num_points: 16384 # Points per patch (4096, 8192, 16384, 32768)

# Data augmentation
augment: false
num_augmentations: 3

# Architectural style features
include_architectural_style: false # Include architectural style as a feature
style_encoding: constant # constant, onehot, multihot

# Performance tuning
batch_size: auto # 'auto' or specific int
prefetch_factor: 2
pin_memory: false
