# Heritage Processor Configuration
#
# Specialized for processing architectural heritage sites

# @package _global_

# LOD level for classification
lod_level: LOD3 # LOD3 for detailed architectural features

# Architecture configuration
architecture: hybrid # Hybrid model for best results on heritage

# Hardware configuration
use_gpu: true # GPU recommended for LOD3
num_workers: 2

# Patch configuration (smaller patches for detailed architecture)
patch_size: 100.0 # 100m patches for heritage sites
patch_overlap: 0.15 # 15% overlap for better coverage
num_points: 32768 # 32k points for detailed features

# Data augmentation (useful for training)
augment: false
num_augmentations: 3

# Architectural style features
include_architectural_style: true
style_encoding: onehot # One-hot encoding for ML
style_from_building_features: true # Infer from geometry

# Performance tuning
batch_size: auto
prefetch_factor: 2
pin_memory: true
