# ========================================================================
# LOD3 Patches Generation - 100m Scale
# ========================================================================

defaults:
  - processor: default
  - features: full
  - preprocess: disabled
  - stitching: enabled
  - output: default
  - _self_

input_dir: /mnt/d/ign/preprocessed/lod3/enriched_tiles
output_dir: /mnt/d/ign/patches/lod3/100m

processor:
  skip_existing: true
  lod_level: LOD3
  architecture: hybrid
  use_gpu: true
  num_workers: 4

  patch_size: 100.0
  patch_overlap: 0.18
  num_points: 32768

  augment: true
  num_augmentations: 5
  augmentation_types:
    - rotation
    - flip
    - jitter
    - scale
    - color_jitter

  pin_memory: true

features:
  mode: precomputed

preprocess:
  enabled: false

stitching:
  enabled: true
  buffer_size: 12.0
  auto_detect_neighbors: true
  auto_download_neighbors: false
  cache_enabled: true
  cache_dir: /mnt/d/ign/cache/neighbors

output:
  format: npz,laz # NPZ for training, LAZ for visualization
  processing_mode: patches_only
  save_stats: true
  save_metadata: true
  compression: false # No compression for NPZ (faster training)

  split_data: true
  train_split: 0.70
  val_split: 0.15
  test_split: 0.15
  organize_by_split: true

quality:
  min_points_per_patch: 16384
  min_classes_per_patch: 3
  min_building_ratio: 0.25
  max_ground_ratio: 0.75

logging:
  level: INFO
  log_file: /mnt/d/ign/logs/lod3_patches_100m.log
  progress_bar: true
