# ============================================================================
# IGN LiDAR HD - ASPRS Classification Preset V5.0 (Simplified)
# ============================================================================
# Optimized configuration for ASPRS LAS 1.4 standard classification
# Focuses on standard ASPRS classes: Ground, Buildings, Vegetation, Water, etc.
#
# Usage:
#   ign-lidar-hd process --config-name asprs_classification
#   ign-lidar-hd process --config-path ign_lidar/configs/presets --config-name asprs_classification
#
# Target classes: ASPRS standard (1-18)
# V5: Simplified configuration with integrated optimizations
# ============================================================================

# V5 simplified base composition - inherit all base configurations
defaults:
  - ../config
  - _self_

# V5: ASPRS-specific overrides (simplified)
processor:
  # Core processing settings
  lod_level: "ASPRS" # Use ASPRS classification scheme
  processing_mode: "enriched_only" # Focus on enriched LAZ output
  processing_mode: "enriched_only" # Processing mode for output

  # GPU configuration
  use_gpu: true # Enable GPU acceleration
  use_gpu_chunked: true # Enable chunked processing
  gpu_batch_size: 8_000_000 # OPTIMIZED: Balanced for ASPRS features
  gpu_memory_target: 0.85 # Conservative memory usage
  gpu_streams: 8
  enable_memory_pooling: true
  enable_async_transfers: true
  adaptive_chunk_sizing: true
  num_workers: 1 # GPU works best with 1 worker

  # Processing parameters
  skip_existing: false
  output_format: "laz"
  use_stitching: false # Disable stitching for simplified processing

  # Patch processing parameters (required even for enriched_only mode)
  patch_size: 50.0 # 50m patches for processing
  patch_overlap: 0.1 # 10% overlap between patches
  num_points: 16384 # Target number of points per patch

  # Additional parameters for V5 compatibility
  architecture: "pointnet++"
  augment: false
  num_augmentations: 3
  batch_size: "auto"
  prefetch_factor: 2
  pin_memory: false

features:
  processing_mode: "asprs_classes" # ASPRS-optimized feature set
  gpu_batch_size: 8_000_000 # OPTIMIZED: Match processor batch size

  # Essential features for ASPRS classification
  k_neighbors: 10 # OPTIMIZED: Reduced from 20 for faster processing
  search_radius: 1.0
  compute_normals: true
  compute_planarity: true
  compute_height_above_ground: true
  compute_verticality: true # Important for buildings vs vegetation

  # Spectral features for vegetation/ground distinction
  use_rgb: true
  use_nir: false # DISABLED: Slow to fetch, can enable if needed
  compute_ndvi: false # DISABLED: Requires NIR

data_sources:
  # Essential sources for ASPRS ground truth
  bd_topo:
    enabled: true
    features:
      buildings: true # ASPRS Class 6 (Buildings)
      roads: true # ASPRS Class 11 (Roads)
      water: true # ASPRS Class 9 (Water)
      vegetation: true # ASPRS Class 3/4/5 (Vegetation)
    cache_enabled: true
    use_global_cache: false
  bd_topo_bridges: true # ASPRS Class 17 (Bridges)
  bd_topo_power_lines: false # DISABLED: Can enable if needed

  # Orthophotos for spectral features
  orthophoto_rgb: true
  orthophoto_nir: false # DISABLED: Slow to fetch

classification:
  enabled: true
  use_ground_truth: true # BD TOPO ground truth
  use_geometric_rules: true # Geometric classification rules
  use_ndvi_classification: true # Enabled with NIR

  # ASPRS-specific thresholds
  height_low_vegetation: 0.5 # 0.5m threshold for low vegetation
  height_medium_vegetation: 2.0 # 2.0m threshold for medium vegetation
  planarity_road: 0.85 # High planarity for roads
  planarity_building: 0.75 # Moderate planarity for buildings

preprocess:
  enabled: true # Enable preprocessing for quality
  statistical_outlier_removal:
    enabled: true
    k_neighbors: 12
    std_threshold: 2.0

output:
  format: "laz" # LAZ format for ASPRS compatibility
  save_enriched: true
  save_metadata: true
  save_stats: true

stitching:
  enabled: false # Disable for simplified processing
  buffer_size: 10.0
  auto_detect_neighbors: true
  auto_download_neighbors: false
  cache_enabled: true

monitoring:
  log_level: "INFO"
  enable_performance_metrics: true
# ============================================================================
# ASPRS Classification Notes
# ============================================================================
#
# Target ASPRS classes:
# - Class 1: Unclassified
# - Class 2: Ground
# - Class 3: Low Vegetation (< 0.5m)
# - Class 4: Medium Vegetation (0.5-2m)
# - Class 5: High Vegetation (> 2m)
# - Class 6: Buildings
# - Class 9: Water
# - Class 11: Roads
# - Class 17: Bridges (optional)
#
# Performance expectations:
# - Enriched LAZ output with ASPRS classifications
# - Processing time: ~1-3 minutes per tile (GPU)
# - High accuracy on buildings, roads, water
# - Good vegetation height classification
#
# Quality factors:
# - Ground truth from BD TOPO for buildings/roads/water
# - Height-based vegetation classification
# - Geometric rules for road/building distinction
# - Optional spectral features with orthophotos
#
