# ============================================================================
# V5: Simplified configuration with integrated optimizations
# IGN LiDAR HD - ASPRS Classification GPU WORKING CONFIG
# ============================================================================
# V5: Simplified configuration with integrated optimizations
# Configuration that ACTUALLY uses GPU by avoiding mode-based fallback
# ============================================================================
# V5: Simplified configuration with integrated optimizations

# Inherit from base configurations
defaults:
  - ../config
  - _self_

# GPU settings that work (no mode fallback) - V5 simplified
processor:
  lod_level: "ASPRS"
  processing_mode: "enriched_only"
  use_gpu: true
  use_gpu_chunked: true # ✅ UPDATED: Enable chunked mode for optimized performance

  # Conservative but working batch sizes
  gpu_batch_size: 1_000_000
  gpu_memory_target: 0.7
  gpu_streams: 4
  enable_memory_pooling: true
  enable_async_transfers: false
  enable_mixed_precision: false
  adaptive_chunk_sizing: false

features:
  # CRITICAL: Don't use mode - it causes CPU fallback!
  # mode: "asprs_classes" # REMOVED: This causes GPU fallback

  # Essential features for ASPRS classification (manually specified)
  k_neighbors: 20
  search_radius: 1.0
  compute_normals: true
  compute_planarity: true
  compute_height_above_ground: true
  compute_verticality: true
  use_rgb: true
  use_nir: false # DISABLED for now
  compute_ndvi: false # DISABLED for now

  # Disable complex features that might cause issues
  compute_architectural_features: false
  compute_multiscale_features: false
  include_architectural_style: false

  normalize_xyz: true
  normalize_features: true
  gpu_batch_size: 1_000_000

# Minimal data sources for testing
data_sources:
  bd_topo_buildings: true
  bd_topo_roads: true
  bd_topo_water: true
  bd_topo_vegetation: false
  bd_topo_bridges: false
  bd_topo_power_lines: false
  orthophoto_rgb: true
  orthophoto_nir: false
  cadastre_enabled: false
  bd_foret_enabled: false
  rpg_enabled: false

# Simplified classification
classification:
  enabled: true
  use_ground_truth: true
  use_geometric_rules: true
  use_ndvi_classification: false # DISABLED due to NIR disabled
  height_low_vegetation: 0.5
  height_medium_vegetation: 2.0
  planarity_road: 0.8
  planarity_building: 0.7
  ndvi_vegetation: 0.35
  post_processing_enabled: true
  reclassify_unclassified: true
  apply_morphological_filters: true

# Disable preprocessing to simplify
preprocess:
  enabled: false

# Enable debugging
monitoring:
  log_level: "DEBUG"
  verbose: true
  enable_gpu_monitoring: true
  enable_performance_metrics: true
  save_metrics: true
  enable_profiling: false

# Conservative optimization
optimization:
  level: "balanced"
  enable_auto_tuning: false
  memory_management: "cuda"
  enable_parallel_processing: true
  enable_caching: true
  cache_optimization_results: false
