# ============================================================================
# V5: Simplified configuration with integrated optimizations
# IGN LiDAR HD - ASPRS Classification GPU Test (Conservative Settings)
# ============================================================================
# V5: Simplified configuration with integrated optimizations
# Conservative GPU configuration for debugging GPU fallback issues
# ============================================================================
# V5: Simplified configuration with integrated optimizations

# Inherit from base configurations
defaults:
  - ../config
  - _self_

# Conservative GPU settings for debugging (V5 simplified)
processor:
  lod_level: "ASPRS"
  mode: "enriched_only"
  use_gpu: true
  use_gpu_chunked: true # ✅ UPDATED: Enable chunked mode (now optimized!)

  # Conservative batch sizes for testing
  gpu_batch_size: 1_000_000 # CONSERVATIVE: 1M points per batch
  gpu_memory_target: 0.7 # Use only 70% of GPU memory
  gpu_streams: 4 # Fewer streams for stability
  enable_memory_pooling: true
  enable_async_transfers: false # DISABLED: Simplify for debugging
  enable_mixed_precision: false
  adaptive_chunk_sizing: false # DISABLED: Fixed chunk size

features:
  mode: "asprs_classes"
  gpu_batch_size: 1_000_000 # CONSERVATIVE: Smaller batch for stability

  # Essential features for ASPRS classification
  k_neighbors: 20
  search_radius: 1.0
  compute_normals: true
  compute_planarity: true
  compute_height_above_ground: true
  compute_verticality: true
  use_rgb: true
  use_nir: true
  compute_ndvi: true

  # Disable complex features for debugging
  compute_architectural_features: false
  compute_multiscale_features: false
  include_architectural_style: false

  normalize_xyz: true
  normalize_features: true

# Enable debugging and monitoring
monitoring:
  log_level: "DEBUG"
  verbose: true
  enable_gpu_monitoring: true
  enable_performance_metrics: true
  save_metrics: true
  enable_profiling: true

# Conservative optimization settings
optimization:
  level: "balanced" # Not aggressive
  enable_auto_tuning: false # DISABLED: Fixed settings for debugging
  memory_management: "cuda"
  enable_parallel_processing: true
  enable_caching: true
  cache_optimization_results: false # DISABLED: For debugging
