# ============================================================================
# IGN LiDAR HD - Preset: ASPRS - Optimized for RTX 4080 (16GB VRAM)
# ============================================================================
# Based on: asprs.yaml
#
# HARDWARE: RTX 4080 with 16GB VRAM
# OPTIMIZATION: Maximized batch sizes and memory utilization
#
# KEY OPTIMIZATIONS:
#   - Increased GPU batch size to 20M points (maximized for 16GB VRAM)
#   - Increased feature batch size to 10M points (2.5× previous)
#   - Higher GPU memory target (90% = 14.4GB)
#   - Increased CUDA streams to 8 (from 4)
#   - Enabled pipeline optimization
#   - Larger ground truth chunk size (15M points)
#   - Optimized memory pooling (14GB limit)
#
# EXPECTED PERFORMANCE:
#   - 3-4× faster than default ASPRS preset
#   - Full VRAM utilization (12-14GB)
#   - Minimal chunking overhead
#   - Maximum GPU occupancy
#
# USAGE:
#   ign-lidar-hd process --preset asprs_rtx4080 input/ output/
#
# Version: 5.1.0 RTX4080
# Date: October 18, 2025
# ============================================================================

# Inherit from base configuration
defaults:
  - ../base
  - _self_

# Preset metadata
config_version: "5.1.0"
preset_name: "asprs_rtx4080"

# ============================================================================
# RTX 4080 OPTIMIZATIONS
# ============================================================================

# Processor: Optimized for 16GB VRAM
processor:
  # Classification scheme
  lod_level: "ASPRS" # Use ASPRS LAS 1.4 classification
  processing_mode: "both" # Generate both patches and enriched LAZ output

  # GPU settings - MAXIMIZED for RTX 4080
  use_gpu: true
  gpu_batch_size: 20_000_000 # 20M points - optimized for full 16GB VRAM utilization
  gpu_memory_target: 0.90 # 90% VRAM usage (14.4GB out of 16GB)
  gpu_streams: 8 # 8 CUDA streams for better parallelism

  # CUDA optimizations - ENABLED for RTX 4080
  use_cuda_streams: true # Enable async CUDA streams
  enable_memory_pooling: true # GPU memory pooling
  enable_pipeline_optimization: true # Triple-buffering pipeline
  auto_optimize: true # Automatic parameter tuning
  chunk_size: null # Auto-determined
  vram_limit_gb: 14 # Conservative 14GB limit (leave 2GB for system)
  cleanup_frequency: 5 # More frequent cleanup (every 5 iterations)

  # Strategy pattern (Week 2 improvement)
  use_strategy_pattern: true # Use new Strategy Pattern

  # Optimization flags
  use_optimized_ground_truth: true # Use optimized ground truth classifier (10× faster)
  enable_async_transfers: true # Async CPU-GPU transfers
  adaptive_chunk_sizing: true # Dynamic chunk sizing

  # Processing settings
  num_workers: 1 # Single worker for GPU processing
  skip_existing: false # Re-process existing files
  output_format: "laz" # Output format
  use_stitching: false # Tile stitching disabled by default

  # Patch extraction (for ML training mode)
  patch_size: 50.0 # Patch size in meters
  patch_overlap: 0.1 # 10% overlap
  num_points: 24576 # Points per patch
  architecture: "direct" # Direct patch extraction
  augment: false # No augmentation for enriched-only mode
  num_augmentations: 3 # Augmentations if enabled

  # Ground truth settings - OPTIMIZED for RTX 4080
  ground_truth_method: "auto" # GPU chunked or STRtree
  ground_truth_chunk_size: 15_000_000 # 15M points per chunk - maximized for 16GB VRAM

  # Reclassification
  reclassification:
    enabled: true
    use_geometric_rules: true # Height, planarity for refinement
    use_ndvi_classification: true # Enable if NIR available
    min_confidence: 0.8 # High confidence for ASPRS compliance

# Features: ASPRS-optimized feature set with RTX 4080 tuning
features:
  mode: "asprs_classes" # ASPRS feature mode
  include_extra: true # Include extra features for classification

  # Geometric parameters
  k_neighbors: 20 # Standard neighborhood
  search_radius: 1.0 # 1 meter radius

  # GPU settings - OPTIMIZED for RTX 4080
  use_gpu_chunked: true
  gpu_batch_size: 10_000_000 # 10M points - maximized for full VRAM utilization

  # Neighbor query chunking (NEW) - Controls how many chunks to split neighbor queries into
  # Lower values = more chunks = less memory per chunk but more overhead
  # For 18.6M point tiles with 2 chunks, use ~10M (ensures 2 chunks even for slightly larger tiles)
  # Default is 5M (creates ~4 chunks for 18.6M points)
  neighbor_query_batch_size: 10_000_000 # 10M points per chunk (creates 2 chunks for 18.6M point tiles)

  # Feature computation batching (NEW) - Controls batching for normal/curvature computation
  # Lower values = more batches = less memory per batch (helps with large tiles)
  # For 18.6M point tiles with 2 batches, use ~10M
  # Default is 2M (creates ~10 batches for 18.6M points)
  feature_batch_size: 10_000_000 # 10M points per batch (creates 2 batches for 18.6M point tiles)

  # Essential features for ASPRS
  compute_normals: true
  compute_curvature: true
  compute_height: true # Critical for vegetation height
  compute_geometric: true # Planarity, verticality

  # Architectural features not critical for ASPRS
  compute_architectural: false

  # Spectral features for vegetation/ground distinction
  use_rgb: true # Recommended for better vegetation classification
  use_nir: false # NIR (near-infrared) - enable if available
  use_infrared: false # Infrared - enable if NIR available (alias for use_nir)
  compute_ndvi: true # NDVI (requires RGB + NIR) - will auto-disable if NIR unavailable

# Data Sources: Full BD TOPO for ASPRS ground truth
data_sources:
  # BD TOPO: Essential for ASPRS ground truth
  bd_topo:
    enabled: true
    features:
      buildings: true # ASPRS Class 6
      roads: true # ASPRS Class 11
      water: true # ASPRS Class 9
      vegetation: true # ASPRS Classes 3/4/5

  # Additional BD TOPO layers for ASPRS
  bd_topo_bridges: true # Enable for ASPRS Class 17
  bd_topo_power_lines: true # Enable for ASPRS Class 14

  # Orthophotos for spectral features
  orthophoto_rgb: true # Recommended for vegetation
  orthophoto_nir: true # Enable for NDVI computation

# Output: Standard ASPRS outputs
output:
  format: "laz" # Output format (required by CLI)
  save_enriched: true # Enriched LAZ with ASPRS classes
  save_patches: true # Save patches for ML training
  save_metadata: true # Save metadata
  save_stats: true # Save ASPRS classification statistics

# Preprocessing: Enable for quality control
preprocess:
  enabled: false # Disabled by default for ASPRS

# Tile Stitching: Disabled for ASPRS
stitching:
  enabled: false # No stitching by default
  buffer_size: 10.0 # Buffer size in meters if enabled

# ============================================================================
# EXPECTED PERFORMANCE vs DEFAULT ASPRS
# ============================================================================
# Processing speed:
#   - 3-4× faster than default asprs.yaml
#   - Minimal chunking (20M points per batch vs 4M)
#   - Maximum GPU utilization (90% = 14.4GB)
#   - Reduced CPU-GPU transfer overhead
#
# Memory usage:
#   - VRAM: 12-14GB (75-90% of 16GB)
#   - RAM: Similar to default
#
# Throughput:
#   - ~80-120 million points per minute (estimated)
#   - Depends on feature complexity and data source availability
#
# Tile handling:
#   - 18M point tiles: Process in 1 chunk (vs 3 chunks before)
#   - 20M point tiles: Process in 1 chunk
#   - 30M point tiles: Process in 2 chunks (vs 6 chunks before)
# ============================================================================
