# ============================================================================
# V5: Simplified configuration with integrated optimizations
# IGN LiDAR HD - Comprehensive Optimized Configuration v4.1
# ============================================================================
# V5: Simplified configuration with integrated optimizations
# Advanced configuration with all performance optimizations enabled
# Targets: GPU acceleration, parallel processing, intelligent caching,
# adaptive parameter tuning, and enhanced feature computation
# ============================================================================
# V5: Simplified configuration with integrated optimizations

# Inherit from base configurations
defaults:
  - ../config
  - _self_

# === CORE PROCESSING OPTIMIZATION ===
processor:
  lod_level: "ASPRS"
  mode: "enriched_only"
  architecture: "enhanced" # Use enhanced orchestrator
  auto_optimize: true # Enable intelligent optimization

  # GPU Configuration - Optimized for RTX 4080 Super
  use_gpu: true
  use_gpu_chunked: false # Use optimized basic GPU mode
  gpu_batch_size: 2_000_000 # Optimized batch size
  gpu_memory_target: 0.8 # Conservative memory usage
  gpu_streams: 6 # Optimal for RTX 4080 Super

  # Memory Management
  enable_memory_pooling: true
  enable_async_transfers: true
  enable_mixed_precision: false # Disabled for stability
  adaptive_chunk_sizing: true

  # Performance Optimization
  num_workers: 4 # Parallel processing
  enable_parallel_processing: true

  # Ground Truth Optimization
  ground_truth_method: "vectorized" # Use optimized implementation
  ground_truth_chunk_size: 5_000_000 # Large chunks for efficiency

  # Reclassification Optimization
  reclassification_mode: "gpu" # Use GPU for reclassification
  reclassification_chunk_size: 3_000_000

# === ENHANCED FEATURE COMPUTATION ===
features:
  # Adaptive Parameters (will be auto-tuned)
  k_neighbors: 20 # Base value, will adapt based on point density
  search_radius: 1.0 # Base value, will adapt based on data

  # Core Features - Optimized Selection
  compute_normals: true
  compute_planarity: true
  compute_height_above_ground: true
  compute_verticality: true
  compute_curvature: true
  compute_density: true

  # RGB/NIR Processing - Parallel Enabled
  use_rgb: true
  use_nir: true
  compute_ndvi: true
  parallel_rgb_nir: true # Enable parallel fetching

  # Advanced Features (selective enable)
  compute_architectural_features: false
  compute_multiscale_features: false
  include_architectural_style: false

  # Optimization Settings
  normalize_xyz: true
  normalize_features: true
  gpu_batch_size: 2_000_000

  # Caching Configuration
  enable_caching: true
  cache_max_size: 200 # MB
  cache_strategy: "intelligent"

  # Auto-tuning
  enable_auto_tuning: true
  adaptation_rate: "moderate"

# === DATA SOURCES OPTIMIZATION ===
data_sources:
  # Core data sources
  bd_topo_buildings: true
  bd_topo_roads: true
  bd_topo_water: true
  bd_topo_vegetation: true
  bd_topo_bridges: true
  bd_topo_power_lines: true

  # RGB/NIR sources
  orthophoto_rgb: true
  orthophoto_nir: true

  # Additional sources (selective)
  cadastre_enabled: false
  bd_foret_enabled: false
  rpg_enabled: false

  # Optimization settings
  enable_parallel_fetching: true
  cache_data_sources: true
  prefetch_strategy: "intelligent"

# === CLASSIFICATION OPTIMIZATION ===
classification:
  enabled: true

  # Ground truth optimization
  use_ground_truth: true
  ground_truth_optimization: "gpu" # Use GPU optimization

  # Rule-based classification
  use_geometric_rules: true
  use_ndvi_classification: true

  # Optimized thresholds (will be auto-tuned)
  height_low_vegetation: 0.5
  height_medium_vegetation: 2.0
  planarity_road: 0.85
  planarity_building: 0.75
  ndvi_vegetation: 0.35

  # Post-processing optimization
  post_processing_enabled: true
  reclassify_unclassified: true
  apply_morphological_filters: true

  # Performance settings
  enable_parallel_classification: true
  classification_batch_size: 1_000_000

# === OUTPUT OPTIMIZATION ===
output:
  format: "laz"
  save_enriched: true
  save_patches: false # Disabled for performance
  save_metadata: true
  save_stats: true
  compression: "default"
  validate_output: true

  # Performance optimization
  enable_parallel_writing: true
  write_buffer_size: 10_000_000 # Large write buffers

# === PREPROCESSING OPTIMIZATION ===
preprocess:
  enabled: true

  # Optimized outlier removal
  statistical_outlier_removal:
    enabled: true
    k_neighbors: 15 # Optimized for performance
    std_threshold: 2.0
    use_gpu: true # Enable GPU acceleration

  radius_outlier_removal:
    enabled: false # Disabled for performance
    radius: 1.0
    min_neighbors: 5

# === MONITORING AND PROFILING ===
monitoring:
  log_level: "INFO"
  verbose: true

  # Performance monitoring
  enable_gpu_monitoring: true
  enable_performance_metrics: true
  enable_profiling: true

  # Advanced monitoring
  save_metrics: true
  metrics_format: "json"
  enable_real_time_optimization: true

# === OPTIMIZATION CONFIGURATION ===
optimization:
  level: "aggressive"

  # Auto-tuning
  enable_auto_tuning: true
  auto_tuning_strategy: "performance"

  # Memory optimization
  memory_management: "cuda"
  enable_parallel_processing: true

  # Caching optimization
  enable_caching: true
  cache_optimization_results: true

  # Advanced optimizations
  enable_vectorization: true
  enable_gpu_streams: true
  enable_memory_pooling: true

# === VALIDATION ===
validation:
  strict_validation: false # Relaxed for performance
  enable_legacy_support: true
  migrate_old_configs: true
  check_gpu_availability: true
  check_memory_requirements: true

  # Performance validation
  validate_performance: true
  performance_targets:
    min_points_per_second: 1_000_000
    max_memory_usage_gb: 12
    max_processing_time_per_tile: 300 # 5 minutes
