# ============================================================================
# IGN LiDAR HD - GPU Optimized Preset V5.0 (Simplified)
# ============================================================================
# High-performance GPU configuration with V5 integrated optimizations.
# Optimizations are now built into FeatureOrchestrator V5.
#
# Usage:
#   ign-lidar-hd process --config-name gpu_optimized
#   ign-lidar-hd process --config-path ign_lidar/configs/presets --config-name gpu_optimized
#
# Target: Maximum GPU utilization with integrated optimizations
# ============================================================================

# V5 simplified base composition
defaults:
  - ../config_v5
  - _self_

# V5 GPU optimization overrides (simplified)
processor:
  mode: "enriched_only"
  use_gpu: true
  gpu_batch_size: 16_000_000 # 16M points for high-memory GPU
  gpu_memory_target: 0.90 # 90% VRAM utilization
  num_workers: 1

features:
  mode: "asprs_classes" # Balanced features
  k_neighbors: 16 # Speed-optimized
  search_radius: 0.8 # Reduced for speed
  use_gpu: true
  gpu_batch_size: 16_000_000

# V5 integrated optimizations (always enabled, configure behavior)
optimizations:
  enable_caching: true
  cache_max_size_mb: 200 # Larger cache for GPU
  enable_parallel_processing: true
  max_workers: 4 # More parallel workers
  enable_auto_tuning: true
  adaptive_parameters: true
  enable_performance_metrics: true

# Hardware-specific settings
hardware:
  prefer_gpu: true
  fallback_cpu: false # Force GPU only

# Output settings
output:
  format: "laz"
  save_enriched: true
  save_patches: false
  validate_output: true

# Monitoring
monitoring:
  log_level: "INFO"
  enable_gpu_monitoring: true
  enable_performance_metrics: true

# Data sources - minimal for speed
data_sources:
  bd_topo_buildings: true
  bd_topo_roads: true
  bd_topo_water: true
  bd_topo_vegetation: false
  bd_topo_bridges: false
  cadastre_enabled: false
  orthophoto_rgb: true
  orthophoto_nir: false

# Classification settings
classification:
  enabled: true
  use_ground_truth: true
  use_geometric_rules: true
  planarity_road: 0.85
  planarity_building: 0.75
  height_low_vegetation: 0.5
  height_medium_vegetation: 2.0
# - Production environments
#
# Performance expectations:
# - GPU utilization: >80%
# - Processing time: <1 minute per tile
# - Memory usage: Up to 90% VRAM
# - Throughput: 60+ tiles per hour
#
# Requirements:
# - GPU with 10GB+ VRAM
# - CUDA-compatible GPU
# - Stable power supply for high GPU load
#
# Speed optimizations:
# - Maximum batch sizes
# - Aggressive memory management
# - Forced GPU processing for all operations
# - Mixed precision enabled
# - Minimal logging overhead
#
# - Utilisation GPU attendue: >85%
# - Utilisation VRAM: ~14-15GB (sur 16GB)
# - Temps par tuile: 30-60 secondes
# - Convient pour: RTX 4080, RTX 3080, A100
#
# Fallback automatique si VRAM insuffisante
