# ============================================================================
# V5: Simplified configuration with integrated optimizations
# IGN LiDAR HD - Ground Truth Training Preset V5.0 (Simplified)
# ============================================================================
# V5: Simplified configuration with integrated optimizations
# Optimized configuration for ML training with ground truth generation
# Produces both enriched tiles and training patches with high-quality labels
#
# Usage:
#   ign-lidar-hd process --config-file ign_lidar/configs/presets/ground_truth_training.yaml
#   ign-lidar-hd process --config-name ground_truth_training
#
# Focus: High-quality training data generation
# ============================================================================
# V5: Simplified configuration with integrated optimizations

# Inherit from base configurations and default config
defaults:
  - ../config
  - _self_

# Ground truth training specific overrides
processor:
  mode: "both" # Generate enriched tiles AND training patches
  lod_level: "LOD2" # Optimized for building training

  # GPU optimized for ground truth processing
  gpu_batch_size: 4_000_000 # Batch size adapted for training
  gpu_memory_target: 0.80 # Conservative to avoid OOM
  gpu_streams: 6 # Moderate parallelism

  # Force GPU methods for consistency
  ground_truth_method: "gpu_chunked" # Optimal method
  reclassification_mode: "gpu" # Force GPU for consistency

  # Advanced optimizations for training quality
  enable_memory_pooling: true
  enable_async_transfers: true
  enable_mixed_precision: false # Disabled for precision in training
  adaptive_chunk_sizing: true

features:
  mode: "lod2" # LOD2 features for building training

  # Enhanced parameters for training quality
  k_neighbors: 24 # Larger neighborhood for better features
  search_radius: 1.5 # Larger radius for context

  # Comprehensive geometric features
  compute_normals: true
  compute_planarity: true
  compute_height_above_ground: true
  compute_verticality: true # Important for building training
  compute_architectural_features: true # Enable for advanced training

  # Full spectral features for training
  use_rgb: true
  use_nir: true # Important for vegetation/building distinction
  compute_ndvi: true # Valuable for training

data_sources:
  # Comprehensive ground truth sources
  bd_topo_buildings: true # Primary building source
  bd_topo_roads: true # Road context
  bd_topo_water: true # Water bodies
  bd_topo_vegetation: true # Vegetation ground truth
  bd_topo_bridges: true # Bridge structures
  bd_topo_power_lines: true # Infrastructure

  # Additional sources for rich training data
  cadastre_enabled: true # Building footprints
  bd_foret_enabled: true # Forest classification
  rpg_enabled: true # Agricultural data

  # Full spectral data
  orthophoto_rgb: true
  orthophoto_nir: true # Required for NDVI

classification:
  enabled: true
  use_ground_truth: true # Essential for training
  use_geometric_rules: true # Comprehensive classification
  use_ndvi_classification: true # NDVI-based classification

  # Optimized thresholds for training
  height_low_vegetation: 0.5
  height_medium_vegetation: 2.0
  planarity_road: 0.85
  planarity_building: 0.70 # Slightly lower for complex buildings
  ndvi_vegetation: 0.3 # NDVI threshold

preprocess:
  enabled: true # Enable for training quality
  statistical_outlier_removal:
    enabled: true
    k_neighbors: 15 # More robust filtering
    std_threshold: 2.0
  radius_outlier_removal:
    enabled: true
    radius: 1.0
    min_neighbors: 5

output:
  format: "laz"
  save_enriched: true # Save enriched tiles
  save_patches: true # Save training patches
  save_metadata: true # Full metadata for training
  save_stats: true

optimization:
  level: "balanced" # Balance speed and quality
  memory_management: "balanced"
  enable_caching: true # Cache for efficiency

monitoring:
  log_level: "INFO" # Detailed logging for training
  verbose: true
  enable_performance_metrics: true
  enable_gpu_monitoring: true

  # ============================================================================
# V5: Simplified configuration with integrated optimizations
  # Ground Truth Training Notes
  # ============================================================================
# V5: Simplified configuration with integrated optimizations
  #
  # Optimized for:
  # - ML training data generation
  # - High-quality ground truth labels
  # - Building detection training
  # - Multi-class classification training
  # - Research and development
  #
  # Training data quality:
  # - Comprehensive feature set (geometric + spectral)
  # - Multi-source ground truth (BD TOPO + Cadastre + BD Forêt + RPG)
  # - NDVI computation for vegetation/building distinction
  # - Architectural features for advanced models
  # - Outlier removal for clean training data
  #
  # Performance expectations:
  # - Processing time: ~5-10 minutes per tile (due to comprehensive processing)
  # - Memory usage: Moderate (80% VRAM target)
  # - Output: Both enriched LAZ and training patches
  # - Quality: High-quality labeled training data
  #
  # Use cases:
  # - Training new ML models
  # - Benchmarking model performance
  # - Research experiments
  # - Creating reference datasets
  #

  # GPU settings adaptés
  gpu_batch_size: 4_000_000
  use_gpu_chunked: true

# ============================================================================
# V5: Simplified configuration with integrated optimizations
# GROUND TRUTH - CONFIGURATION COMPLÈTE
# ============================================================================
# V5: Simplified configuration with integrated optimizations
ground_truth:
  enabled: true
  update_classification: true
  save_updated_tiles: true

  # Mode de classification pour training
  classification_mode: "lod2" # Classes optimisées training bâtiments

  # Sources de données étendues
  fetch_buildings: true
  fetch_roads: true
  fetch_water: true
  fetch_vegetation: true
  fetch_railways: true

  # NDVI pour végétation précise
  use_ndvi: true
  fetch_rgb_nir: true
  ndvi_vegetation_threshold: 0.3
  ndvi_low_vegetation_threshold: 0.15

  # Configuration bâtiments pour training
  building_buffer: 0.5
  preserve_building_nature: true
  building_height_estimation: true

  # Configuration routes détaillée
  road_width_fallback: 6.0
  preserve_road_nature: true

  # Configuration eau
  water_buffer: 1.0
  preserve_water_nature: true

  # - Creating reference datasets
#
