# ============================================================================
# IGN LiDAR HD - Minimal Test Preset V5.0 (Simplified)
# ============================================================================
# Minimal configuration for rapid testing and development
# Reduced features, minimal sources, fast processing
#
# Usage:
#   ign-lidar-hd process --config-name minimal
#   ign-lidar-hd process --config-path ign_lidar/configs/presets --config-name minimal
#
# Focus: Maximum speed for testing and development
# V5: Simplified configuration with integrated optimizations
# ============================================================================

# V5 simplified base composition
defaults:
  - ../config
  - _self_

# V5: Minimal configuration overrides (simplified)
processor:
  mode: "enriched_only" # Enrichment only for speed

  # V5 conservative settings for compatibility
  gpu_batch_size: 4_000_000 # Small batch for compatibility
  gpu_memory_target: 0.70 # Conservative for testing
  gpu_streams: 4 # Moderate parallelism

  # Auto-selection for stability
  ground_truth_method: "auto"
  reclassification_mode: "auto"

  # Disabled for stability
  enable_mixed_precision: false
  enable_memory_pooling: true
  enable_async_transfers: true
  adaptive_chunk_sizing: true

features:
  mode: "minimal" # Minimal feature set

  # Minimal parameters for maximum speed
  k_neighbors: 10 # Very small neighborhood
  search_radius: 0.5 # Very small radius

  # Essential features only
  compute_normals: true
  compute_planarity: true
  compute_height_above_ground: false # Disabled for max speed
  compute_verticality: false

  # Disable all expensive features
  compute_architectural_features: false
  compute_multiscale_features: false

  # No spectral features for speed
  use_rgb: false
  use_nir: false
  compute_ndvi: false

data_sources:
  # Minimal BD TOPO sources
  bd_topo_buildings: true # Essential only
  bd_topo_roads: true # Essential only
  bd_topo_water: false # Disabled for speed
  bd_topo_vegetation: false # Disabled for speed
  bd_topo_bridges: false
  bd_topo_power_lines: false

  # Disable all optional sources
  cadastre_enabled: false
  bd_foret_enabled: false
  rpg_enabled: false

  # No orthophotos for speed
  orthophoto_rgb: false
  orthophoto_nir: false

classification:
  enabled: true
  use_ground_truth: true # Basic ground truth only
  use_geometric_rules: true # Basic geometric rules
  use_ndvi_classification: false

  # Standard thresholds
  height_low_vegetation: 0.5
  height_medium_vegetation: 2.0
  planarity_road: 0.85
  planarity_building: 0.75

preprocess:
  enabled: false # Disabled for speed

output:
  format: "laz"
  save_enriched: true
  save_patches: false
  save_metadata: false # Minimal output for speed
  save_stats: false # Minimal output

optimization:
  level: "conservative" # Conservative for testing
  memory_management: "conservative"
  enable_caching: false # Disabled for clean testing

monitoring:
  log_level: "DEBUG" # Debug level for testing
  verbose: true # Verbose for development
  enable_performance_metrics: true
  enable_gpu_monitoring: true
# ============================================================================
# Minimal Configuration Notes
# ============================================================================
#
# Designed for:
# - Quick testing and development
# - Compatibility verification
# - Debugging and troubleshooting
# - Low-resource environments
# - CI/CD pipelines
#
# Performance expectations:
# - Processing time: <30s per tile
# - Memory usage: Very low
# - Feature quality: Basic but functional
# - Classification: Limited but working
#
# Limitations:
# - No spectral features (RGB, NIR, NDVI)
# - No height above ground computation
# - No orthophoto integration
# - No advanced data sources
# - Conservative memory usage
#
# Use cases:
# - Testing new tiles or data
# - Verifying installation
# - Quick quality checks
# - Development and debugging
#
