# ============================================================================
# IGN LiDAR HD - Preset: MINIMAL
# ============================================================================
# Inherits: base.yaml
#
# USE CASE: Quick preview, testing, development
# SPEED: ⚡ FASTEST (2-3× faster than base)
#
# FEATURES:
#   - Normals + basic planarity only
#   - Minimal external data sources
#   - Fast processing for rapid iteration
#
# WHEN TO USE:
#   ✓ Testing new datasets quickly
#   ✓ Development and debugging
#   ✓ Quick visual preview of point clouds
#   ✓ Prototyping new processing workflows
#
# USAGE:
#   ign-lidar-hd process --preset minimal input/ output/
#
# ALTERNATIVES:
#   - For building modeling → use 'lod2' preset
#   - For detailed analysis → use 'lod3' preset
#   - For classification → use 'asprs' preset
#
# Version: 5.1.0
# Week: 3 (Configuration Refactoring)
# ============================================================================

# Inherit from base configuration
defaults:
  - ../base
  - _self_

# ============================================================================
# MINIMAL PRESET OVERRIDES
# ============================================================================

# Processor: Minimal settings for maximum speed
processor:
  processing_mode: "enriched_only" # No patch extraction

  # GPU settings (required for direct config loading)
  use_gpu: true # Enable GPU acceleration (but smaller batches)
  num_workers: 1 # Single worker for GPU processing
  patch_overlap: 0.1 # 10% overlap
  num_points: 16384 # Points per patch

  # Conservative GPU settings for compatibility
  gpu_batch_size: 4_000_000 # Smaller batches for stability
  gpu_memory_target: 0.70 # Conservative memory usage
  gpu_streams: 2 # Fewer streams for simplicity

  # CUDA Optimization Settings (disabled for minimal preset)
  use_cuda_streams: false # Disabled for simplicity
  enable_memory_pooling: true # Still use memory pooling
  enable_pipeline_optimization: false # Skip for minimal preset
  auto_optimize: false # Manual configuration only
  chunk_size: null # Use defaults
  vram_limit_gb: null # Use defaults
  cleanup_frequency: 10 # Cleanup every N iterations

  # Strategy pattern
  use_strategy_pattern: true # Use new Strategy Pattern

  # Optimization flags
  use_optimized_ground_truth: false # Skip for maximum speed
  enable_async_transfers: false # Skip for simplicity
  adaptive_chunk_sizing: false # Fixed sizing for speed

  # Processing settings
  skip_existing: false # Re-process existing files
  output_format: "laz" # Output format
  use_stitching: false # Tile stitching disabled

  # Patch extraction
  patch_size: 150.0 # Patch size in meters
  architecture: "direct" # Direct patch extraction
  augment: false # No augmentation
  num_augmentations: 0 # No augmentations

  # Disable optional processing
  reclassification:
    enabled: false # Skip reclassification for speed

# Features: Absolute minimum for fastest processing
features:
  mode: "minimal" # Minimal feature set

  # Required fields for direct config loading
  include_extra: false # Minimal features only
  use_gpu_chunked: true # GPU chunked processing
  gpu_batch_size: 500_000 # Smaller batches for minimal mode
  use_nir: false # No NIR

  # Minimal geometric parameters
  k_neighbors: 10 # Very small neighborhood for speed
  search_radius: 0.5 # Very small radius

  # Essential features only
  compute_normals: true # Always needed
  compute_curvature: false # Disabled for speed
  compute_height: false # Disabled for speed
  compute_geometric: true # Basic planarity only

  # All advanced features disabled
  compute_architectural: false
  compute_boundaries: false
  compute_multiscale: false

  # No spectral features
  use_rgb: false
  use_infrared: false
  compute_ndvi: false

# Data Sources: Minimal external data
data_sources:
  # Minimal BD TOPO (only if needed for basic classification)
  bd_topo:
    enabled: false # Disabled for maximum speed

  # No orthophotos
  orthophoto_rgb: false
  orthophoto_nir: false

  # No optional sources
  cadastre_enabled: false
  bd_foret_enabled: false
  rpg_enabled: false

# Preprocessing: Required section
preprocess:
  enabled: false # Disabled by default

# Stitching: Required section
stitching:
  enabled: false # Disabled by default
  buffer_size: 10.0 # 10 meter buffer

# Output: Minimal outputs for speed
output:
  format: "laz" # Output format
  save_enriched: true # Main output
  save_patches: false # No patches
  save_metadata: false # No metadata for speed
  save_stats: false # No stats for speed

# ============================================================================
# EXPECTED PERFORMANCE
# ============================================================================
# Processing time (relative to base):
#   - 2-3× faster than base configuration
#   - 5-10× faster than LOD3
#
# Memory usage:
#   - Minimal (works on GPUs with 4GB+ VRAM)
#
# Output file size:
#   - Smallest (only essential attributes)
# ============================================================================
