# ASPRS Preprocessing with Cadastre - Full Configuration
# Usage:
#   ign-lidar-hd process --config-file configs/multiscale/config_asprs_preprocessing.yaml

# Bounding box (optional - null = process all tiles)
bbox:
  xmin: null
  ymin: null
  xmax: null
  ymax: null

# Output configuration
output:
  format: laz
  processing_mode: enriched_only
  save_stats: true
  save_metadata: false
  compression: null

# Ground truth configuration (legacy compatibility - points to data_sources)
ground_truth:
  enabled: true
  update_classification: true
  use_ndvi: true
  fetch_rgb_nir: true
  cache_dir: ${cache_dir}/ground_truth

processor:
  lod_level: ASPRS
  processing_mode: enriched_only
  skip_existing: false
  architecture: hybrid
  use_gpu: true
  num_workers: 1
  building_detection_mode: asprs
  transport_detection_mode: asprs_extended

  # Patch settings (not used in enriched_only mode, but required by config schema)
  patch_size: 150.0
  patch_overlap: 0.1
  num_points: 100000

  # Output settings
  output_format: laz
  augment: false
  num_augmentations: 0

  # Tile stitching
  use_stitching: true
  buffer_size: 10.0

  # Performance settings
  batch_size: 32 # Reduced from "auto"/64 for stability
  prefetch_factor: 2
  pin_memory: true

  # Direct enrichment mode
  apply_reclassification_inline: true
  ground_truth_integration_mode: "direct"

  # Reclassification settings
  reclassification:
    enabled: true
    acceleration_mode: auto
    use_geometric_rules: true
    ndvi_vegetation_threshold: 0.3
    ndvi_road_threshold: 0.15
    road_vegetation_height_threshold: 2.0

# ============================================================================
# FEATURES CONFIGURATION - ASPRS Optimized for RTX 4080 Super
# ============================================================================
features:
  mode: asprs_classes # Lightweight ~15 features for ASPRS
  k_neighbors: 12 # Optimized for speed (was 15)
  search_radius: 0.8 # Tighter radius = MUCH faster (was 1.2)
  include_extra: false

  # GPU acceleration settings (RTX 4080 Super - reduced for stability)
  gpu_batch_size: 3000000 # 3M points per batch (safer for memory)
  use_gpu_chunked: true # Enable chunked GPU processing

  # Core geometric features
  compute_normals: true
  compute_planarity: true
  compute_curvature: false
  compute_linearity: false
  compute_verticality: true
  compute_height_above_ground: true
  compute_horizontality: true
  compute_sphericity: true

  # Spectral features - required for NDVI
  use_rgb: true
  use_infrared: true
  compute_ndvi: true
  augment_rgb: false
  augment_infrared: false

  # Advanced features (disabled for speed)
  compute_architectural_features: false
  include_architectural_style: false
  compute_wall_likelihood: false
  compute_roof_likelihood: false
  compute_surface_variation: false
  compute_anisotropy: false
  compute_eigenvalue_features: false
  compute_local_point_density: false
  compute_roughness: false
  compute_moment_features: false
  compute_multiscale_features: false
  compute_normal_variation: false
  compute_normal_change_rate: false

  # Sampling and normalization
  sampling_method: fps
  normalize_xyz: true
  normalize_features: true

# ============================================================================
# PREPROCESSING
# ============================================================================
preprocess:
  enabled: true
  sor_enabled: true
  sor_k: 10
  sor_std: 2.0
  ror_enabled: true
  ror_radius: 1.0
  ror_neighbors: 5
  voxel_enabled: false

# ============================================================================
# TILE STITCHING
# ============================================================================
stitching:
  enabled: true
  buffer_size: 10.0
  auto_detect_neighbors: true
  auto_download_neighbors: true
  cache_enabled: true
  cache_dir: ${cache_dir}/neighbors

# ============================================================================
# DATA SOURCES - BD TOPO & CADASTRE ENABLED
# ============================================================================
data_sources:
  # BD TOPO® V3 - Infrastructure Ground Truth
  bd_topo:
    enabled: true # ✅ ENABLED for ground truth classification
    cache_enabled: true
    features:
      buildings: true # ASPRS code 6
      roads: true # ASPRS code 11 - Roads
      railways: true # ASPRS code 10 - Railways
      water: true # ASPRS code 9
      vegetation: true # ASPRS codes 3-5
      bridges: true # ASPRS code 17
      parking: true # ASPRS code 40
      sports: true # ASPRS code 41
      cemeteries: true # ASPRS code 42
      power_lines: true # ASPRS code 43
    parameters:
      road_width_fallback: 4.0
      road_buffer_tolerance: 0.5
      railway_width_fallback: 3.5
      railway_buffer_tolerance: 0.6
      power_line_buffer: 2.0
      road_height_max: 1.5
      road_height_min: -0.3
      rail_height_max: 1.2
      rail_height_min: -0.2
      road_planarity_min: 0.6
      rail_planarity_min: 0.5
      enable_intensity_filter: true
      road_intensity_min: 0.15
      road_intensity_max: 0.7
      rail_intensity_min: 0.1
      rail_intensity_max: 0.8
    cache_dir: ${cache_dir}/ground_truth

  # BD PARCELLAIRE (Cadastre) - Cadastral Parcels with Cluster IDs
  cadastre:
    enabled: true # ✅ ENABLED for cadastral enrichment
    cache_enabled: true

    # Enrichment options
    label_parcel_id: true # Add parcel ID (19 characters unique identifier)
    group_by_parcel: true # Group points by cadastral parcel
    compute_parcel_statistics: true # Calculate statistics per parcel

    # Clustering options - Create numerical cluster IDs for parcels
    create_cluster_ids: true # ✅ Create numerical cluster ID for each parcel
    cluster_id_start: 1 # Start cluster numbering at 1
    cluster_id_field: "parcel_cluster" # Field name for cluster ID in LAZ
    assign_cluster_to_points: true # ✅ Assign cluster ID to all points in parcel

    # Export attributes as extra dimensions in LAZ
    export_attributes: true # ✅ Export parcel_id and parcel_cluster to LAZ
    export_statistics: true # Export per-parcel statistics to file
    cache_dir: ${cache_dir}/cadastre

# Required paths (must be provided)
input_dir: /mnt/d/ign/selected_tiles/asprs/tiles
output_dir: /mnt/d/ign/preprocessed/asprs/enriched_tiles

# Cache directory (uses environment variable or default)
cache_dir: ${oc.env:IGN_CACHE_DIR,/tmp/ign_cache}
# Optional: Override if needed
# num_workers: 1
# verbose: true
