# ========================================================================
# LOD2 Preprocessing Configuration
# ========================================================================
# Updated: October 16, 2025 - Latest datasets (BD TOPO V3, BD Forêt V2, RPG 2024)
# Purpose: Preprocess selected tiles for LOD2 building classification
#          with enhanced features for wall/roof detection
#
# ⚠️  MODERNIZATION NOTE (October 16, 2025):
#     A NEW SIMPLIFIED VERSION exists: ign_lidar/configs/experiment/lod2_preprocessing_v2.yaml
#     - 87% smaller (50 lines vs 389 lines)
#     - Uses modular data source configs (no duplication)
#     - Easier to maintain and understand
#
#     To use the new version:
#       ign-lidar-hd process experiment=lod2_preprocessing_v2 \
#         input_dir=/path/to/tiles output_dir=/path/to/output
#
#     This file is kept for backward compatibility but will be deprecated in v3.0
#     See: MIGRATION_GUIDE.md for details
# ========================================================================
#
# Input: /mnt/d/ign/selected_tiles/lod2/tiles
# Output: Enriched LAZ tiles with building-focused features + RGB/IR/NDVI
#
# Features:
# - Enhanced geometric features (building-focused)
# - RGB, NIR, NDVI computation
# - RGB/IR augmentations
# - Ground truth from IGN BD TOPO®
# - NDVI-based preclassification (vegetation detection)
# - LOD2 mode: Wall/roof detection for buildings
# - LOD2 mode: Transport as ground class for building reconstruction
# - Building height and planarity analysis
# - Tile stitching for boundary continuity
# - Output: Enriched LAZ only (no patches)
#
# Usage:
#   ign-lidar-hd process --config config_lod2_preprocessing.yaml
# ========================================================================

defaults:
  - processor: default
  - features: enhanced
  - preprocess: default
  - stitching: enabled
  - output: default
  - ground_truth: enabled
  - _self_

# ============================================================================
# I/O PATHS
# ============================================================================
input_dir: /mnt/d/ign/selected_tiles/lod2/tiles
output_dir: /mnt/d/ign/preprocessed/lod2/enriched_tiles
cache_dir: /mnt/d/ign/cache # Root cache directory for all data sources

# ============================================================================
# PROCESSOR CONFIGURATION
# ============================================================================
processor:
  skip_existing: true
  lod_level: LOD2
  architecture: hybrid
  use_gpu: true
  num_workers: 1 # Single worker to maximize GPU utilization

  # NO patch extraction - full tile enrichment only
  patch_size: null
  patch_overlap: null
  num_points: null
  augment: false
  num_augmentations: 0

  # Performance settings
  batch_size: "auto"
  prefetch_factor: 2
  pin_memory: true

  # ========================================================================
  # DETECTION MODES - LOD2 Configuration
  # ========================================================================
  # Building Detection Mode: lod2 for wall/roof classification
  building_detection_mode: lod2

  # Transport Detection Mode: lod2 for ground-level transport surfaces
  # LOD2 mode validates transport as ground class for building reconstruction
  transport_detection_mode: lod2

  # ========================================================================
  # RECLASSIFICATION SETTINGS - GPU-Accelerated Ground Truth Application
  # ========================================================================
  # Use reclassification mode to update existing enriched files with ground truth
  # Supports: 'cpu', 'gpu', 'gpu+cuml', 'auto' (auto-detect best backend)
  reclassification:
    enabled: true # Enable to apply geometric rules during processing
    acceleration_mode: auto # Auto-detect: gpu+cuml → gpu → cpu
    chunk_size: 100000 # Points per chunk (CPU)
    gpu_chunk_size: 500000 # Larger chunks for GPU
    show_progress: true
    skip_existing: true

    # Geometric rules for intelligent refinement (LOD2 optimized)
    use_geometric_rules: true # Apply geometric rules after basic classification

    # NDVI-based refinement thresholds
    ndvi_vegetation_threshold: 0.3 # NDVI >= this value = likely vegetation
    ndvi_road_threshold: 0.15 # NDVI <= this value = likely road/impervious surface

    # Road-vegetation disambiguation
    road_vegetation_height_threshold: 2.0 # Height (m) above road to classify as vegetation

    # Building buffer zone classification (stricter for LOD2)
    building_buffer_distance: 1.5 # Smaller buffer (m) for precise building edges
    max_building_height_difference: 2.5 # Stricter height (m) tolerance for LOD2

    # Verticality-based building classification (enhanced for LOD2)
    verticality_threshold: 0.75 # Higher threshold for LOD2 wall detection
    verticality_search_radius: 1.0 # Search radius (m) for verticality computation
    min_vertical_neighbors: 8 # More neighbors for better accuracy

# ============================================================================
# TRANSPORT ENHANCEMENT - ADAPTIVE BUFFERING & SPATIAL INDEXING
# ============================================================================
transport_enhancement:
  # Adaptive buffering with curvature awareness
  adaptive_buffering:
    enabled: true
    curvature_aware: true
    curvature_factor: 0.2 # 20% width increase on curves
    min_curve_radius: 50.0
    type_specific_tolerance: true

    # LOD2: More lenient tolerances for ground validation (improved)
    tolerance_motorway: 0.6 # Highways with shoulders
    tolerance_primary: 0.6 # Major roads
    tolerance_secondary: 0.5 # Regional roads
    tolerance_residential: 0.4 # Urban roads
    tolerance_service: 0.3 # Narrow roads
    tolerance_railway_main: 0.7 # Main railways with ballast
    tolerance_railway_tram: 0.4 # Embedded trams

    # Intersection enhancement (less critical for LOD2)
    intersection_enhancement: false

    # Elevation awareness (important for bridges as non-ground)
    elevation_aware: true
    elevation_tolerance: 1.5 # Tighter filtering for ground-level detection
    elevation_min: -0.3
    elevation_max_road: 1.5
    elevation_max_rail: 1.2

  # Spatial indexing for fast processing
  spatial_indexing:
    enabled: true
    index_type: rtree
    cache_index: true
    cache_dir: /mnt/d/ign/cache/spatial_index

  # Quality metrics (focus on ground validation)
  quality_metrics:
    enabled: true
    save_confidence: true
    detect_overlaps: true
    generate_reports: false # Less critical for LOD2 ground class
    low_confidence_threshold: 0.5

# ============================================================================
# FEATURES CONFIGURATION - ENHANCED FOR BUILDING DETECTION + ARCHITECTURAL
# ============================================================================
features:
  mode: lod2 # Valid modes: minimal, lod2, lod3, asprs_classes, full
  k_neighbors: 30 # Increased for better building surface analysis
  search_radius: 2.0 # Larger radius for building features
  include_extra: true # Include extra building-specific features

  # Enhanced geometric features for walls/roofs
  compute_normals: true
  compute_planarity: true # Essential for wall/roof detection
  compute_curvature: true # Detect roof types
  compute_linearity: true # Edge detection
  compute_verticality: true # Wall detection
  compute_height_above_ground: true # Building height

  # Architectural features (essential for LOD2 wall/roof classification)
  compute_architectural_features: true
  compute_horizontality: true
  compute_wall_likelihood: true
  compute_roof_likelihood: true
  compute_facade_score: true
  compute_building_regularity: true
  compute_corner_likelihood: true

  # Spectral features with augmentations
  use_rgb: true
  use_infrared: true
  compute_ndvi: true

  # RGB/IR augmentations
  augment_rgb: true
  rgb_brightness_range: [0.8, 1.2]
  rgb_contrast_range: [0.8, 1.2]
  rgb_saturation_range: [0.8, 1.2]

  augment_infrared: true
  ir_intensity_range: [0.9, 1.1]

  # Building-specific features
  compute_surface_variation: true
  compute_anisotropy: true
  compute_eigenvalue_features: true
  compute_sphericity: true # For curved surfaces and details
  compute_omnivariance: true # 3D shape descriptors

  # Advanced geometric features for building analysis
  compute_local_point_density: true
  density_radius: 0.5 # m
  compute_roughness: true
  roughness_radius: 1.0 # m
  compute_moment_features: true # Statistical shape moments

  # Multi-scale features for buildings
  compute_multiscale_features: true
  multiscale_radii: [0.5, 1.0, 2.0, 3.0] # Multiple scales for context

  # Normal-based features
  compute_normal_variation: true
  normal_variation_radius: 1.5
  compute_normal_change_rate: true

  # Sampling and normalization
  sampling_method: fps
  normalize_xyz: true
  normalize_features: true

  # GPU acceleration
  gpu_batch_size: 1000000
  use_gpu_chunked: true

# ============================================================================
# PREPROCESSING - BUILDING-FOCUSED OUTLIER REMOVAL
# ============================================================================
preprocess:
  enabled: true

  # Statistical Outlier Removal (stricter for buildings)
  sor_enabled: true
  sor_k: 12
  sor_std: 1.8

  # Radius Outlier Removal
  ror_enabled: true
  ror_radius: 1.0
  ror_neighbors: 6

  # NO voxel downsampling - preserve all points for building details
  voxel_enabled: false

# ============================================================================
# TILE STITCHING - LARGER BUFFER FOR BUILDING CONTINUITY
# ============================================================================
stitching:
  enabled: true
  buffer_size: 20.0 # Larger buffer for building edges
  auto_detect_neighbors: true
  auto_download_neighbors: true
  cache_enabled: true
  cache_dir: /mnt/d/ign/cache/neighbors

# ============================================================================
# DATA SOURCES - MULTI-SOURCE INTEGRATION
# ============================================================================
data_sources:
  # BD TOPO® V3 - Infrastructure (focus on buildings)
  bd_topo:
    enabled: true
    cache_enabled: true
    features:
      buildings: true # Primary focus for LOD2
      roads: true
      railways: true
      water: true
      vegetation: true
      bridges: true
      parking: true
      cemeteries: false # Not essential for LOD2 building focus
      power_lines: false # Not essential for LOD2 building focus
      sports: false # Not essential for LOD2 building focus
    parameters:
      road_width_fallback: 4.0
      road_buffer_tolerance: 0.5
      railway_width_fallback: 3.5
      railway_buffer_tolerance: 0.6
      power_line_buffer: 2.0 # For consistency (if power_lines enabled)

      # Height filtering
      road_height_max: 1.5
      road_height_min: -0.3
      rail_height_max: 1.2
      rail_height_min: -0.2

      # Geometric filtering
      road_planarity_min: 0.6
      rail_planarity_min: 0.5

      # Intensity filtering
      enable_intensity_filter: true
      road_intensity_min: 0.15
      road_intensity_max: 0.7
      rail_intensity_min: 0.1
      rail_intensity_max: 0.8
    cache_dir: /mnt/d/ign/cache/ground_truth

  # BD Forêt® V2 - Forest types (limited for LOD2)
  bd_foret:
    enabled: false # Less relevant for building-focused LOD2
    cache_enabled: true
    cache_dir: /mnt/d/ign/cache/bd_foret

  # RPG 2024 - Agriculture (minimal for LOD2)
  rpg:
    enabled: false # Less relevant for building-focused LOD2
    cache_enabled: true
    year: 2024
    cache_dir: /mnt/d/ign/cache/rpg

  # Cadastre - Parcels (useful for building grouping)
  cadastre:
    enabled: true # Useful for building-parcel association
    cache_enabled: true
    group_by_parcel: true
    label_parcel_id: true
    cache_dir: /mnt/d/ign/cache/cadastre

# ============================================================================
# GROUND TRUTH - IGN BD TOPO® + BUILDING-FOCUSED PRECLASSIFICATION
# ============================================================================
ground_truth:
  enabled: true
  source: ign_bdtopo
  preclassify: true

  # NDVI-based vegetation preclassification
  ndvi_vegetation_threshold: 0.3
  ndvi_low_vegetation_threshold: 0.5
  ndvi_high_vegetation_threshold: 0.7

  # Building height thresholds (stricter for LOD2)
  building_min_height: 3.0
  building_max_height: 150.0

  # Building classification improvements (NEW - Oct 2025)
  building_buffer_tolerance: 0.0 # Strict footprint matching for LOD2
  use_building_footprints: true # Enable BD TOPO® footprint matching
  ground_truth_building_priority: high # Override other classifications

  # Post-processing for unclassified points (NEW - Oct 2025)
  # Enhanced for LOD2 wall/roof classification
  post_processing:
    enabled: true # Enable Stage 4 post-processing
    reclassify_unclassified: true # Attempt to reclassify unclassified points
    use_ground_truth_context: true # Use building footprints for context
    use_geometric_similarity: true # Use geometric features for wall/roof detection
    min_building_height: 3.0 # Minimum height for LOD2 buildings (m)
    min_building_planarity: 0.65 # Higher planarity threshold for LOD2
    min_wall_verticality: 0.7 # Minimum verticality for wall detection
    min_roof_horizontality: 0.85 # Minimum horizontality for roof detection

  # Wall/roof detection thresholds
  wall_verticality_threshold: 0.7 # Vertical surfaces
  roof_planarity_threshold: 0.8 # Flat surfaces
  roof_slope_threshold: 15.0 # Degrees for gable/hip detection

  # Ground classification
  ground_max_slope: 30.0

  # Cache ground truth data
  cache_enabled: true
  cache_dir: /mnt/d/ign/cache/ground_truth

# ============================================================================
# OUTPUT CONFIGURATION - LAZ ONLY (NO PATCHES)
# ============================================================================
output:
  format: laz # Only enriched LAZ tiles
  processing_mode: enriched_only # No patch extraction
  save_stats: true
  save_metadata: true
  compression: true

  # Metadata to save
  save_feature_stats: true
  save_class_distribution: true
  save_quality_metrics: true
  save_building_metrics: true # LOD2-specific: wall/roof stats

# ============================================================================
# LOGGING
# ============================================================================
logging:
  level: INFO
  log_file: /mnt/d/ign/logs/lod2_preprocessing.log
  progress_bar: true
