# Ground Truth Configuration - Disabled
#
# No ground truth labeling or classification update
# Updated: October 16, 2025 - Migrated to new data_sources structure

# ============================================================================
# Multi-Source Data Integration (DISABLED)
# ============================================================================

data_sources:
  bd_topo:
    enabled: false

  bd_foret:
    enabled: false

  rpg:
    enabled: false

  cadastre:
    enabled: false

# ============================================================================
# Classification Configuration (Geometric only)
# ============================================================================

classification:
  enabled: false
  methods:
    geometric: true
    ndvi: false
    ground_truth: false
    forest_types: false
    crop_types: false
