# Ground Truth Configuration - Enabled
#
# Enable ground truth labeling from IGN BD TOPO®, BD Forêt®, RPG, and Cadastre
# Updated: October 16, 2025 - Migrated to new data_sources structure

# ============================================================================
# Multi-Source Data Integration (NEW STRUCTURE)
# ============================================================================

data_sources:
  # === BD TOPO® V3 - Ground Truth Classification ===
  bd_topo:
    enabled: true
    cache_enabled: true

    features:
      buildings: true
      roads: true
      railways: true
      water: true
      vegetation: true
      bridges: true
      parking: true
      cemeteries: false
      power_lines: false
      sports: true

    parameters:
      road_width_fallback: 4.0
      road_buffer_tolerance: 0.5
      railway_width_fallback: 3.5
      railway_buffer_tolerance: 0.6
      power_line_buffer: 2.0
      road_height_max: 1.5
      rail_height_max: 1.2
      road_planarity_min: 0.6
      rail_planarity_min: 0.5
      enable_intensity_filter: true

    cache_dir: cache/ground_truth
    use_cache: true

  # === BD Forêt® V2 - Forest Classification ===
  bd_foret:
    enabled: true
    cache_enabled: true
    label_forest_type: true
    label_primary_species: true
    label_secondary_species: false
    label_tertiary_species: false
    estimate_height: true
    export_attributes: true
    attributes_to_export:
      - forest_type
      - primary_species
      - estimated_height
    cache_dir: cache/bd_foret
    use_cache: true

  # === RPG (Registre Parcellaire Graphique) - Agricultural Land ===
  rpg:
    enabled: true
    cache_enabled: true
    year: 2024
    apply_asprs_classification: true
    label_crop_code: true
    label_crop_category: true
    label_crop_name: true
    label_parcel_area: true
    label_organic_farming: true
    export_attributes: true
    attributes_to_export:
      - crop_code
      - crop_category
      - crop_name
      - parcel_area
      - is_organic
    cache_dir: cache/rpg
    use_cache: true

  # === Cadastre - Land Parcel Information ===
  cadastre:
    enabled: true
    cache_enabled: true
    group_by_parcel: true
    label_parcel_id: true
    label_parcel_area: true
    label_commune_code: true
    compute_statistics: true
    export_parcel_stats: true
    export_attributes: true
    attributes_to_export:
      - parcel_id
      - parcel_area
      - commune_code
    cache_dir: cache/cadastre
    use_cache: true

# ============================================================================
# Classification Configuration
# ============================================================================

classification:
  enabled: true
  methods:
    geometric: true
    ndvi: false
    ground_truth: true
    forest_types: true
    crop_types: true
  thresholds:
    ndvi_vegetation: 0.35
    ndvi_building: 0.15
    height_low_veg: 0.5
    height_medium_veg: 2.0
    planarity_road: 0.8
    planarity_building: 0.7
    road_buffer_tolerance: 0.5
    railway_buffer_tolerance: 0.5
  priority_order:
    - vegetation
    - water
    - cemeteries
    - parking
    - sports
    - agriculture
    - power_lines
    - railways
    - roads
    - bridges
    - buildings
