# Aggressive Preprocessing Configuration
#
# Strong outlier removal for noisy data

enabled: true

# Statistical Outlier Removal - more aggressive
sor_k: 20 # More neighbors
sor_std: 1.5 # Tighter threshold

# Radius Outlier Removal - more aggressive
ror_radius: 0.5 # Smaller radius
ror_neighbors: 6 # More neighbors required

# Voxel downsampling enabled
voxel_enabled: true
voxel_size: 0.05 # Fine voxel grid
