# Disabled Preprocessing Configuration
#
# No preprocessing (fastest)

enabled: false

# Values below are ignored when disabled=false
sor_k: 12
sor_std: 2.0
ror_radius: 1.0
ror_neighbors: 4
voxel_enabled: false
voxel_size: 0.1
