# BD TOPO® V3 - ASPRS Full Configuration
# ============================================================================
# Complete infrastructure classification with all ASPRS codes
# ============================================================================
# Date: October 16, 2025
# Use Case: Complete topographic mapping, urban planning, infrastructure inventory
# ============================================================================

# BD TOPO® V3 - All features enabled
bd_topo:
  enabled: true
  cache_enabled: true

  features:
    buildings: true # ASPRS 6
    roads: true # ASPRS 11
    railways: true # ASPRS 10
    water: true # ASPRS 9
    vegetation: true # ASPRS 3-5
    bridges: true # ASPRS 17
    parking: true # ASPRS 40
    sports: true # ASPRS 41
    cemeteries: true # ASPRS 42
    power_lines: true # ASPRS 43

  parameters:
    road_width_fallback: 4.0
    road_buffer_tolerance: 0.5
    railway_width_fallback: 3.5
    railway_buffer_tolerance: 0.6
    power_line_buffer: 2.0
    road_height_max: 1.5
    road_height_min: -0.3
    rail_height_max: 1.2
    rail_height_min: -0.2
    road_planarity_min: 0.6
    rail_planarity_min: 0.5
    enable_intensity_filter: true
    road_intensity_min: 0.15
    road_intensity_max: 0.7
    rail_intensity_min: 0.1
    rail_intensity_max: 0.8

  cache_dir: null

# Additional sources
bd_foret:
  enabled: true # Include forest classification
  cache_enabled: true
  label_forest_type: true
  label_primary_species: true
  estimate_height: true
  export_attributes: true
  cache_dir: null

rpg:
  enabled: true # Include agricultural classification
  cache_enabled: true
  year: 2024
  apply_asprs_classification: true
  label_crop_code: true
  label_crop_category: true
  export_attributes: true
  cache_dir: null

cadastre:
  enabled: false # Optional for ASPRS
  cache_enabled: true
  group_by_parcel: false
  cache_dir: null
