# @package data_sources.bd_foret
# BD Forêt® V2 - Forest Type Classification
#
# This config enables forest species and type classification.

enabled: true
year: latest # Use latest version V2

# BD Forêt features
refine_vegetation: true # Refine vegetation classification
fetch_polygons: true # Fetch forest polygons
label_species: true # Label tree species
estimate_height: true # Estimate tree heights
export_attributes: true # Export as extra LAZ dimensions

# Cache directory
cache_dir: null
