# @package data_sources.bd_topo
# BD TOPO® V3 - Minimal Ground Truth Configuration
#
# This config enables only essential BD TOPO features for fast processing.
# Use this for LOD2/LOD3 building detection where you only need core features.

enabled: true
cache_enabled: true

# Features to fetch and apply - minimal set
features:
  buildings: true # ASPRS 6 - Essential for building detection
  roads: true # ASPRS 11 - Important for ground class
  railways: false # ASPRS 10 - Disabled for speed
  water: true # ASPRS 9 - Helps with ground classification
  vegetation: false # ASPRS 5 - Can be detected geometrically
  bridges: false # ASPRS 17 - Rare, disabled for speed
  parking: false # ASPRS 40 - Can be inferred from buildings
  cemeteries: false # ASPRS 42 - Rare
  power_lines: false # ASPRS 43 - Rare
  sports: false # ASPRS 41 - Can be inferred

# Geometry generation parameters (optimized for speed)
parameters:
  # Road geometry (simplified)
  road_width_fallback: 4.0
  road_buffer_tolerance: 0.3 # Smaller buffer for speed

  # Height filtering (simplified)
  road_height_max: 1.5
  road_height_min: -0.3

  # Geometric filtering (relaxed for speed)
  road_planarity_min: 0.5

  # Intensity filtering disabled for speed
  enable_intensity_filter: false

  # Building parameters
  building_buffer_tolerance: 0.0
  use_building_footprints: true
  ground_truth_building_priority: high

# Cache directory
cache_dir: null
