# BD TOPO® V3 - Data Sources Configuration
# ============================================================================
# Multi-source data integration for ground truth classification
# ============================================================================
# Date: October 16, 2025
# Purpose: Central configuration for all IGN data sources
#
# Sources:
# - BD TOPO® V3: Infrastructure (buildings, roads, railways, etc.)
# - BD Forêt® V2: Forest types and species
# - RPG 2024: Agricultural parcels and crop types
# - BD PARCELLAIRE: Cadastral parcels
# ============================================================================

# BD TOPO® V3 - Infrastructure Ground Truth
bd_topo:
  enabled: true
  cache_enabled: true

  features:
    buildings: true # ASPRS 6 - Building structures
    roads: true # ASPRS 11 - Road surfaces
    railways: true # ASPRS 10 - Railway tracks
    water: true # ASPRS 9 - Water surfaces
    vegetation: true # ASPRS 3-5 - Vegetation refinement
    bridges: true # ASPRS 17 - Bridge decks
    parking: true # ASPRS 40 - Parking areas
    sports: true # ASPRS 41 - Sports facilities
    cemeteries: true # ASPRS 42 - Cemeteries
    power_lines: true # ASPRS 43 - Power line corridors

  parameters:
    # Buffer widths
    road_width_fallback: 4.0
    road_buffer_tolerance: 0.5
    railway_width_fallback: 3.5
    railway_buffer_tolerance: 0.6
    power_line_buffer: 2.0

    # Height filtering (exclude bridges/overpasses)
    road_height_max: 1.5
    road_height_min: -0.3
    rail_height_max: 1.2
    rail_height_min: -0.2

    # Geometric filtering
    road_planarity_min: 0.6
    rail_planarity_min: 0.5

    # Intensity filtering
    enable_intensity_filter: true
    road_intensity_min: 0.15
    road_intensity_max: 0.7
    rail_intensity_min: 0.1
    rail_intensity_max: 0.8

  cache_dir: null # null = use default cache_dir from root config

# BD Forêt® V2 - Forest types
bd_foret:
  enabled: false # Enable for vegetation classification
  cache_enabled: true
  label_forest_type: true
  label_primary_species: true
  estimate_height: true
  export_attributes: true
  cache_dir: null

# RPG 2024 - Agriculture
rpg:
  enabled: false # Enable for agricultural classification
  cache_enabled: true
  year: 2024
  apply_asprs_classification: true
  label_crop_code: true
  label_crop_category: true
  export_attributes: true
  cache_dir: null

# Cadastre - Parcels
cadastre:
  enabled: false # Enable for parcel grouping
  cache_enabled: true
  group_by_parcel: false
  label_parcel_id: false
  cache_dir: null
