# BD TOPO® V3 - Disabled Configuration
# ============================================================================
# No data source integration - geometric features only
# ============================================================================
# Date: October 16, 2025
# Use Case: Pure geometric classification without ground truth
# ============================================================================

bd_topo:
  enabled: false
  cache_enabled: false
  features:
    buildings: false
    roads: false
    railways: false
    water: false
    vegetation: false
    bridges: false
    parking: false
    sports: false
    cemeteries: false
    power_lines: false

bd_foret:
  enabled: false
  cache_enabled: false

rpg:
  enabled: false
  cache_enabled: false
  year: 2024

cadastre:
  enabled: false
  cache_enabled: false
