name: ign-lidar-hd
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy>=1.21.0
  - scikit-learn>=1.0.0
  - tqdm>=4.60.0
  - click>=8.0.0
  - pyyaml>=6.0
  - psutil>=5.8.0
  - requests>=2.25.0
  - pillow>=9.0.0
  - hydra-core>=1.3.0
  - omegaconf>=2.3.0
  - pip
  - pip:
      - laspy>=2.3.0
      - lazrs>=0.5.0
