name: ign-lidar-hd
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy>=1.21.0
  - scikit-learn>=1.0.0
  - tqdm>=4.60.0
  - click>=8.0.0
  - pyyaml>=6.0
  - psutil>=5.8.0
  - requests>=2.25.0
  - pillow>=9.0.0
  - hydra-core>=1.3.0
  - omegaconf>=2.3.0
  - h5py>=3.0.0
  # Optional: PyTorch (uncomment for deep learning support)
  # - pytorch>=2.0.0
  # - torchvision
  # - torchaudio

  - pip
  - pip:
      - laspy>=2.3.0
      - lazrs>=0.5.0

  # Optional GPU dependencies (uncomment for GPU acceleration):
  # For CuPy (basic GPU acceleration - 6-8x speedup):
  # Choose ONE based on your CUDA version:
  # - cupy  # Auto-detects CUDA version (conda only)
  # Or via pip (uncomment in pip section):
  #   - cupy-cuda11x>=12.0.0  # For CUDA 11.x
  #   - cupy-cuda12x>=12.0.0  # For CUDA 12.x

  # For RAPIDS cuML (full GPU acceleration - 12-20x speedup):
  # Requires separate installation:
  # conda install -c rapidsai -c conda-forge -c nvidia cuml=24.10 python=3.12
  # OR add to channels: rapidsai, nvidia and uncomment below:
  # - cuml>=23.10.0
