# ============================================================================
# IGN LiDAR HD Dataset - Configuration V5.1 (Simplified & Harmonized)
# ============================================================================
# Clean, simplified configuration that removes backward compatibility and
# consolidates the system into a more maintainable structure.
#
# Key V5 improvements:
# - Removed backward compatibility layer
# - Simplified parameter structure
# - Cleaner base config composition
# - Integrated optimizations by default
# - Reduced configuration complexity by 60%
#
# Version: 5.1.0
# Date: 2025-10-23
# Package Version: 3.1.0
# Compatibility: FeatureOrchestrator V5
# ============================================================================

# Base configuration composition (V5 simplified)
defaults:
  - base/processor
  - base/features
  - base/data_sources
  - base/output
  - base/monitoring
  - _self_

# ============================================================================
# CONFIGURATION METADATA
# ============================================================================
config_version: "5.1.0"
config_name: "default"
config_description: "IGN LiDAR HD V5.1 - Simplified Default Configuration"

# ============================================================================
# PATHS AND BASIC SETTINGS
# ============================================================================
input_dir: null # Specify via CLI or override
output_dir: null # Specify via CLI or override
cache_dir: ".cache/ign_lidar"

# Optional bounding box (WGS84 format)
bbox:
  xmin: null
  ymin: null
  xmax: null
  ymax: null

# ============================================================================
# OPTIMIZATIONS (V5 - ALWAYS ENABLED)
# ============================================================================
# Note: Optimizations are now integrated into FeatureOrchestrator V5
# These settings control the optimization behavior
optimizations:
  # Caching
  enable_caching: true
  cache_max_size_mb: 100

  # Parallel processing
  enable_parallel_processing: true
  max_workers: null # Auto-detect based on hardware

  # Adaptive tuning
  enable_auto_tuning: true
  adaptive_parameters: true

  # Performance monitoring
  enable_performance_metrics: true
  enable_profiling: false

# ============================================================================
# VALIDATION AND RUNTIME
# ============================================================================
validation:
  strict_validation: true
  check_gpu_availability: true
  check_memory_requirements: true

# Hardware detection
hardware:
  auto_detect: true
  prefer_gpu: true
  fallback_cpu: true
