# Multi-Scale Feature Computation - Aggressive Artifact Suppression
# IGN LiDAR HD Processing v6.2
#
# This configuration uses 4 scales with high variance penalty for
# maximum artifact suppression. Best for highly problematic datasets.
#
# Use case: Datasets with severe scan line artifacts, noisy data
# Expected artifact reduction: 30-50% → 2-5%
# Performance: ~4x single-scale computation

processor:
  lod_level: LOD2
  processing_mode: patches_only
  use_gpu: false # Set to true if GPU available for better performance
  patch_size: 150.0
  num_points: 16384

preprocess:
  enabled: false
  sor_k: 12
  sor_std: 2.0
  ror_radius: 1.0
  ror_neighbors: 4
  voxel_enabled: false
  voxel_size: 0.1

stitching:
  enabled: false
  buffer_size: 10.0
  auto_detect_neighbors: true
  auto_download_neighbors: false
  cache_enabled: true

features:
  mode: lod2
  k_neighbors: 30
  search_radius: 3.0

  # Enable multi-scale computation
  multi_scale_computation: true

  # Define 4 scales: ultra-fine, fine, medium, coarse
  scales:
    - name: ultra_fine
      k_neighbors: 15
      search_radius: 0.5
      weight: 0.15 # Lowest weight (very artifact-prone)

    - name: fine
      k_neighbors: 30
      search_radius: 1.5
      weight: 0.25 # Low-medium weight

    - name: medium
      k_neighbors: 80
      search_radius: 3.0
      weight: 0.40 # Highest weight (most reliable)

    - name: coarse
      k_neighbors: 150
      search_radius: 6.0
      weight: 0.20 # Medium weight (smoothing)

  # Aggressive aggregation settings
  aggregation_method: variance_weighted
  variance_penalty_factor: 3.0 # High penalty for variance

  # Comprehensive artifact detection
  detect_artifacts: true
  artifact_variance_threshold: 0.10 # Lower threshold (more sensitive)
  artifact_gradient_threshold: 0.08 # Lower threshold (more sensitive)

  # Adaptive scale selection (experimental)
  adaptive_scale_selection: false # Not yet fully implemented
  complexity_threshold: 0.3

  # Output all diagnostic data
  save_per_scale_features: true
  save_artifact_mask: true

  # Performance settings
  parallel_scale_computation: false # Can enable if enough memory
  cache_kdtrees: true

  # RGB/NIR augmentation
  use_rgb: true
  use_nir: true
  rgb_cache_dir: null

data_sources:
  bd_topo:
    buildings: true
    roads: true
    vegetation: true
    water: true
    railways: true

output:
  enriched_laz: true
  patches: true
  classification_stats: true

  # Additional output for analysis
  save_intermediate_results: true
