# Example Configuration: FeatureComputer with Forced GPU Chunked Mode
#
# This configuration forces the GPU_CHUNKED computation mode, which is optimal for:
# - Large point clouds (millions of points)
# - GPU with limited memory
# - Maximum GPU utilization
#
# Use this when you know GPU_CHUNKED is the best mode for your workload.
#
# Package Version: 3.1.0
# Config Version: 5.1.0 (Legacy - Consider using preset with GPU optimizations instead)
# Date: October 18, 2025

# Configuration metadata
config_version: "3.0.0"
config_type: "legacy_example"

# Processing Configuration
processor:
  # NEW (Phase 4): Enable FeatureComputer
  use_feature_computer: true

  # Force specific computation mode
  computation_mode: "gpu_chunked" # Options: cpu, gpu, gpu_chunked, boundary

  # Tile processing
  tile_size: 1000 # meters
  buffer_size: 10.0 # meters

  # Memory management
  max_memory_gb: 16

  # Processing options
  num_workers: 4
  save_intermediate: false

# Feature Configuration
features:
  # K-nearest neighbors for feature computation
  k_neighbors: 20

  # Search strategy
  search_radius: null # Use k-neighbors instead of radius

  # Features to compute
  compute_normals: true
  compute_curvature: true
  compute_geometric: true
  compute_height: true

# Feature Mode
feature_mode: "lod3" # High-detail mode

# Input/Output
input:
  data_source: "ign_lidar_hd"
  tile_codes:
    - "0830_6283"

output:
  directory: "./output"
  format: "laz"
  compression: true
  save_enriched: true

# Logging
logging:
  level: "INFO"
  log_mode_selection: true
  log_recommendations: true
