# Custom Configuration Example - Quick Enrichment
# Use this for fast LAZ enrichment without patches (GIS workflows)

processor:
  lod_level: LOD2
  use_gpu: false # Can set to true if GPU available
  num_workers: 4

features:
  mode: minimal # Fast minimal features
  k_neighbors: 20
  use_rgb: true
  use_infrared: false
  compute_ndvi: false

preprocess:
  enabled: false # Skip for speed

stitching:
  enabled: false # Skip for speed

output:
  processing_mode: enriched_only # Only LAZ files
  format: laz
  save_stats: false # Skip for speed
  save_metadata: false # Skip for speed

# REQUIRED: Set these when running
input_dir: ??? # Set with: input_dir=/path/to/raw/data
output_dir: ??? # Set with: output_dir=/path/to/enriched
