# ========================================================================
# LOD3 Training Patches Configuration - 50m Scale (Fine Details)
# ========================================================================
# Purpose: Generate ML training patches focusing on fine architectural details
#
# Key Features:
# - Small patch size (50m) for local features: windows, balconies, ornaments
# - Point count (24k) suitable for detailed geometric analysis
# - Higher overlap (15%) to capture boundary features
# - More augmentations (5) for increased training diversity
# - Smaller k-neighbors (20) for fine-grained feature computation
#
# Use Case:
# - Training on small residential buildings
# - Fine architectural detail classification
# - Local texture and pattern recognition
# - Part of multi-scale training strategy (Phase 1)
#
# Output Example:
#   LHD_FXX_0649_6863_hybrid_patch_0001.npz (24,576 points)
#   LHD_FXX_0649_6863_hybrid_patch_0001.laz
# ========================================================================

processor:
  lod_level: LOD3
  architecture: hybrid
  use_gpu: true
  num_workers: 1
  patch_size: 50.0 # Small patches for fine architectural details
  patch_overlap: 0.15 # Higher overlap for better boundary coverage
  num_points: 24576 # 24k points suitable for small patches
  augment: false
  num_augmentations: 5 # More augmentation for training diversity
  pin_memory: true

features:
  mode: full
  k_neighbors: 20 # Smaller neighborhood for fine details
  include_extra: true
  use_rgb: true
  use_infrared: true
  compute_ndvi: true
  sampling_method: fps
  normalize_xyz: true
  normalize_features: true
  gpu_batch_size: 1000000
  use_gpu_chunked: true

preprocess:
  enabled: true
  sor_k: 10 # Plus tolérant pour conserver plus de points
  sor_std: 2.5 # Seuil plus élevé = moins de points retirés
  ror_radius: 0.75 # Rayon plus large pour la détection d'outliers
  ror_neighbors: 2 # Moins de voisins requis = moins strict
  voxel_enabled: false
  voxel_size: 0.1

stitching:
  enabled: true
  buffer_size: 8.0 # Smaller buffer for 50m patches
  auto_detect_neighbors: true
  auto_download_neighbors: true
  cache_enabled: true

output:
  format: npz,laz
  processing_mode: patches_only
  save_stats: true
  save_metadata: true
  compression: null

input_dir: /mnt/c/Users/Simon/ign/versailles/input
output_dir: /mnt/c/Users/Simon/ign/versailles/output
