# ========================================================================
# Architectural Heritage Analysis Configuration
# ========================================================================
# Purpose: Process heritage sites with architectural style classification
#          for analysis and visualization (not training)
#
# Key Features:
# - Constant encoding (memory efficient)
# - Full-resolution processing (no subsampling)
# - Multi-format output with style annotations
# - Style statistics and distribution analysis
# - Optimized for large heritage site datasets
#
# Use Cases:
# - Architectural heritage documentation
# - Urban planning and conservation
# - Historical building analysis
# - 3D GIS integration with style metadata
#
# Usage:
#   ign-lidar-hd process experiment=architectural_analysis \
#     input_dir=/path/to/tiles output_dir=/path/to/enriched
# ========================================================================

processor:
  lod_level: LOD3
  architecture: hybrid
  use_gpu: true
  num_workers: 4 # More workers for faster processing

  # No patching - enrich full tiles
  patch_size: null
  patch_overlap: 0.0
  num_points: null

  # No augmentation for analysis
  augment: false
  num_augmentations: 0

  # Architectural style configuration (memory efficient)
  include_architectural_style: true
  style_encoding: constant # Constant encoding (single ID per point)

  pin_memory: true

features:
  mode: full
  k_neighbors: 30
  search_radius: 1.5
  include_extra: true

  # Spectral features
  use_rgb: true
  use_nir: false
  compute_ndvi: false

  # Architectural style features
  include_architectural_style: true
  style_encoding: constant # Memory-efficient constant encoding
  style_from_building_features: true # Refine styles from building geometry

  # PointNet++ settings (not used for full tile processing)
  sampling_method: random
  normalize_xyz: false
  normalize_features: false

  # GPU settings
  gpu_batch_size: 2000000
  use_gpu_chunked: true

preprocess:
  enabled: true
  sor_k: 12
  sor_std: 2.0
  ror_radius: 1.0
  ror_neighbors: 4
  voxel_enabled: false

stitching:
  enabled: false # Disable stitching for faster processing
  buffer_size: 0.0
  auto_detect_neighbors: false
  auto_download_neighbors: false
  cache_enabled: false

output:
  # LAZ output with all features including architectural style
  format: laz

  # Enrich tiles only (no patching)
  processing_mode: enriched_only

  # Save detailed statistics
  save_stats: true # Includes style distribution statistics
  save_metadata: true # Includes style metadata per tile
  compression: null

# Example paths
input_dir: ??? # /path/to/raw/tiles
output_dir: ??? # /path/to/enriched/tiles

# ============================================================================
# OUTPUT FEATURES
# ============================================================================
# The enriched LAZ files will include:
#
# Standard LiDAR:
#   - XYZ coordinates
#   - Intensity
#   - Return number
#   - Classification
#   - RGB (if available)
#
# Geometric Features:
#   - Normals (3D)
#   - Curvature
#   - Eigenvalues (3D)
#   - Height features
#   - Building scores
#   - Density features
#   - Architectural features
#
# Architectural Style:
#   - architectural_style: Style ID (0-12)
#     Available as extra dimension in LAZ
#
# Metadata (JSON):
#   - Style distribution histogram
#   - Dominant style per tile
#   - Confidence scores
#   - Style names and descriptions
# ============================================================================

# ============================================================================
# ARCHITECTURAL STYLE CLASSES
# ============================================================================
# The following 13 architectural styles are supported:
#
#   0: unknown       - Unknown or unclassified
#   1: classical     - Classical/Traditional French architecture
#   2: gothic        - Gothic (medieval churches, cathedrals)
#   3: renaissance   - Renaissance (châteaux, palaces)
#   4: baroque       - Baroque ornate style
#   5: haussmann     - Haussmannian (Paris-style buildings)
#   6: modern        - Modern/Contemporary (20th-21st century)
#   7: industrial    - Industrial buildings and warehouses
#   8: vernacular    - Vernacular/Local traditional rural
#   9: art_deco      - Art Deco style (1920s-1940s)
#  10: brutalist     - Brutalist concrete architecture
#  11: glass_steel   - Modern glass and steel buildings
#  12: fortress      - Military fortifications and fortresses
#
# View with QGIS or CloudCompare by styling the 'architectural_style' dimension
# ============================================================================
