# Example Configuration: UnifiedFeatureComputer with Automatic Mode Selection
#
# This configuration enables the new UnifiedFeatureComputer which automatically
# selects the optimal computation mode (CPU, GPU, GPU_CHUNKED) based on:
# - Available hardware (GPU presence)
# - Point cloud size
# - Memory constraints
#
# Use this for maximum simplicity and automatic optimization.

# Processing Configuration
processor:
  # NEW (Phase 4): Enable UnifiedFeatureComputer with automatic mode selection
  use_unified_computer: true

  # Tile processing
  tile_size: 1000 # meters
  buffer_size: 10.0 # meters

  # Optional: Help mode selector make better decisions
  typical_points_per_tile: 2000000 # Approximate points per tile

  # Memory management
  max_memory_gb: 16

  # Processing options
  num_workers: 4
  save_intermediate: false

# Feature Configuration
features:
  # K-nearest neighbors for feature computation
  k_neighbors: 20

  # Search strategy
  search_radius: null # Use k-neighbors instead of radius

  # Features to compute
  compute_normals: true
  compute_curvature: true
  compute_geometric: true
  compute_height: true

# Feature Mode (controls which features to include)
feature_mode: "lod2" # Options: minimal, lod2, lod3, full

# Input/Output
input:
  data_source: "ign_lidar_hd"
  tile_codes:
    - "0830_6283"
    - "0830_6284"

output:
  directory: "./output"
  format: "laz"
  compression: true
  save_enriched: true

# Logging
logging:
  level: "INFO"
  log_mode_selection: true # Log automatic mode selection decisions
  log_recommendations: true # Log expert recommendations
