processor:
  lod_level: LOD3
  architecture: hybrid
  use_gpu: true
  num_workers: 1 # Sequential processing to avoid memory duplication
  patch_size: 150.0 # Not used in enriched-only mode
  patch_overlap: 0.0 # Not used in enriched-only mode
  num_points: 32768 # Not used in enriched-only mode
  augment: false
  num_augmentations: 0
  batch_size: 1 # Optimized for single worker
  prefetch_factor: 1 # Minimal prefetch
  pin_memory: true # Disabled to save RAM
features:
  mode: full
  k_neighbors: 30
  include_extra: true
  use_rgb: true
  use_infrared: true
  compute_ndvi: true
  sampling_method: fps # Not used for enriched LAZ only
  normalize_xyz: false # Keep original coordinates in LAZ
  normalize_features: false # Keep original feature values in LAZ
  gpu_batch_size: 1000000 # 1M points per GPU chunk for efficient processing
  use_gpu_chunked: true # CRITICAL: GPU chunked processing enabled
preprocess:
  enabled: false
  sor_k: 0 # DISABLED: SOR is extremely slow on large point clouds
  sor_std: 1.5
  ror_radius: 0.0 # DISABLED - skip ROR too
  ror_neighbors: 0
  voxel_enabled: false # GPU accelerated voxelization
  voxel_size: 0.1 # Voxel downsampling to 10cm (can be enabled if needed)
stitching:
  enabled: false # Disabled - not creating patches
  buffer_size: 0.0
  auto_detect_neighbors: false
  auto_download_neighbors: false
  cache_enabled: false
output:
  format: npz # Output format for patches (npz, hdf5, pytorch, laz)
  processing_mode: enriched_only # Only create enriched LAZ files (no patches)
  save_stats: true
  save_metadata: true
  compression: null
