# ============================================================================
# Versailles Dataset - ASPRS + Parcel Classification (Phase 1)
# ============================================================================
# Purpose: Process Versailles LiDAR data with parcel-based classification
#          for spatial coherence and improved accuracy
#
# Features:
# - Parcel-based clustering (Stage 0 - NEW)
# - Cadastre (BD Parcellaire) grouping
# - BD Forêt forest validation
# - RPG agricultural parcel validation
# - ASPRS LAS 1.4 classification
# - Ground truth from IGN BD TOPO®
# - Full feature computation
#
# Expected improvements:
# - 3-7× faster processing
# - +14% overall accuracy
# - +17% vegetation recall
# - Spatially coherent results within parcels
#
# Usage:
#   ign-lidar-hd process --config-file examples/config_parcel_versailles.yaml
#
# Package Version: 3.1.0
# Config Version: 5.1.0 (Phase 1 - Parcel Classification)
# Date: October 23, 2025
# ============================================================================

# Inherit from ASPRS preset
defaults:
  - presets/asprs
  - _self_

# Configuration metadata
config_version: "5.1.0"
config_name: "parcel_versailles"
config_description: "Versailles - ASPRS + Parcel Classification"

# Custom paths for Versailles dataset
input_dir: /mnt/c/Users/Simon/ign/versailles
output_dir: /mnt/c/Users/Simon/ign/versailles_parcel

# ============================================================================
# PROCESSOR - Enable Parcel Classification
# ============================================================================

processor:
  # Enable parcel-based classification (NEW - Phase 1)
  use_parcel_classification: true

  # Classification settings (inherited from ASPRS)
  lod_level: "ASPRS"
  processing_mode: "enriched_only"

  # Processing options
  num_workers: 1
  skip_existing: true
  use_gpu: true

# ============================================================================
# PARCEL CLASSIFICATION CONFIGURATION
# ============================================================================

parcel_classification:
  # Minimum points per parcel (filter small parcels)
  min_parcel_points: 20
  min_parcel_area: 10.0

  # Confidence threshold for parcel type assignment
  parcel_confidence_threshold: 0.6

  # Enable point-level refinement within parcels
  refine_points: true
  refinement_method: "feature_based"

  # NDVI Thresholds
  forest_ndvi_min: 0.5
  agriculture_ndvi_min: 0.2
  agriculture_ndvi_max: 0.6
  building_ndvi_max: 0.15
  road_ndvi_max: 0.15
  water_ndvi_max: -0.05

  # Geometric Thresholds
  forest_curvature_min: 0.25
  forest_planarity_max: 0.6
  building_verticality_min: 0.6
  building_planarity_min: 0.7
  road_planarity_min: 0.85
  water_planarity_min: 0.9

# ============================================================================
# GROUND TRUTH INTEGRATION - Parcel Classification
# ============================================================================

ground_truth:
  # Enable ground truth classification
  enabled: true

  # Processing method (GPU recommended)
  method: "auto" # Auto-detect GPU/CPU
  chunk_size: 4_000_000 # 4M points per chunk

  # Cache configuration
  cache_dir: null # Auto-set to {input_dir}/cache/ground_truth
  cache_ttl_days: 30 # 30 days cache
  cache_compression: true

  # Pre-classify with BD TOPO and cadastre
  preclassify: true

  # BD TOPO settings for parcel classification
  bd_topo:
    enabled: true

    # Enhanced classification for parcel coherence
    classification_mapping:
      buildings: 6 # ASPRS Building
      roads: 11 # ASPRS Road
      water: 9 # ASPRS Water
      low_vegetation: 3 # ASPRS Low vegetation
      medium_vegetation: 4 # ASPRS Medium vegetation
      high_vegetation: 5 # ASPRS High vegetation
      bridges: 17 # ASPRS Bridge deck

    # Conservative buffers for parcel boundaries
    road_buffer: 2.5
    building_buffer: 0.3
    water_buffer: 1.0
    road_width_fallback: 4.0

  # CADASTRE SETTINGS - CRITICAL FOR PARCEL CLASSIFICATION
  cadastre:
    enabled: true # Required for parcel-based classification

    # Parcel filtering thresholds
    min_parcel_area: 10.0 # m² (matches parcel_classification.min_parcel_area)
    min_parcel_points: 20 # points (matches parcel_classification.min_parcel_points)

    # Enable parcel grouping
    group_by_parcel: true

    # Export parcel statistics
    export_parcel_stats: true # NEW - export parcel classification stats

  # Priority-based integration (BD TOPO + Cadastre + Features)
  integration:
    method: "priority_based"
    priority:
      cadastre: 1 # Highest priority - parcel boundaries
      bd_topo: 2 # BD TOPO features within parcels
      orthophoto: 3 # NDVI for vegetation within parcels
      geometric_rules: 4 # Fallback for uncovered areas
    confidence_threshold: 0.6 # Match parcel_classification threshold

  # Quality control
  quality_control:
    enabled: true
    validate_geometries: true
    check_coverage: true
    min_coverage_ratio: 0.3 # Expect good coverage with cadastre

  # Performance settings
  use_gpu: true
  parallel_fetch: true
  max_parallel_requests: 4
  show_progress: true

# ============================================================================
# DATA SOURCES - Enable Cadastre, BD Forêt, RPG
# ============================================================================

data_sources:
  # BD TOPO (inherited from ASPRS preset)
  bd_topo:
    enabled: true
    features:
      buildings: true
      roads: true
      water: true
      vegetation: true

  # Cadastre (BD Parcellaire) - REQUIRED for parcel classification
  cadastre_enabled: true

  # BD Forêt - Improves forest classification
  bd_foret_enabled: true

  # RPG - Improves agriculture classification
  rpg_enabled: true

  # Orthophotos
  orthophoto_rgb: true
  orthophoto_nir: true

# ============================================================================
# FEATURES - Required for Parcel Classification
# ============================================================================

features:
  # Feature mode (inherited from ASPRS)
  mode: "asprs_classes"

  # Essential features for parcel classification
  compute_ndvi: true
  compute_height: true
  compute_verticality: true
  compute_planarity: true
  compute_curvature: true
  compute_normals: true

# ============================================================================
# OUTPUT - Export Parcel Statistics
# ============================================================================

output:
  format: "laz"
  save_enriched: true
  save_metadata: true
  save_stats: true

  # NEW: Export parcel classification statistics
  export_parcel_stats: true
  parcel_stats_format: "csv"

# ============================================================================
# PREPROCESS
# ============================================================================
preprocess:
  enabled: false
  remove_duplicates: true
  remove_outliers: true
  outlier_std_multiplier: 3.0


stitching:
  enabled: false
  buffer_size: 10.0
  blend_overlap: true


# Hydra output directory
hydra:
  run:
    dir: outputs/versailles_parcel/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    name: versailles_parcel
# ============================================================================
# All other settings inherited from ASPRS preset
# ============================================================================
