# ========================================================================
# Versailles Dataset - LOD3 Extended Building Classification (V5.1 Preset-Based)
# ========================================================================
# Purpose: Process Versailles LiDAR data with LOD3 extended classification
#
# LOD3 Classes (30):
# - Walls: plain, with windows, with door
# - Roofs: flat, gable, hip, mansard, shed, gambrel, butterfly, dome, other
# - Openings: window, door, balcony door
# - Details: chimney, dormer, balcony, overhang, gutter, parapet
# - Context: foundation, ground, vegetation, water, vehicle, other
#
# Usage:
#   ign-lidar-hd process --config examples/config_versailles_lod3_v5.1.yaml
# ========================================================================

# Use LOD3 preset (inherits from base.yaml)
preset: lod3

# Custom paths for Versailles dataset
input_dir: /mnt/c/Users/Simon/ign/versailles
output_dir: /mnt/c/Users/Simon/ign/versailles_processed_lod3

# Ground truth caching
ground_truth:
  cache_dir: /mnt/c/Users/Simon/ign/cache/ground_truth

# Hydra output directory
hydra:
  run:
    dir: outputs/versailles_lod3/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    name: versailles_lod3
# ========================================================================
# All other settings inherited from lod3 preset:
# - GPU acceleration enabled
# - LOD3 classification (30 classes)
# - Full geometric + spectral features
# - Architectural style detection
# - Optimized ground truth classification
# - Geometric reclassification refinement
# - Statistical + radius outlier removal
# - Tile stitching with 15m buffer
# - Output: LAZ + NPZ patches for training
# ========================================================================
