# Custom Configuration Example - Training Dataset Creation
# Use this to create ML-ready training patches with augmentation

processor:
  lod_level: LOD2
  architecture: pointnet++
  use_gpu: false
  num_workers: 4
  patch_size: 100.0
  num_points: 16384
  augment: true
  num_augmentations: 5 # Create 5 augmented versions per patch

features:
  mode: full
  k_neighbors: 20
  search_radius: 1.5 # Radius search eliminates scan line artifacts
  include_extra: true
  use_rgb: true
  normalize_xyz: true # Normalize coordinates for PointNet++
  normalize_features: true # Standardize features

preprocess:
  enabled: true
  sor_k: 12
  sor_std: 2.0

stitching:
  enabled: true
  buffer_size: 10.0
  auto_detect_neighbors: true
  auto_download_neighbors: false

output:
  processing_mode: patches_only # Only patches for ML training
  format: npz
  save_stats: true
  save_metadata: true
  skip_existing: true

# REQUIRED: Set these when running
input_dir: ??? # Set with: input_dir=/path/to/raw/data
output_dir: ??? # Set with: output_dir=/path/to/training/patches
