# ========================================================================
# Versailles Dataset - ASPRS Classification (V5.1)
# ========================================================================
# Purpose: Process Versailles LiDAR data with ASPRS LAS 1.4 standard
#          classification (Ground, Vegetation, Building, Water, etc.)
#
# Features:
# - ASPRS-compliant classification codes
# - Ground truth from IGN BD TOPO®
# - Full feature computation (RGB, NIR, NDVI, geometric)
# - Optimal preprocessing (outlier removal)
#
# Usage:
#   ign-lidar-hd process --config-file examples/config_versailles_asprs_v5.1.yaml
# ========================================================================

# Inherit from ASPRS preset (Hydra defaults system)
defaults:
  - presets/asprs
  - _self_

# Custom paths for Versailles dataset
input_dir: /mnt/c/Users/Simon/ign/versailles
output_dir: /mnt/c/Users/Simon/ign/versailles

# Processor settings
processor:
  skip_existing: true # Don't reprocess existing tiles
  num_workers: 1 # Single worker for this dataset

# Ground truth caching
ground_truth:
  cache_dir: /mnt/c/Users/Simon/ign/cache/ground_truth

# Hydra output directory
hydra:
  run:
    dir: outputs/versailles_asprs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    name: versailles_asprs
# ========================================================================
# All other settings inherited from asprs preset:
# - GPU acceleration enabled
# - ASPRS classification scheme
# - Full geometric + spectral features
# - Optimized ground truth classification
# - Geometric reclassification refinement
# - Statistical + radius outlier removal
# - Tile stitching with 15m buffer
# - Output: LAZ + NPZ patches for training
# ========================================================================
