# Example Configuration: FeatureComputer with Forced CPU Mode
#
# This configuration forces CPU computation mode, which is optimal for:
# - Small to medium point clouds
# - Systems without GPU
# - Development/debugging
# - Reproducible results
#
# Use this when you want deterministic CPU computation.
#
# Package Version: 3.1.0
# Config Version: 5.1.0 (Legacy - Consider using presets/hardware/cpu_only.yaml instead)
# Date: October 23, 2025

# Configuration metadata
config_version: "5.1.0"
config_type: "legacy_example"

# Processing Configuration
processor:
  # NEW (Phase 4): Enable FeatureComputer
  use_feature_computer: true

  # Force CPU mode
  computation_mode: "cpu"

  # Tile processing
  tile_size: 1000 # meters
  buffer_size: 10.0 # meters

  # Memory management
  max_memory_gb: 8

  # Processing options
  num_workers: 8 # More workers for CPU parallelization
  save_intermediate: false

# Feature Configuration
features:
  # K-nearest neighbors for feature computation
  k_neighbors: 20

  # Search strategy
  search_radius: null # Use k-neighbors instead of radius

  # Features to compute
  compute_normals: true
  compute_curvature: true
  compute_geometric: true
  compute_height: true

# Feature Mode
feature_mode: "lod2" # Standard mode

# Input/Output
input:
  data_source: "ign_lidar_hd"
  tile_codes:
    - "0830_6283"

output:
  directory: "./output"
  format: "laz"
  compression: true
  save_enriched: true

# Logging
logging:
  level: "INFO"
  log_mode_selection: true
  log_recommendations: true
