# ============================================================================
# IGN LiDAR HD - AGGRESSIVE Building Classification Configuration v5.5
# ============================================================================
# Purpose: Maximize building point capture with aggressive classification
#
# KEY IMPROVEMENTS for Missing Building Points:
# 1. ✅ Lower thresholds for building detection (planarity, verticality)
# 2. ✅ Larger building buffer zones (up to 8m vs 6m)
# 3. ✅ Enable 3D bounding box extrusion (captures overhangs, balconies)
# 4. ✅ More aggressive adaptive expansion (up to 10m)
# 5. ✅ Lower confidence thresholds (0.35 vs 0.45)
# 6. ✅ Reduced minimum height (0.8m vs 1.2m for low buildings)
# 7. ✅ Enhanced fuzzy boundaries (up to 8m outer buffer)
# 8. ✅ Aggressive post-processing (gap filling, morphological closing)
#
# Expected Improvement: +30-50% more building points classified
#
# Usage:
#   ign-lidar-hd process \
#     -c examples/config_asprs_aggressive_buildings_v5.5.yaml \
#     input_dir="/path/to/tiles" \
#     output_dir="/path/to/output"
# ============================================================================

defaults:
  - base/processor
  - base/features
  - base/data_sources
  - base/output
  - base/monitoring
  - _self_

# Configuration metadata
config_version: "5.5.0"
config_name: "asprs_aggressive_buildings_v5.5"
config_description: "Aggressive Building Classification - Maximum Coverage"

# ============================================================================
# PROCESSOR - Aggressive Building Classification
# ============================================================================
processor:
  lod_level: "ASPRS"
  processing_mode: "enriched_only"

  use_gpu: false
  num_workers: 1

  chunk_size: 3_000_000
  ground_truth_method: "strtree"
  ground_truth_chunk_size: 3_000_000

  use_strategy_pattern: true

  skip_existing: false
  output_format: "laz"
  use_stitching: false

  patch_size: 50.0
  patch_overlap: 0.1
  num_points: 24576
  architecture: "direct"
  augment: false
  num_augmentations: 0

  # ⚡ AGGRESSIVE RECLASSIFICATION SETTINGS
  reclassification:
    enabled: true
    acceleration_mode: "cpu"
    chunk_size: 1_500_000
    min_confidence: 0.35 # ⬇️ Lowered from 0.45 - more permissive
    use_geometric_rules: true
    use_ndvi_classification: true
    show_progress: true
    ndvi_vegetation_threshold: 0.35 # ⬆️ Raised from 0.3 - stricter vegetation filter
    ndvi_road_threshold: 0.18 # ⬆️ Raised from 0.15
    use_spectral_rules: true
    nir_vegetation_threshold: 0.40 # ⬆️ Raised from 0.35
    nir_building_threshold: 0.20 # ⬇️ Lowered from 0.25 - more buildings
    use_clustering: true
    spatial_cluster_eps: 0.8 # ⬆️ Increased from 0.6 - larger clusters
    min_cluster_size: 2 # ⬇️ Reduced from 3 - smaller clusters ok
    building_buffer_distance: 8.0 # ⬆️ Increased from 6.0 - wider capture
    verticality_threshold: 0.45 # ⬇️ Lowered from 0.50 - more walls captured

  # ⚡ AGGRESSIVE BUILDING CLUSTERING
  building_clustering:
    enabled: true
    use_centroid_attraction: true
    attraction_radius: 6.0 # ⬆️ Increased from 5.0
    min_points_per_building: 5 # ⬇️ Reduced from 10 - smaller buildings ok
    adjust_polygons: true
    polygon_buffer: 1.0 # ⬆️ Increased from 0.5 - more generous
    wall_buffer: 0.8 # ⬆️ Increased from 0.3
    detect_near_vertical_walls: true

  # ⚡ AGGRESSIVE POST-PROCESSING
  post_processing:
    enabled: true
    fill_building_gaps: true
    max_gap_distance: 3.0 # ⬆️ Increased from 2.0 - fill larger gaps
    min_gap_points: 2 # ⬇️ Reduced from 3 - fill smaller gaps
    gap_classification_method: "nearest_neighbor"
    morphological_closing: true
    kernel_size: 2.0 # ⬆️ Increased from 1.5 - more aggressive closing
    iterations: 3 # ⬆️ Increased from 2
    smooth_boundaries: true
    smoothing_radius: 2.0 # ⬆️ Increased from 1.5
    preserve_corners: true
    min_corner_angle: 50.0 # ⬇️ Lowered from 60.0 - preserve more corners

# ============================================================================
# FEATURES - Optimized for Building Detection
# ============================================================================
features:
  mode: "asprs_classes"
  include_extra: true

  k_neighbors: 50
  search_radius: 1.5

  use_gpu: false
  use_gpu_chunked: false

  neighbor_query_batch_size: 1_500_000
  feature_batch_size: 1_500_000

  compute_normals: true
  compute_curvature: true
  compute_height: true
  compute_geometric: true

  compute_planarity: true
  compute_verticality: true
  compute_linearity: true
  compute_sphericity: true
  compute_eigenfeatures: true

  height_method: "hybrid"
  use_rge_alti_for_height: true
  dtm_interpolation: "bilinear"
  compute_height_above_ground: true
  compute_height_local: true
  compute_z_from_dtm: true

  use_rgb: true
  use_nir: true
  use_infrared: true
  compute_ndvi: true

  compute_architectural: false
  architectural_styles: false
  compute_boundaries: false
  compute_multiscale: false

  enable_caching: true
  cache_max_size: 50
  enable_auto_tuning: false
  validate_features: true
  handle_nan_values: true

# ============================================================================
# ⚡ 3D BUILDING EXTRUSION (NEW - v5.5)
# ============================================================================
building_extrusion_3d:
  enabled: true # ✅ ENABLE 3D EXTRUSION for balconies, overhangs

  floor_height: 3.0 # Standard French floor height
  min_building_height: 0.8 # ⬇️ Lowered from 2.0 - capture low buildings
  max_building_height: 100.0

  # Detection features
  detect_setbacks: true # Capture tiered buildings
  detect_overhangs: true # Capture balconies, eaves

  # Buffers (key for capturing missed points)
  vertical_buffer: 0.8 # ⬆️ Increased from 0.5 - more vertical tolerance
  horizontal_buffer_ground: 1.2 # ⬆️ Increased from 0.8 - capture ground floor edges
  horizontal_buffer_upper: 2.0 # ⬆️ Increased from 1.2 - capture large balconies

  # Segmentation
  enable_floor_segmentation: true # Analyze by floor

  # Classification
  apply_to_ground_truth: true # Apply to BD TOPO polygons
  override_2d_classification: true # 3D takes priority over 2D

# ============================================================================
# VARIABLE OBJECT FILTERING
# ============================================================================
variable_object_filtering:
  enabled: true
  filter_vehicles: true
  vehicle_height_range: [0.8, 4.0]
  filter_urban_furniture: true
  furniture_height_range: [0.5, 4.0]
  furniture_max_cluster_size: 50
  filter_walls: false
  wall_height_range: [0.5, 2.5]
  wall_min_verticality: 0.8
  reclassify_to: 1
  create_vehicle_class: true
  vehicle_class_code: 18
  verbose: true

  # ⚡ AGGRESSIVE BUILDING FUSION
  building_fusion:
    enabled: true
    source_priority:
      - "bd_topo"
      - "cadastre"
      - "osm"
    min_quality_score: 0.40 # ⬇️ Lowered from 0.50 - accept more sources
    quality_difference_threshold: 0.15 # ⬆️ Increased from 0.10
    fusion_mode: "best"
    enable_multi_source_fusion: true
    enable_translation: true
    max_translation: 15.0 # ⬆️ Increased from 12.0 - more flexible alignment
    enable_scaling: true
    max_scale_factor: 3.0 # ⬆️ Increased from 2.5
    enable_rotation: true
    max_rotation: 50.0 # ⬆️ Increased from 45.0
    enable_buffering: true
    adaptive_buffer_range: [1.0, 3.0] # ⬆️ Increased from [0.8, 2.0]
    min_points_per_building: 8 # ⬇️ Reduced from 12 - smaller buildings ok
    wall_detection_threshold: 0.55 # ⬇️ Lowered from 0.60
    overlap_threshold: 0.25 # ⬇️ Lowered from 0.28 - more permissive
    merge_nearby_buildings: true
    merge_distance_threshold: 2.5 # ⬆️ Increased from 2.0

  building_clustering:
    enabled: true
    use_centroid_attraction: true
    attraction_radius: 7.0 # ⬆️ Increased from 6.0
    min_points_per_building: 5 # ⬇️ Reduced from 8
    adjust_polygons: false
    polygon_buffer: 0.0
    wall_buffer: 0.0
    detect_near_vertical_walls: true

  # ⚡ VERY AGGRESSIVE ADAPTIVE BUILDING CLASSIFICATION
  adaptive_building_classification:
    enabled: true
    signature:
      min_height: 0.8 # ⬇️ Lowered from 1.2 - capture low buildings/annexes
      typical_height_range: [1.5, 50.0]
      wall_verticality_min: 0.55 # ⬇️ Lowered from 0.65 - rough walls ok
      wall_planarity_max: 0.7 # ⬆️ Increased from 0.6 - more tolerance
      roof_planarity_min: 0.68 # ⬇️ Lowered from 0.75 - rough roofs ok
      roof_curvature_max: 0.12 # ⬆️ Increased from 0.08 - curved roofs ok
      ndvi_max: 0.30 # ⬆️ Increased from 0.25 - some vegetation on buildings ok
      max_isolation_distance: 8.0 # ⬆️ Increased from 6.0
    fuzzy_boundary_inner: 0.0
    fuzzy_boundary_outer: 8.0 # ⬆️ Increased from 6.0 - wider fuzzy zone
    fuzzy_decay_function: "gaussian"
    enable_adaptive_expansion: true
    max_expansion_distance: 10.0 # ⬆️ Increased from 7.0 - expand further
    expansion_confidence_threshold: 0.35 # ⬇️ Lowered from 0.45 - more permissive
    enable_intelligent_rejection: true
    rejection_confidence_threshold: 0.25 # ⬇️ Lowered from 0.30 - reject less
    enable_spatial_clustering: true
    spatial_radius: 3.0 # ⬆️ Increased from 2.5
    min_neighbor_ratio: 0.20 # ⬇️ Lowered from 0.25 - more isolated points ok
    min_classification_confidence: 0.30 # ⬇️ Lowered from 0.35 - lower threshold
    feature_weights:
      height: 0.20 # ⬇️ Reduced from 0.25 - less height-dependent
      geometry: 0.35 # ⬆️ Increased from 0.30 - more geometry-driven
      spectral: 0.12 # ⬇️ Reduced from 0.15 - less spectral-dependent
      spatial: 0.25 # ⬆️ Increased from 0.20 - more spatial coherence
      ground_truth: 0.08 # ⬇️ Reduced from 0.15 - less GT-dependent

  # ⚡ AGGRESSIVE PLANE DETECTION
  plane_detection:
    enabled: true
    horizontal_angle_max: 18.0 # ⬆️ Increased from 15.0 - more tolerance
    horizontal_planarity_min: 0.60 # ⬇️ Lowered from 0.68 - rough surfaces ok
    vertical_angle_min: 65.0 # ⬇️ Lowered from 70.0 - less strict verticality
    vertical_planarity_min: 0.50 # ⬇️ Lowered from 0.58 - rough walls ok
    inclined_angle_min: 18.0 # ⬆️ Increased from 15.0
    inclined_angle_max: 65.0 # ⬇️ Lowered from 70.0
    inclined_planarity_min: 0.55 # ⬇️ Lowered from 0.62 - rough inclined surfaces ok
    min_points_per_plane: 25 # ⬇️ Reduced from 35 - smaller planes ok
    max_plane_distance: 0.30 # ⬆️ Increased from 0.20 - more tolerance
    use_spatial_coherence: true
    classify_roof_types: true
    detect_architectural_elements: false

# ============================================================================
# DATA SOURCES
# ============================================================================
data_sources:
  bd_topo:
    enabled: true
    features:
      buildings: true
      roads: true
      railways: true
      vegetation: false
    wfs_url: "https://data.geopf.fr/wfs"
    max_features: 10000
    timeout: 30
    cache_enabled: true
    cache_dir: null
    use_global_cache: false
    use_gpu: false
    road_buffer: 2.5
    building_priority: 1
    road_priority: 2
    water_priority: 3
    vegetation_priority: 4

  bd_topo_bridges: true
  bd_topo_power_lines: true
  bd_topo_sports: true
  bd_topo_cemeteries: true
  bd_topo_parking: false

  cadastre:
    enabled: true
    wfs_url: "https://data.geopf.fr/wfs"
    typename: "CADASTRALPARCELS.PARCELLAIRE_EXPRESS:parcelle"
    use_as_building_proxy: true
    cache_dir: null

  cadastre_enabled: true
  cadastre_cache_dir: null

  osm:
    enabled: true
    overpass_url: "https://overpass-api.de/api/interpreter"
    timeout: 180
    building_tags:
      - "building=yes"
      - "building=house"
      - "building=apartments"
      - "building=residential"
      - "building=commercial"
      - "building=retail"
      - "building=industrial"
      - "building=warehouse"
      - "building=office"
      - "building=school"
      - "building=hospital"
    min_building_area: 6.0 # ⬇️ Reduced from 8.0 - capture smaller buildings
    max_building_area: 15000.0
    cache_enabled: true
    cache_dir: null
    cache_ttl_days: 30

  # RGE ALTI - Memory-Safe DTM
  rge_alti:
    enabled: true
    use_wcs: true
    use_local: false
    wcs_url: "https://wxs.ign.fr/altimetrie/geoportail/r/wcs"
    coverage_id: "ELEVATION.ELEVATIONGRIDCOVERAGE.HIGHRES"
    api_key: "pratique"
    resolution: 1.0
    local_dtm_dir: null
    cache_enabled: true
    cache_dir: null
    cache_ttl_days: 90

    augment_ground_points: true
    augmentation_spacing: 1.0
    augmentation_areas:
      - "gaps"
      - "vegetation"

    compute_height_from_dtm: true
    dtm_height_priority: "high"

  bd_foret_enabled: false
  rpg_enabled: false
  orthophoto_rgb: true
  orthophoto_nir: true
  orthophoto_cache_dir: null

# ============================================================================
# GROUND TRUTH
# ============================================================================
ground_truth:
  enabled: true
  method: "strtree"
  chunk_size: 3_000_000
  cache_dir: null
  cache_ttl_days: 30
  cache_compression: true
  preclassify: true
  show_progress: true
  use_gpu: false

  adaptive_mode: true
  fuzzy_boundary_enabled: true
  fuzzy_boundary_inner: 0.0
  fuzzy_boundary_outer: 3.5 # ⬆️ Increased from 2.5 - wider fuzzy zone
  fuzzy_decay_function: "gaussian"
  adaptive_expansion_enabled: true
  max_expansion_distance: 5.0 # ⬆️ Increased from 3.5
  expansion_confidence_threshold: 0.55 # ⬇️ Lowered from 0.65
  intelligent_rejection_enabled: true
  rejection_confidence_threshold: 0.35 # ⬇️ Lowered from 0.45
  reject_vegetation_in_polygons: true
  reject_outliers_in_polygons: true

  # Memory-Safe DTM Augmentation
  rge_alti:
    enabled: true
    augment_ground: true
    augmentation_strategy: "intelligent"
    augmentation_spacing: 1.0
    min_spacing_to_existing: 1.0

    augmentation_priority:
      vegetation: true
      gaps: true
      sparse_areas: true
      buildings: false
      roads: false
      all: false

    max_height_difference: 3.0
    validate_against_neighbors: true
    synthetic_ground_class: 2
    mark_as_synthetic: true

  bd_topo:
    enabled: true
    classification_mapping:
      buildings: 6
      roads: 11
      railways: 10
      bridges: 17
      water: 9
      parking: 40
      sports: 41
      cemeteries: 42
      vegetation_low: 3
      vegetation_medium: 4
      vegetation_high: 5
      power_lines: 14
    road_buffer: 3.0
    railway_buffer: 2.5
    power_line_buffer: 6.0
    building_buffer: 1.5 # ⬆️ Increased from 1.2 - wider building capture
    water_buffer: 1.5
    road_width_fallback: 5.0
    railway_width_fallback: 4.0
    road_min_width: 1.5
    road_max_width: 60.0

  cadastre:
    enabled: true
    min_parcel_area: 6.0 # ⬇️ Reduced from 8.0
    min_parcel_points: 10 # ⬇️ Reduced from 15
    group_by_parcel: true
    export_parcel_stats: true

  integration:
    method: "priority_based"
    priority:
      bd_topo: 1
      cadastre: 2
      osm: 3
      geometric_rules: 4 # ⬆️ Promoted from 5
      ndvi_rules: 5
    confidence_threshold: 0.55 # ⬇️ Lowered from 0.65

  quality_control:
    enabled: true
    validate_geometries: true
    check_coverage: true
    min_coverage_ratio: 0.12 # ⬇️ Lowered from 0.15 - accept sparse coverage

  parallel_fetch: true
  max_parallel_requests: 8

# ============================================================================
# OUTPUT CONFIGURATION
# ============================================================================
output:
  format: "laz"
  save_enriched: true
  save_patches: false
  save_metadata: true
  save_stats: true
  compression: null
  validate_output: true
  save_fusion_report: true
  save_quality_scores: true
  save_adapted_polygons: true
  save_dtm_augmentation_report: true
  save_dtm_grid: false
  save_height_comparison: true
  include_dtm_height: true
  include_local_height: true
  include_dtm_elevation: true
  include_synthetic_flag: true
  save_adaptive_report: true
  include_confidence_scores: true
  extra_dims:
    - name: "BuildingConfidence"
      type: "float32"
      description: "Building classification confidence (0-1)"
    - name: "IsWall"
      type: "uint8"
      description: "1 if point is likely a wall"
    - name: "IsRoof"
      type: "uint8"
      description: "1 if point is likely a roof"
    - name: "DistanceToPolygon"
      type: "float32"
      description: "Signed distance to nearest building polygon (m)"
    - name: "AdaptiveExpanded"
      type: "uint8"
      description: "1 if classified via adaptive expansion"
    - name: "IntelligentRejected"
      type: "uint8"
      description: "1 if rejected despite being in polygon"
    - name: "Extrusion3D"
      type: "uint8"
      description: "1 if classified via 3D extrusion"
  export_parcel_stats: true
  parcel_stats_format: "csv,geojson,html"

# ============================================================================
# LOGGING
# ============================================================================
logging:
  level: INFO
  show_progress: true
  detailed_timing: true
  enable_performance_metrics: true
  enable_profiling: false

# ============================================================================
# PREPROCESSING & STITCHING
# ============================================================================
preprocess:
  enabled: false
  remove_duplicates: true
  remove_outliers: true
  outlier_std_multiplier: 3.0

stitching:
  enabled: false
  buffer_size: 10.0
  blend_overlap: true

# ============================================================================
# OPTIMIZATIONS
# ============================================================================
optimizations:
  enable_caching: true
  cache_max_size_mb: 100
  enable_parallel_processing: false
  max_workers: 1
  enable_auto_tuning: false
  adaptive_parameters: true
  enable_performance_metrics: true
  enable_profiling: false

validation:
  strict_validation: true
  check_gpu_availability: false
  check_memory_requirements: true

hardware:
  auto_detect: true
  prefer_gpu: false
  fallback_cpu: true

# ============================================================================
# HYDRA CONFIGURATION
# ============================================================================
hydra:
  run:
    dir: outputs/asprs_aggressive_buildings_v5.5/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    name: asprs_aggressive_buildings_v5.5
