# ========================================================================
# Versailles Dataset - LOD2 Building Classification (V5.1)
# ========================================================================
# Purpose: Process Versailles LiDAR data with LOD2 building classification
#
# LOD2 Classes (15):
# - Structural: wall
# - Roofs: flat, gable, hip
# - Details: chimney, dormer, balcony, overhang, foundation
# - Context: ground, vegetation (low/high), water, vehicle, other
#
# Usage:
#   ign-lidar-hd process --config-file examples/config_versailles_lod2_v5.0.yaml
#
# Version: 5.1.0
# Date: October 18, 2025
# ========================================================================

# Inherit from LOD2 preset (Hydra defaults system)
defaults:
  - presets/lod2
  - _self_

# Custom paths for Versailles dataset
input_dir: /mnt/c/Users/Simon/ign/versailles
output_dir: /mnt/c/Users/Simon/ign/versailles_processed_lod2

# Ground truth caching
ground_truth:
  cache_dir: /mnt/c/Users/Simon/ign/cache/ground_truth

# Hydra output directory
hydra:
  run:
    dir: outputs/versailles_lod2/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    name: versailles_lod2
# ========================================================================
# All other settings inherited from lod2 preset:
# - GPU acceleration enabled
# - LOD2 classification (15 classes)
# - Full geometric + spectral features
# - Optimized ground truth classification
# - Geometric reclassification refinement
# - Statistical + radius outlier removal
# - Tile stitching with 15m buffer
# - Output: LAZ + NPZ patches for training
# ========================================================================
