# ========================================================================
# LOD2 Simplified Features Configuration - Essential Training
# ========================================================================
# Purpose: Generate ML training patches with essential 11 features for LOD2
#
# Feature Set (11 features total):
# - Coordinates: xyz (3)
# - Geometric: normal_z, planarity, linearity (3)
# - Building: height_above_ground, verticality (2)
# - Spectral: red, green, blue, ndvi (4)
#
# Benefits:
# - Faster training (fewer features)
# - Better generalization (less overfitting)
# - Lower memory usage
# - Suitable for basic building classification
#
# Use Case: LOD2 building detection and basic roof/wall classification
# ========================================================================

processor:
  lod_level: LOD2
  architecture: pointnet++
  use_gpu: true
  num_workers: 4
  patch_size: 100.0 # Smaller patches for LOD2
  patch_overlap: 0.1
  num_points: 16384 # 16k points sufficient for LOD2
  augment: true
  num_augmentations: 3
  pin_memory: true

features:
  mode: lod2 # LOD2 simplified feature set
  k_neighbors: 20 # Standard k for LOD2
  search_radius: 1.5 # Radius search eliminates scan line artifacts
  include_extra: false # No extra features for LOD2

  # Spectral features
  use_rgb: true
  use_infrared: false # NIR not critical for LOD2
  compute_ndvi: true # Vegetation index for classification

  # Sampling and normalization
  sampling_method: random # Random sampling OK for LOD2
  normalize_xyz: true
  normalize_features: true

  # GPU optimization
  gpu_batch_size: 1000000
  use_gpu_chunked: true

preprocess:
  enabled: true
  sor_k: 12
  sor_std: 2.0
  ror_radius: 1.0
  ror_neighbors: 4
  voxel_enabled: false

stitching:
  enabled: false # Not critical for LOD2
  buffer_size: 10.0
  auto_detect_neighbors: false
  auto_download_neighbors: false
  cache_enabled: false

output:
  format: npz
  processing_mode: patches_only
  save_stats: true
  save_metadata: true
  compression: null

input_dir: /mnt/c/Users/Simon/ign/enriched_tiles
output_dir: /mnt/c/Users/Simon/ign/patches_lod2_simplified
