# ============================================================================
# IGN LiDAR HD - Multi-Source Building Fusion Configuration
# ============================================================================
# Purpose: Advanced building detection with multi-source comparison and fusion
#
# Features:
# - Compare building footprints from BD TOPO, Cadastre, and OpenStreetMap
# - Intelligent quality scoring based on point cloud fit
# - Adaptive polygon adjustment (translation, scaling, rotation, buffering)
# - Conflict resolution and merging of nearby buildings
# - Best-source selection or weighted fusion strategies
#
# New Enhancements (V5.1):
# - Multi-source polygon comparison with quality metrics
# - Intelligent fusion strategies (best, weighted_merge, consensus)
# - Adaptive polygon transformation to match point cloud reality
# - Translation: Move polygons to actual point cloud centroids
# - Scaling: Expand/contract polygons based on point density
# - Rotation: Align with principal axes of point distribution
# - Buffering: Adaptive buffer distances (0.3-1.0m) for wall capture
# - Conflict resolution: Merge overlapping buildings intelligently
#
# Use Cases:
# - Urban areas with heterogeneous data quality
# - Historical areas where BD TOPO may be outdated
# - Detailed building reconstruction requiring best footprints
# - Quality assessment of different data sources
# - Data fusion for authoritative building database
#
# Usage:
#   ign-lidar-hd process \
#     -c examples/config_building_fusion.yaml \
#     input_dir="/path/to/tiles" \
#     output_dir="/path/to/output"
#
# Package Version: 3.1.0
# Config Version: 5.1.0
# Date: October 19, 2025
# Hardware: RTX 4080 16GB (or similar)
# ============================================================================

# Inherit from LOD3 preset for detailed building analysis
defaults:
  - presets/lod3
  - _self_

# Configuration metadata
config_version: "5.1.0"
config_name: "building_fusion"
config_description: "Multi-source building fusion with adaptive polygon adjustment"

# ============================================================================
# PROCESSOR - Building Fusion Configuration
# ============================================================================
processor:
  # Classification scheme
  lod_level: "LOD3" # Maximum detail for building analysis
  processing_mode: "enriched_only" # LAZ output

  # GPU optimization
  use_gpu: true
  gpu_batch_size: 20_000_000
  gpu_memory_target: 0.85
  gpu_streams: 4

  # ============================================================================
  # BUILDING FUSION (V5.1 Enhancement) ⭐ NEW
  # ============================================================================
  building_fusion:
    enabled: true # Enable multi-source building fusion

    # ─────────────────────────────────────────────────────────────────────
    # SOURCE PRIORITIES
    # ─────────────────────────────────────────────────────────────────────
    # Priority order (highest to lowest)
    source_priority:
      - "bd_topo" # IGN BD TOPO (official, most accurate)
      - "cadastre" # Cadastre (legal boundaries)
      - "osm" # OpenStreetMap (community data)

    # ─────────────────────────────────────────────────────────────────────
    # QUALITY THRESHOLDS
    # ─────────────────────────────────────────────────────────────────────
    min_quality_score: 0.5 # Minimum quality to accept polygon (0-1)
    quality_difference_threshold: 0.15 # Min difference to switch sources

    # ─────────────────────────────────────────────────────────────────────
    # FUSION STRATEGY
    # ─────────────────────────────────────────────────────────────────────
    # Options:
    #   "best": Select polygon with highest quality score
    #   "weighted_merge": Union of polygons weighted by quality
    #   "consensus": Intersection of good polygons (conservative)
    fusion_mode: "best" # Recommended for most cases
    enable_multi_source_fusion: true # Allow combining multiple sources

    # ─────────────────────────────────────────────────────────────────────
    # ADAPTIVE POLYGON ADJUSTMENT
    # ─────────────────────────────────────────────────────────────────────
    # Translation: Move polygon to match point cloud centroid
    enable_translation: true
    max_translation: 5.0 # Maximum movement (meters)

    # Scaling: Resize polygon to match point extent
    enable_scaling: true
    max_scale_factor: 1.5 # 1.5x max expansion/contraction

    # Rotation: Align with principal axes (expensive!)
    enable_rotation: false # Disabled by default (CPU intensive)
    max_rotation: 15.0 # Maximum rotation angle (degrees)

    # Buffering: Adaptive buffer for wall capture
    enable_buffering: true
    adaptive_buffer_range: [0.3, 1.0] # Min/max buffer distances (meters)
    # Buffer adapts based on wall detection (high verticality → larger buffer)

    # ─────────────────────────────────────────────────────────────────────
    # POINT CLOUD ANALYSIS
    # ─────────────────────────────────────────────────────────────────────
    min_points_per_building: 20 # Minimum points to process building
    wall_detection_threshold: 0.7 # Verticality threshold for walls

    # ─────────────────────────────────────────────────────────────────────
    # CONFLICT RESOLUTION
    # ─────────────────────────────────────────────────────────────────────
    overlap_threshold: 0.3 # IoU threshold for overlap detection (0-1)
    merge_nearby_buildings: true # Merge overlapping buildings
    merge_distance_threshold: 2.0 # Max distance for merging (meters)

  # ============================================================================
  # BUILDING CLUSTERING (Standard Parameters)
  # ============================================================================
  building_clustering:
    enabled: true # Works with fused polygons
    use_centroid_attraction: true
    attraction_radius: 5.0
    min_points_per_building: 10
    adjust_polygons: false # Disabled when fusion is enabled
    polygon_buffer: 0.0 # Fusion handles buffering
    wall_buffer: 0.0
    detect_near_vertical_walls: true

  # ============================================================================
  # PLANE DETECTION (Optional for Building Analysis)
  # ============================================================================
  plane_detection:
    enabled: true
    horizontal_angle_max: 8.0
    vertical_angle_min: 78.0
    inclined_angle_min: 12.0
    inclined_angle_max: 75.0
    min_points_per_plane: 30
    classify_roof_types: true
    detect_architectural_elements: true

# ============================================================================
# FEATURES - Enhanced for Building Analysis
# ============================================================================
features:
  mode: "lod3"
  include_extra: true

  # High-resolution parameters for accurate polygon fitting
  k_neighbors: 30 # More neighbors for precise normals
  search_radius: 1.5

  # Essential features for building fusion
  compute_normals: true # CRITICAL for wall detection
  compute_curvature: true
  compute_height: true
  compute_geometric: true # Planarity, verticality

  # Architectural analysis
  compute_architectural: true
  architectural_styles: true

  # Boundary detection
  compute_boundaries: true

  # GPU settings
  use_gpu_chunked: true
  gpu_batch_size: 2_000_000

  # Spectral features (optional)
  use_rgb: true
  use_nir: false
  compute_ndvi: false

# ============================================================================
# DATA SOURCES - Multi-Source Configuration
# ============================================================================
data_sources:
  # ─────────────────────────────────────────────────────────────────────
  # BD TOPO (PRIMARY SOURCE)
  # ─────────────────────────────────────────────────────────────────────
  bd_topo:
    enabled: true
    features:
      buildings: true # REQUIRED for fusion
      roads: true
      water: true
      vegetation: true

    # WFS endpoint
    wfs_url: "https://wxs.ign.fr/essentiels/geoportail/wfs"
    typename: "BDTOPO_V3:batiment"

  # ─────────────────────────────────────────────────────────────────────
  # CADASTRE (SECONDARY SOURCE)
  # ─────────────────────────────────────────────────────────────────────
  cadastre:
    enabled: true
    wfs_url: "https://wxs.ign.fr/parcellaire/geoportail/wfs"
    typename: "CADASTRALPARCELS.PARCELLAIRE_EXPRESS:parcelle"

    # Use parcels as building proxies where buildings unavailable
    use_as_building_proxy: true

  # ─────────────────────────────────────────────────────────────────────
  # OPENSTREETMAP (TERTIARY SOURCE) ⭐ NEW
  # ─────────────────────────────────────────────────────────────────────
  osm:
    enabled: true # Enable OpenStreetMap buildings

    # Overpass API endpoint
    overpass_url: "https://overpass-api.de/api/interpreter"

    # Query parameters
    timeout: 180 # seconds

    # Building filters
    building_tags:
      - "building=yes"
      - "building=house"
      - "building=residential"
      - "building=apartments"
      - "building=commercial"
      - "building=industrial"
      - "building=retail"
      - "building=office"

    # Quality filters
    min_building_area: 10.0 # m² (exclude small artifacts)
    max_building_area: 10000.0 # m² (exclude invalid geometries)

    # Cache settings
    cache_enabled: true
    cache_ttl_days: 30

  # Additional data sources
  bd_topo_bridges: true
  bd_topo_power_lines: false

  # Orthophotos (optional)
  orthophoto_rgb: false
  orthophoto_nir: false

# ============================================================================
# GROUND TRUTH - Optional Classification
# ============================================================================
ground_truth:
  enabled: false # Fusion is geometry-based
  method: "gpu_chunked"
  chunk_size: 20_000_000

# ============================================================================
# OUTPUT CONFIGURATION
# ============================================================================
output:
  format: "laz" # LAZ output
  save_enriched: true # Save enriched point cloud
  save_metadata: true # Save fusion metadata
  save_stats: true # Save detailed statistics

  # Additional outputs for fusion analysis
  save_fusion_report: true # Save source comparison report
  save_quality_scores: true # Save per-building quality scores
  save_adapted_polygons: true # Save final adapted polygons (GeoJSON/Shapefile)

  parcel_stats_format: "csv,geojson" # Building statistics with geometries

# ============================================================================
# PREPROCESSING (Optional)
# ============================================================================
preprocess:
  enabled: false
  remove_outliers: true
  outlier_std_multiplier: 3.0

# ============================================================================
# TILE STITCHING (Optional)
# ============================================================================
stitching:
  enabled: false
  buffer_size: 15.0
  blend_overlap: true

# ============================================================================
# HYDRA CONFIGURATION
# ============================================================================
hydra:
  run:
    dir: outputs/building_fusion/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    name: building_fusion
# ============================================================================
# EXPECTED RESULTS
# ============================================================================
# Source Comparison (typical urban tile):
#   - BD TOPO buildings: 150-300 buildings
#   - Cadastre parcels: 200-400 parcels
#   - OSM buildings: 100-250 buildings
#   - Fused buildings: 180-320 buildings (best of all sources)
#
# Quality Scores (average):
#   - BD TOPO: 0.75-0.85 (most accurate)
#   - Cadastre: 0.60-0.70 (parcels ≠ buildings)
#   - OSM: 0.50-0.75 (variable quality)
#
# Polygon Adaptations (per 100 buildings):
#   - Translated: 60-80 buildings (move to point cloud centroid)
#   - Scaled: 40-60 buildings (adjust to point extent)
#   - Rotated: 10-20 buildings (if enabled)
#   - Buffered: 70-90 buildings (adaptive wall capture)
#
# Fusion Strategy Results:
#   - "best": Uses BD TOPO 70%, Cadastre 20%, OSM 10%
#   - "weighted_merge": Combines multiple sources ~40% of time
#   - "consensus": Conservative, smaller polygons
#
# Performance (RTX 4080, 18.6M point tile):
#   - Source download: ~2-3 minutes (first time, then cached)
#   - Polygon matching: ~30 seconds
#   - Quality scoring: ~1-2 minutes
#   - Polygon adaptation: ~1-2 minutes
#   - Conflict resolution: ~30 seconds
#   - Total processing: ~8-12 minutes per tile
#
# Quality Improvements:
#   - Coverage: +10-25% more building points captured
#   - Accuracy: +5-15% better centroid alignment
#   - Completeness: +15-30% more wall points included
#   - Consistency: Uniform quality across heterogeneous data
# ============================================================================
