# ============================================================================
# IGN LiDAR HD - ASPRS CPU V3 Memory-Safe Configuration
# ============================================================================
# Purpose: V3 aggressive classification with MEMORY SAFETY for 32GB systems
#
# KEY CHANGES for Memory Safety:
# 1. Reduced DTM augmentation density (2.0m spacing instead of 0.5m)
# 2. Intelligent augmentation strategy (not "all")
# 3. Smaller chunk sizes (3M instead of 5M)
# 4. DTM augmentation in chunks, not all at once
# 5. Immediate memory cleanup after augmentation
#
# Memory Profile:
# - 21M points × 150 bytes = ~3.2GB (original points)
# - 250K DTM points × 150 bytes = ~38MB (augmented, 16x less than v3)
# - Feature computation: ~2GB working memory
# - Total peak: ~6-8GB (safe for 32GB system)
#
# Compared to V3 original:
# - DTM points: 4M → 250K (16x reduction)
# - Peak memory: ~25GB → ~8GB (3x reduction)
# - Processing time: +10% (chunked processing overhead)
#
# Usage:
#   ign-lidar-hd process \
#     -c examples/config_asprs_bdtopo_cadastre_cpu_v3_memory_safe.yaml \
#     input_dir="/path/to/tiles" \
#     output_dir="/path/to/output"
# ============================================================================

defaults:
  - base/processor
  - base/features
  - base/data_sources
  - base/output
  - base/monitoring
  - _self_

# Configuration metadata
config_version: "5.3.2"
config_name: "asprs_bdtopo_cadastre_cpu_v3_memory_safe"
config_description: "V3 Aggressive Classification with Memory Safety (32GB systems)"

# ============================================================================
# PROCESSOR - Memory-Safe Settings
# ============================================================================
processor:
  lod_level: "ASPRS"
  processing_mode: "enriched_only"

  use_gpu: false
  num_workers: 1

  # REDUCED chunk sizes for memory safety
  chunk_size: 3_000_000 # ⬇️ Reduced from 5M for safer memory usage
  ground_truth_method: "strtree"
  ground_truth_chunk_size: 3_000_000 # ⬇️ Reduced from 5M

  use_strategy_pattern: true

  use_cuda_streams: false
  enable_memory_pooling: false
  enable_pipeline_optimization: false
  enable_async_transfers: false
  adaptive_chunk_sizing: true
  auto_optimize: false

  skip_existing: false
  output_format: "laz"
  use_stitching: false

  patch_size: 50.0
  patch_overlap: 0.1
  num_points: 24576
  architecture: "direct"
  augment: false
  num_augmentations: 0

  # Aggressive classification settings (same as V3)
  reclassification:
    enabled: true
    acceleration_mode: "cpu"
    chunk_size: 1_500_000 # ⬇️ Reduced from 2M for memory safety
    min_confidence: 0.45
    use_geometric_rules: true
    use_ndvi_classification: true
    show_progress: true
    ndvi_vegetation_threshold: 0.3
    ndvi_road_threshold: 0.15
    use_spectral_rules: true
    nir_vegetation_threshold: 0.35
    nir_building_threshold: 0.25
    use_clustering: true
    spatial_cluster_eps: 0.6
    min_cluster_size: 3
    building_buffer_distance: 6.0
    verticality_threshold: 0.50

  building_clustering:
    enabled: true
    use_centroid_attraction: true
    attraction_radius: 5.0
    min_points_per_building: 10
    adjust_polygons: true
    polygon_buffer: 0.5
    wall_buffer: 0.3
    detect_near_vertical_walls: true

  post_processing:
    enabled: true
    fill_building_gaps: true
    max_gap_distance: 2.0
    min_gap_points: 3
    gap_classification_method: "nearest_neighbor"
    morphological_closing: true
    kernel_size: 1.5
    iterations: 2
    smooth_boundaries: true
    smoothing_radius: 1.5
    preserve_corners: true
    min_corner_angle: 60.0

# ============================================================================
# FEATURES - Memory-Optimized Settings
# ============================================================================
features:
  mode: "asprs_classes"
  include_extra: true

  k_neighbors: 50
  search_radius: 1.5

  use_gpu: false
  use_gpu_chunked: false

  # Smaller batches for memory safety
  neighbor_query_batch_size: 1_500_000 # ⬇️ Reduced from 2M
  feature_batch_size: 1_500_000 # ⬇️ Reduced from 2M

  compute_normals: true
  compute_curvature: true
  compute_height: true
  compute_geometric: true

  compute_planarity: true
  compute_verticality: true
  compute_linearity: true
  compute_sphericity: true
  compute_eigenfeatures: true

  height_method: "hybrid"
  use_rge_alti_for_height: true
  dtm_interpolation: "bilinear"
  compute_height_above_ground: true
  compute_height_local: true
  compute_z_from_dtm: true

  use_rgb: true
  use_nir: true
  use_infrared: true
  compute_ndvi: true

  compute_architectural: false
  architectural_styles: false
  compute_boundaries: false
  compute_multiscale: false

  enable_caching: true
  cache_max_size: 50
  enable_auto_tuning: false
  validate_features: true
  handle_nan_values: true

# ============================================================================
# VARIABLE OBJECT FILTERING (Same as V3)
# ============================================================================
variable_object_filtering:
  enabled: true
  filter_vehicles: true
  vehicle_height_range: [0.8, 4.0]
  filter_urban_furniture: true
  furniture_height_range: [0.5, 4.0]
  furniture_max_cluster_size: 50
  filter_walls: false
  wall_height_range: [0.5, 2.5]
  wall_min_verticality: 0.8
  reclassify_to: 1
  create_vehicle_class: true
  vehicle_class_code: 18
  verbose: true

  building_fusion:
    enabled: true
    source_priority:
      - "bd_topo"
      - "cadastre"
      - "osm"
    min_quality_score: 0.50
    quality_difference_threshold: 0.10
    fusion_mode: "best"
    enable_multi_source_fusion: true
    enable_translation: true
    max_translation: 12.0
    enable_scaling: true
    max_scale_factor: 2.5
    enable_rotation: true
    max_rotation: 45.0
    enable_buffering: true
    adaptive_buffer_range: [0.8, 2.0]
    min_points_per_building: 12
    wall_detection_threshold: 0.60
    overlap_threshold: 0.28
    merge_nearby_buildings: true
    merge_distance_threshold: 2.0

  building_clustering:
    enabled: true
    use_centroid_attraction: true
    attraction_radius: 6.0
    min_points_per_building: 8
    adjust_polygons: false
    polygon_buffer: 0.0
    wall_buffer: 0.0
    detect_near_vertical_walls: true

  # V3 Aggressive adaptive classification (unchanged)
  adaptive_building_classification:
    enabled: true
    signature:
      min_height: 1.2
      typical_height_range: [2.0, 60.0]
      wall_verticality_min: 0.50
      wall_planarity_max: 0.65
      roof_planarity_min: 0.55
      roof_curvature_max: 0.25
      roof_normal_z_range: [0.10, 1.0]
      ndvi_max: 0.28
      ndvi_wall_max: 0.22
      min_cluster_size: 3
      max_isolation_distance: 6.0
    fuzzy_boundary_inner: 0.0
    fuzzy_boundary_outer: 6.0
    fuzzy_decay_function: "gaussian"
    enable_adaptive_expansion: true
    max_expansion_distance: 7.0
    expansion_confidence_threshold: 0.45
    enable_intelligent_rejection: true
    rejection_confidence_threshold: 0.30
    enable_spatial_clustering: true
    spatial_radius: 2.5
    min_neighbor_ratio: 0.25
    min_classification_confidence: 0.35
    feature_weights:
      height: 0.25
      geometry: 0.30
      spectral: 0.15
      spatial: 0.15
      ground_truth: 0.15

  plane_detection:
    enabled: true
    horizontal_angle_max: 15.0
    horizontal_planarity_min: 0.68
    vertical_angle_min: 70.0
    vertical_planarity_min: 0.58
    inclined_angle_min: 15.0
    inclined_angle_max: 70.0
    inclined_planarity_min: 0.62
    min_points_per_plane: 35
    max_plane_distance: 0.20
    use_spatial_coherence: true
    classify_roof_types: true
    detect_architectural_elements: false

# ============================================================================
# DATA SOURCES (Same as V3)
# ============================================================================
data_sources:
  bd_topo:
    enabled: true
    features:
      buildings: true
      roads: true
      water: true
      vegetation: false
    wfs_url: "https://data.geopf.fr/wfs"
    max_features: 10000
    timeout: 30
    cache_enabled: true
    cache_dir: null
    use_global_cache: false
    use_gpu: false
    road_buffer: 2.5
    building_priority: 1
    road_priority: 2
    water_priority: 3
    vegetation_priority: 4

  bd_topo_bridges: true
  bd_topo_power_lines: true
  bd_topo_sports: true
  bd_topo_cemeteries: true
  bd_topo_parking: false

  cadastre:
    enabled: true
    wfs_url: "https://data.geopf.fr/wfs"
    typename: "CADASTRALPARCELS.PARCELLAIRE_EXPRESS:parcelle"
    use_as_building_proxy: true
    cache_dir: null

  cadastre_enabled: true
  cadastre_cache_dir: null

  osm:
    enabled: true
    overpass_url: "https://overpass-api.de/api/interpreter"
    timeout: 180
    building_tags:
      - "building=yes"
      - "building=house"
      - "building=residential"
      - "building=apartments"
      - "building=commercial"
      - "building=industrial"
      - "building=retail"
      - "building=office"
      - "building=school"
      - "building=church"
      - "building=hospital"
    min_building_area: 8.0
    max_building_area: 15000.0
    cache_enabled: true
    cache_dir: null
    cache_ttl_days: 30

  # ============================================================================
  # RGE ALTI - MEMORY-SAFE DTM AUGMENTATION
  # ============================================================================
  rge_alti:
    enabled: true
    use_wcs: true
    use_local: false
    wcs_url: "https://wxs.ign.fr/altimetrie/geoportail/r/wcs"
    coverage_id: "ELEVATION.ELEVATIONGRIDCOVERAGE.HIGHRES"
    api_key: "pratique"
    resolution: 1.0
    local_dtm_dir: null
    cache_enabled: true
    cache_dir: null
    cache_ttl_days: 90

    # CRITICAL MEMORY SAFETY SETTINGS
    augment_ground_points: true
    augmentation_spacing: 1.0 # ⬆️ 0.5m → 1.0m (4x fewer points, ~1M instead of 4M)
    augmentation_areas: # ⬇️ Only augment where needed
      - "gaps" # ✓ Fill gaps in point cloud
      - "vegetation" # ✓ Help classify vegetation areas
      # NOT "all" - this creates millions of unnecessary points

    compute_height_from_dtm: true
    dtm_height_priority: "high"

  bd_foret_enabled: false
  rpg_enabled: false
  orthophoto_rgb: true
  orthophoto_nir: true
  orthophoto_cache_dir: null

# ============================================================================
# GROUND TRUTH - MEMORY-SAFE DTM AUGMENTATION
# ============================================================================
ground_truth:
  enabled: true
  method: "strtree"
  chunk_size: 3_000_000 # ⬇️ Reduced from 5M
  cache_dir: null
  cache_ttl_days: 30
  cache_compression: true
  preclassify: true
  show_progress: true
  use_gpu: false

  adaptive_mode: true
  fuzzy_boundary_enabled: true
  fuzzy_boundary_inner: 0.0
  fuzzy_boundary_outer: 2.5
  fuzzy_decay_function: "gaussian"
  adaptive_expansion_enabled: true
  max_expansion_distance: 3.5
  expansion_confidence_threshold: 0.65
  intelligent_rejection_enabled: true
  rejection_confidence_threshold: 0.45
  reject_vegetation_in_polygons: true
  reject_outliers_in_polygons: true

  # ============================================================================
  # CRITICAL: Memory-Safe DTM Augmentation
  # ============================================================================
  rge_alti:
    enabled: true
    augment_ground: true
    augmentation_strategy: "intelligent" # ⬇️ "all" → "intelligent" (only gaps)
    augmentation_spacing: 1.0 # ⬆️ 0.5m → 1.0m (4x fewer points!)
    min_spacing_to_existing: 1.0 # ⬆️ 0.5m → 1.0m (avoid clustering)

    # Only augment where truly needed
    augmentation_priority:
      vegetation: true # ✓ Help vegetation classification
      buildings: false # ✗ Buildings have enough points
      water: false # ✗ Water has enough points
      roads: false # ✗ Roads have enough points
      gaps: true # ✓ Fill real gaps only
      all: false # ✗ CRITICAL: Don't augment everywhere!

    max_height_difference: 3.0 # ⬇️ 5.0m → 3.0m (stricter validation)
    validate_against_neighbors: true # ⬆️ Enable validation for quality
    synthetic_ground_class: 2
    mark_as_synthetic: true

  bd_topo:
    enabled: true
    classification_mapping:
      buildings: 6
      roads: 11
      railways: 10
      water: 9
      low_vegetation: 3
      medium_vegetation: 4
      high_vegetation: 5
      bridges: 17
      parking: 11
      cemeteries: 2
      sports: 11
      power_lines: 14
    road_buffer: 3.0
    railway_buffer: 2.5
    power_line_buffer: 6.0
    building_buffer: 1.2
    water_buffer: 1.5
    road_width_fallback: 5.0
    railway_width_fallback: 4.0
    road_min_width: 1.5
    road_max_width: 60.0

  cadastre:
    enabled: true
    min_parcel_area: 8.0
    min_parcel_points: 15
    group_by_parcel: true
    export_parcel_stats: true

  integration:
    method: "priority_based"
    priority:
      bd_topo: 1
      cadastre: 2
      orthophoto: 4
      geometric_rules: 5
    confidence_threshold: 0.65

  quality_control:
    enabled: true
    validate_geometries: true
    check_coverage: true
    min_coverage_ratio: 0.15

  parallel_fetch: true
  max_parallel_requests: 8

# ============================================================================
# OUTPUT CONFIGURATION (Same as V3)
# ============================================================================
output:
  format: "laz"
  save_enriched: true
  save_patches: false
  save_metadata: true
  save_stats: true
  compression: null
  validate_output: true
  save_fusion_report: true
  save_quality_scores: true
  save_adapted_polygons: true
  save_dtm_augmentation_report: true
  save_dtm_grid: false
  save_height_comparison: true
  include_dtm_height: true
  include_local_height: true
  include_dtm_elevation: true
  include_synthetic_flag: true
  save_adaptive_report: true
  include_confidence_scores: true
  extra_dims:
    - name: "BuildingConfidence"
      type: "float32"
      description: "Building classification confidence (0-1)"
    - name: "IsWall"
      type: "uint8"
      description: "1 if point is likely a wall"
    - name: "IsRoof"
      type: "uint8"
      description: "1 if point is likely a roof"
    - name: "DistanceToPolygon"
      type: "float32"
      description: "Signed distance to nearest building polygon (m)"
    - name: "AdaptiveExpanded"
      type: "uint8"
      description: "1 if classified via adaptive expansion"
    - name: "IntelligentRejected"
      type: "uint8"
      description: "1 if rejected despite being in polygon"
  export_parcel_stats: true
  parcel_stats_format: "csv,geojson,html"

# ============================================================================
# LOGGING
# ============================================================================
logging:
  level: INFO
  show_progress: true
  detailed_timing: true
  enable_performance_metrics: true
  enable_profiling: false

# ============================================================================
# PREPROCESSING & STITCHING
# ============================================================================
preprocess:
  enabled: false
  remove_duplicates: true
  remove_outliers: true
  outlier_std_multiplier: 3.0

stitching:
  enabled: false
  buffer_size: 10.0
  blend_overlap: true

# ============================================================================
# OPTIMIZATIONS - Memory Safety
# ============================================================================
optimizations:
  enable_caching: true
  cache_max_size_mb: 100
  enable_parallel_processing: false
  max_workers: 1
  enable_auto_tuning: false
  adaptive_parameters: true
  enable_performance_metrics: true
  enable_profiling: false

validation:
  strict_validation: true
  check_gpu_availability: false
  check_memory_requirements: true

hardware:
  auto_detect: true
  prefer_gpu: false
  fallback_cpu: true

# ============================================================================
# HYDRA CONFIGURATION
# ============================================================================
hydra:
  run:
    dir: outputs/asprs_bdtopo_cadastre_cpu_v3_memory_safe/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    name: asprs_bdtopo_cadastre_cpu_v3_memory_safe
