# ============================================================================
# IGN LiDAR HD - Plane Detection Configuration (LOD3)
# ============================================================================
# Purpose: Comprehensive plane detection for architectural analysis
#
# Features:
# - Horizontal plane detection (flat roofs, terraces, balconies)
# - Vertical plane detection (walls, facades, parapets)
# - Inclined plane detection (pitched roofs, slopes)
# - Automatic roof type classification (flat/gable/hip/complex)
# - Architectural element detection (chimneys, dormers, balconies, parapets)
# - Building clustering with centroid attraction and wall buffers
#
# New Enhancements (V5.1):
# - Near-vertical wall detection with extended buffers (0.8m total)
# - Comprehensive plane segmentation (horizontal/vertical/inclined)
# - Roof type classification algorithm
# - Small architectural element detection
# - Integration with BD TOPO building footprints
#
# Use Cases:
# - Architectural heritage documentation
# - Building 3D reconstruction (LOD3 level)
# - Roof surface analysis for solar panel placement
# - Facade analysis and orientation studies
# - Detailed urban modeling
#
# Usage:
#   ign-lidar-hd process \
#     -c examples/config_plane_detection_lod3.yaml \
#     input_dir="/path/to/tiles" \
#     output_dir="/path/to/output"
#
# Version: 5.1.0
# Date: October 19, 2025
# Hardware: RTX 4080 16GB (or similar)
# ============================================================================

# Inherit from LOD3 preset with plane detection enhancements
defaults:
  - presets/lod3
  - _self_

# Configuration metadata
config_version: "5.1.0"
config_name: "plane_detection_lod3"
config_description: "LOD3 with comprehensive plane detection and architectural elements"

# ============================================================================
# PROCESSOR - LOD3 with Enhanced Features
# ============================================================================
processor:
  # Classification scheme
  lod_level: "LOD3" # Maximum architectural detail
  processing_mode: "enriched_only" # LAZ output only

  # GPU optimization
  use_gpu: true
  gpu_batch_size: 20_000_000 # 20M points
  gpu_memory_target: 0.85 # 85% VRAM
  gpu_streams: 4

  # ============================================================================
  # BUILDING CLUSTERING - Enhanced for Plane Detection
  # ============================================================================
  building_clustering:
    enabled: true # CRITICAL for building-level plane detection
    use_centroid_attraction: true # Resolve ambiguous point assignments
    attraction_radius: 5.0 # Maximum distance for centroid attraction (meters)
    min_points_per_building: 10 # Minimum points to form valid cluster

    # Polygon adjustment for point cloud reality
    adjust_polygons: true # Adjust BD TOPO polygons to match actual points
    polygon_buffer: 0.5 # Base buffer for polygon adjustment (meters)

    # Wall detection enhancements
    wall_buffer: 0.3 # Additional buffer for near-vertical walls (meters)
    detect_near_vertical_walls: true # Enable wall detection
    # Total effective buffer: 0.5 + 0.3 = 0.8m for wall capture

  # ============================================================================
  # PLANE DETECTION - Comprehensive Configuration
  # ============================================================================
  plane_detection:
    enabled: true # Enable all plane detection features

    # ─────────────────────────────────────────────────────────────────────
    # HORIZONTAL PLANES (Toits Plats, Terrasses, Dalles)
    # ─────────────────────────────────────────────────────────────────────
    horizontal_angle_max: 8.0 # Strict: ≤8° from horizontal
    horizontal_planarity_min: 0.80 # High planarity requirement (0-1 scale)
    # Detects: flat roofs, terraces, parking decks, balconies

    # ─────────────────────────────────────────────────────────────────────
    # VERTICAL PLANES (Murs, Façades, Pignons)
    # ─────────────────────────────────────────────────────────────────────
    vertical_angle_min: 78.0 # Strict: ≥78° from horizontal
    vertical_planarity_min: 0.70 # High planarity requirement
    # Detects: walls, facades, parapets, vertical building elements

    # ─────────────────────────────────────────────────────────────────────
    # INCLINED PLANES (Toits en Pente, Versants)
    # ─────────────────────────────────────────────────────────────────────
    inclined_angle_min: 12.0 # Wide range: 12-75° for all roof types
    inclined_angle_max: 75.0
    inclined_planarity_min: 0.75 # High planarity for roof surfaces
    # Detects: gable roofs, hip roofs, shed roofs, complex roof structures

    # ─────────────────────────────────────────────────────────────────────
    # GENERAL PARAMETERS
    # ─────────────────────────────────────────────────────────────────────
    min_points_per_plane: 30 # Lower threshold to detect small elements
    max_plane_distance: 0.10 # Tight tolerance: 10cm from plane
    use_spatial_coherence: true # Group spatially connected points

    # ─────────────────────────────────────────────────────────────────────
    # ROOF TYPE CLASSIFICATION
    # ─────────────────────────────────────────────────────────────────────
    classify_roof_types: true # Enable automatic roof classification
    # Output classes: flat, gable (2 pans), hip (4+ pans), complex

    # ─────────────────────────────────────────────────────────────────────
    # ARCHITECTURAL ELEMENTS (LOD3 Detail Level)
    # ─────────────────────────────────────────────────────────────────────
    detect_architectural_elements: true # Enable detailed element detection

    # Balconies (balcons)
    balcony_max_area: 20.0 # Maximum area for balconies (m²)
    balcony_height_range: [2.0, 15.0] # Height range for balconies (meters)
    balcony_max_points: 500 # Maximum points for balcony elements

    # Chimneys (cheminées)
    chimney_max_area: 10.0 # Maximum area for chimneys (m²)
    chimney_min_height: 8.0 # Minimum height for chimneys (meters)
    chimney_max_points: 300 # Maximum points for chimney elements

    # Dormers (lucarnes)
    dormer_min_protrusion: 1.0 # Minimum protrusion above roof (meters)
    dormer_max_area: 15.0 # Maximum area for dormers (m²)

    # Parapets (garde-corps)
    parapet_height_range: [0.5, 2.0] # Height range for parapets (meters)
    parapet_max_points: 200 # Maximum points for parapet elements

# ============================================================================
# FEATURES - Enhanced for Plane Detection
# ============================================================================
features:
  mode: "lod3" # LOD3 feature mode
  include_extra: true

  # High-resolution geometric parameters for plane detection
  k_neighbors: 30 # More neighbors for accurate normal estimation
  search_radius: 1.5 # Larger radius for context

  # Essential features for plane detection
  compute_normals: true # CRITICAL for plane detection
  compute_curvature: true # Helps distinguish planes from curved surfaces
  compute_height: true # Height above ground for element classification
  compute_geometric: true # Planarity, verticality, linearity

  # Architectural analysis
  compute_architectural: true
  architectural_styles: true # Detailed style analysis

  # Boundary detection for fine details
  compute_boundaries: true

  # GPU settings
  use_gpu_chunked: true
  gpu_batch_size: 2_000_000

  # Spectral features (optional)
  use_rgb: true
  use_nir: false
  compute_ndvi: false

# ============================================================================
# DATA SOURCES - BD TOPO for Building Footprints
# ============================================================================
data_sources:
  # BD TOPO: Essential for building clustering
  bd_topo:
    enabled: true
    features:
      buildings: true # REQUIRED for building clustering
      roads: true
      water: true
      vegetation: true

  bd_topo_bridges: true
  bd_topo_power_lines: true

  # Cadastre for additional building sources
  cadastre:
    enabled: true

  # Orthophotos (optional, for RGB features)
  orthophoto_rgb: false
  orthophoto_nir: false

# ============================================================================
# GROUND TRUTH - Optional Classification
# ============================================================================
ground_truth:
  enabled: false # Disabled by default - plane detection is geometry-based
  method: "gpu_chunked"
  chunk_size: 20_000_000

# ============================================================================
# OUTPUT CONFIGURATION
# ============================================================================
output:
  format: "laz" # LAZ output
  save_enriched: true # Save enriched point cloud
  save_metadata: true # Save plane detection metadata
  save_stats: true # Save statistics (plane counts, areas, roof types)

  # Additional outputs for plane analysis
  parcel_stats_format: "csv" # CSV with building-level statistics

# ============================================================================
# PREPROCESSING (Optional)
# ============================================================================
preprocess:
  enabled: false # Disabled by default
  remove_outliers: true
  outlier_std_multiplier: 3.0

# ============================================================================
# TILE STITCHING (Optional)
# ============================================================================
stitching:
  enabled: false # Disabled by default
  buffer_size: 15.0 # 15m buffer if enabled
  blend_overlap: true

# ============================================================================
# HYDRA CONFIGURATION
# ============================================================================
hydra:
  run:
    dir: outputs/plane_detection/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    name: plane_detection_lod3
# ============================================================================
# EXPECTED RESULTS
# ============================================================================
# Plane Detection Coverage:
#   - Horizontal planes: 15-25% of building points (flat roofs, terraces)
#   - Vertical planes: 30-45% of building points (walls, facades)
#   - Inclined planes: 20-35% of building points (pitched roofs)
#   - Other (edges, corners): 10-20%
#
# Roof Type Distribution (typical residential area):
#   - Flat roofs: 20-30% of buildings
#   - Gable roofs (2 pans): 30-45% of buildings
#   - Hip roofs (4+ pans): 15-25% of buildings
#   - Complex roofs: 10-20% of buildings
#
# Architectural Elements (per 100 buildings):
#   - Chimneys: 30-60 detected
#   - Dormers: 10-30 detected
#   - Balconies: 20-50 detected
#   - Parapets: 15-35 detected
#
# Performance (RTX 4080, 18.6M point tile):
#   - Building clustering: ~30 seconds
#   - Normal computation: ~45 seconds
#   - Plane detection: ~1-2 minutes
#   - Roof classification: ~15 seconds
#   - Element detection: ~30 seconds
#   - Total processing: ~5-7 minutes per tile
#
# Quality Metrics:
#   - Plane detection accuracy: 85-95%
#   - Roof type classification: 80-90%
#   - Architectural element detection: 70-85% (varies by element type)
#   - Building clustering completeness: 95-99%
# ============================================================================
