# ============================================================================
# MEMORY-OPTIMIZED CONFIGURATION FOR HYBRID MODEL TRAINING
# ============================================================================
# Optimizations to prevent OOM (Out of Memory) errors:
# 1. Reduced num_workers (4 -> 2) - Less parallel processing
# 2. Smaller GPU batch size (1M -> 500K) - Less GPU memory
# 3. Reduced batch_size (4 -> 2) - Less CPU memory per worker
# 4. Disabled neighbor auto-download - Process sequentially
# 5. Reduced prefetch_factor (2 -> 1) - Less memory overhead
# 6. Enabled chunk processing with lower memory limit
# 7. More aggressive garbage collection
# ============================================================================

processor:
  lod_level: LOD3
  architecture: hybrid
  use_gpu: true
  num_workers: 2 # REDUCED: 4 -> 2 (less parallel memory usage)
  patch_size: 150.0
  patch_overlap: 0.1
  num_points: 32768
  augment: true
  num_augmentations: 3
  batch_size: 2 # REDUCED: 4 -> 2 (less memory per worker)
  prefetch_factor: 1 # REDUCED: 2 -> 1 (less prefetching)
  pin_memory: false # DISABLED: Reduces memory pressure

features:
  mode: full
  k_neighbors: 32
  include_extra: true
  use_rgb: false
  use_infrared: false
  compute_ndvi: false
  sampling_method: fps
  normalize_xyz: true
  normalize_features: true
  gpu_batch_size: 500000 # REDUCED: 1M -> 500K (less GPU memory)
  use_gpu_chunked: true

preprocess:
  enabled: true
  sor_k: 12
  sor_std: 2.0
  ror_radius: 0.0
  ror_neighbors: 0
  voxel_enabled: false
  voxel_size: 0.1

stitching:
  enabled: true
  buffer_size: 10.0
  adaptive_buffer: true
  min_buffer: 5.0
  max_buffer: 25.0
  auto_detect_neighbors: true
  auto_download_neighbors: false # DISABLED: Process sequentially to save memory
  neighbor_search_radius: 50.0
  max_neighbors: 8
  use_grid_pattern: true
  cache_enabled: true
  cache_size: 500 # REDUCED: 1000 -> 500 (smaller cache)
  parallel_loading: false # DISABLED: Load neighbors sequentially
  prefetch_neighbors: false # DISABLED: Don't prefetch neighbors
  overlap_threshold: 0.1
  boundary_smoothing: true
  edge_artifact_removal: true
  seamless_blending: true
  memory_limit: 4096 # REDUCED: 8192 -> 4096 (4GB limit per tile)
  chunk_processing: true
  gc_frequency: 5 # INCREASED: 10 -> 5 (more frequent garbage collection)
  compute_boundary_features: true
  boundary_feature_radius: 5.0
  cross_tile_neighborhoods: true
  preserve_tile_metadata: true
  verbose_logging: true
  save_boundary_masks: false
  save_stitching_stats: true
  timing_analysis: false

output:
  format: npz, laz
  processing_mode: patches_only
  compression: null
  save_stats: true
  save_metadata: true

input_dir: /mnt/c/Users/Simon/ign/enriched_tiles
output_dir: /mnt/c/Users/Simon/ign/patches

num_workers: 2 # Match processor.num_workers
verbose: true
log_level: INFO

bbox:
  xmin: null
  ymin: null
  xmax: null
  ymax: null
