# ============================================================================
# IGN LiDAR HD - ASPRS CPU-Optimized Configuration (V3 - VERY AGGRESSIVE)
# ============================================================================
# Purpose: MOST AGGRESSIVE configuration for cases where V2 still has >20% unclassified
#
# ⚠️ This is V3 - Use only if V2 (config_asprs_bdtopo_cadastre_cpu_fixed.yaml) still shows >20% unclassified
#
# V3 CHANGES from V2 (2025-10-24):
# 1. Even Lower Confidence Thresholds (CRITICAL)
#    - min_classification_confidence: 0.40 → 0.35 (even less strict)
#    - expansion_confidence_threshold: 0.50 → 0.45 (more expansion)
#    - rejection_confidence_threshold: 0.35 → 0.30 (less rejection)
#    - reclassification min_confidence: 0.50 → 0.45 (most aggressive)
#
# 2. Post-Processing Gap Filling (NEW)
#    - fill_building_gaps: true (fill gaps within buildings)
#    - morphological_closing: true (smooth boundaries)
#    - boundary_smoothing: true (reduce jagged edges)
#
# 3. More Permissive Building Signature
#    - roof_planarity_min: 0.60 → 0.55 (accept very rough roofs)
#    - min_cluster_size: 5 → 3 (tiny building parts OK)
#
# ⚠️ WARNING: This configuration may produce false positives
# - Use only if V2 still shows >20% unclassified rate
# - Carefully validate results to ensure quality
# - May classify some vegetation/noise as buildings
#
# Expected Improvement over V2:
# - Unclassified rate: 15-20% → <10%
# - Building coverage: 85-95% → 90-98%
# - Trade-off: Increased false positives (5-10%)
#
# See docs/QUICK_START_V2.md for guidance
#
# Hardware Requirements:
# - RAM: 32GB system memory
# - CPU: Multi-core recommended
# - No GPU required
#
# Usage:
#   ign-lidar-hd process \
#     -c examples/config_asprs_bdtopo_cadastre_cpu_v3.yaml \
#     input_dir="/path/to/tiles" \
#     output_dir="/path/to/output"
# ============================================================================

defaults:
  - base/processor
  - base/features
  - base/data_sources
  - base/output
  - base/monitoring
  - _self_

# Configuration metadata
config_version: "5.3.2"
config_name: "asprs_bdtopo_cadastre_cpu_v3_very_aggressive"
config_description: "V3 - Most Aggressive Classification for Stubborn Unclassified Points"

# ============================================================================
# PROCESSOR - CPU-Optimized Settings
# ============================================================================
processor:
  lod_level: "ASPRS"
  processing_mode: "enriched_only"

  use_gpu: false
  num_workers: 1

  chunk_size: 5_000_000
  ground_truth_method: "strtree"
  ground_truth_chunk_size: 5_000_000

  use_strategy_pattern: true

  use_cuda_streams: false
  enable_memory_pooling: false
  enable_pipeline_optimization: false
  enable_async_transfers: false
  adaptive_chunk_sizing: true
  auto_optimize: false

  skip_existing: false
  output_format: "laz"
  use_stitching: false

  patch_size: 50.0
  patch_overlap: 0.1
  num_points: 24576
  architecture: "direct"
  augment: false
  num_augmentations: 0

  # ============================================================================
  # RECLASSIFICATION - V3 MOST AGGRESSIVE
  # ============================================================================
  reclassification:
    enabled: true
    acceleration_mode: "cpu"
    chunk_size: 2_000_000
    min_confidence: 0.45 # ⬇️ V3: Reduced from 0.50 (MOST aggressive)
    use_geometric_rules: true
    use_ndvi_classification: true
    show_progress: true
    ndvi_vegetation_threshold: 0.3
    ndvi_road_threshold: 0.15
    use_spectral_rules: true
    nir_vegetation_threshold: 0.35
    nir_building_threshold: 0.25
    use_clustering: true
    spatial_cluster_eps: 0.6 # ⬆️ V3: Increased from 0.5 for even larger clusters
    min_cluster_size: 3 # ⬇️ V3: Reduced from 5 for tiny clusters
    building_buffer_distance: 6.0 # ⬆️ V3: Increased from 5.0m for widest expansion
    verticality_threshold: 0.50 # ⬇️ V3: Reduced from 0.55 for very permissive walls

  building_clustering:
    enabled: true
    use_centroid_attraction: true
    attraction_radius: 5.0
    min_points_per_building: 10
    adjust_polygons: true
    polygon_buffer: 0.5
    wall_buffer: 0.3
    detect_near_vertical_walls: true

  # ============================================================================
  # POST-PROCESSING - V3 NEW SECTION
  # ============================================================================
  post_processing:
    enabled: true

    # Fill gaps within building footprints
    fill_building_gaps: true
    max_gap_distance: 2.0 # meters
    min_gap_points: 3
    gap_classification_method: "nearest_neighbor"

    # Morphological operations for smoother buildings
    morphological_closing: true
    kernel_size: 1.5 # meters
    iterations: 2

    # Smooth building boundaries
    smooth_boundaries: true
    smoothing_radius: 1.5 # meters
    preserve_corners: true
    min_corner_angle: 60.0 # degrees

# ============================================================================
# FEATURES - CPU-Optimized Settings
# ============================================================================
features:
  mode: "asprs_classes"
  include_extra: true

  k_neighbors: 50
  search_radius: 1.5

  use_gpu: false
  use_gpu_chunked: false

  neighbor_query_batch_size: 2_000_000
  feature_batch_size: 2_000_000

  compute_normals: true
  compute_curvature: true
  compute_height: true
  compute_geometric: true

  compute_planarity: true
  compute_verticality: true
  compute_linearity: true
  compute_sphericity: true
  compute_eigenfeatures: true

  height_method: "hybrid"
  use_rge_alti_for_height: true
  dtm_interpolation: "bilinear"
  compute_height_above_ground: true
  compute_height_local: true
  compute_z_from_dtm: true

  use_rgb: true
  use_nir: true
  use_infrared: true
  compute_ndvi: true

  compute_architectural: false
  architectural_styles: false
  compute_boundaries: false
  compute_multiscale: false

  enable_caching: true
  cache_max_size: 50
  enable_auto_tuning: false
  validate_features: true
  handle_nan_values: true

# ============================================================================
# VARIABLE OBJECT FILTERING
# ============================================================================
variable_object_filtering:
  enabled: true
  filter_vehicles: true
  vehicle_height_range: [0.8, 4.0]
  filter_urban_furniture: true
  furniture_height_range: [0.5, 4.0]
  furniture_max_cluster_size: 50
  filter_walls: false
  wall_height_range: [0.5, 2.5]
  wall_min_verticality: 0.8
  reclassify_to: 1
  create_vehicle_class: true
  vehicle_class_code: 18
  verbose: true

  building_fusion:
    enabled: true
    source_priority:
      - "bd_topo"
      - "cadastre"
      - "osm"
    min_quality_score: 0.50
    quality_difference_threshold: 0.10
    fusion_mode: "best"
    enable_multi_source_fusion: true
    enable_translation: true
    max_translation: 12.0
    enable_scaling: true
    max_scale_factor: 2.5
    enable_rotation: true
    max_rotation: 45.0
    enable_buffering: true
    adaptive_buffer_range: [0.8, 2.0]
    min_points_per_building: 12
    wall_detection_threshold: 0.60
    overlap_threshold: 0.28
    merge_nearby_buildings: true
    merge_distance_threshold: 2.0

  building_clustering:
    enabled: true
    use_centroid_attraction: true
    attraction_radius: 6.0
    min_points_per_building: 8
    adjust_polygons: false
    polygon_buffer: 0.0
    wall_buffer: 0.0
    detect_near_vertical_walls: true

  # ============================================================================
  # ADAPTIVE BUILDING CLASSIFICATION - V3 MOST AGGRESSIVE
  # ============================================================================
  adaptive_building_classification:
    enabled: true
    signature:
      min_height: 1.2
      typical_height_range: [2.0, 60.0]
      wall_verticality_min: 0.50 # ⬇️ V3: Reduced from 0.55 for VERY permissive walls
      wall_planarity_max: 0.65
      roof_planarity_min: 0.55 # ⬇️ V3: Reduced from 0.60 for very rough roofs
      roof_curvature_max: 0.25 # ⬆️ V3: Increased from 0.20 for very curved roofs
      roof_normal_z_range: [0.10, 1.0] # ⬇️ V3: Lowered from [0.15, 1.0] for steepest roofs
      ndvi_max: 0.28
      ndvi_wall_max: 0.22
      min_cluster_size: 3 # ⬇️ V3: Reduced from 5 for tiny clusters
      max_isolation_distance: 6.0
    fuzzy_boundary_inner: 0.0
    fuzzy_boundary_outer: 6.0 # ⬆️ V3: Increased from 5.0m for widest fuzzy zone
    fuzzy_decay_function: "gaussian"
    enable_adaptive_expansion: true
    max_expansion_distance: 7.0 # ⬆️ V3: Increased from 6.0m for maximum expansion
    expansion_confidence_threshold: 0.45 # ⬇️ V3: Reduced from 0.50 for MAXIMUM expansion
    enable_intelligent_rejection: true
    rejection_confidence_threshold: 0.30 # ⬇️ V3: Reduced from 0.35 for MINIMUM rejection
    enable_spatial_clustering: true
    spatial_radius: 2.5
    min_neighbor_ratio: 0.25
    min_classification_confidence: 0.35 # ⬇️ V3: Reduced from 0.40 for MAXIMUM permissiveness
    feature_weights:
      height: 0.25
      geometry: 0.30
      spectral: 0.15
      spatial: 0.15
      ground_truth: 0.15

  plane_detection:
    enabled: true
    horizontal_angle_max: 15.0
    horizontal_planarity_min: 0.68
    vertical_angle_min: 70.0
    vertical_planarity_min: 0.58
    inclined_angle_min: 15.0
    inclined_angle_max: 70.0
    inclined_planarity_min: 0.62
    min_points_per_plane: 35
    max_plane_distance: 0.20
    use_spatial_coherence: true
    classify_roof_types: true
    detect_architectural_elements: false

# ============================================================================
# DATA SOURCES
# ============================================================================
data_sources:
  bd_topo:
    enabled: true
    features:
      buildings: true
      roads: true
      water: true
      vegetation: false
    wfs_url: "https://data.geopf.fr/wfs"
    max_features: 10000
    timeout: 30
    cache_enabled: true
    cache_dir: null
    use_global_cache: false
    use_gpu: false
    road_buffer: 2.5
    building_priority: 1
    road_priority: 2
    water_priority: 3
    vegetation_priority: 4

  bd_topo_bridges: true
  bd_topo_power_lines: true
  bd_topo_sports: true
  bd_topo_cemeteries: true
  bd_topo_parking: false

  cadastre:
    enabled: true
    wfs_url: "https://data.geopf.fr/wfs"
    typename: "CADASTRALPARCELS.PARCELLAIRE_EXPRESS:parcelle"
    use_as_building_proxy: true
    cache_dir: null

  cadastre_enabled: true
  cadastre_cache_dir: null

  osm:
    enabled: true
    overpass_url: "https://overpass-api.de/api/interpreter"
    timeout: 180
    building_tags:
      - "building=yes"
      - "building=house"
      - "building=residential"
      - "building=apartments"
      - "building=commercial"
      - "building=industrial"
      - "building=retail"
      - "building=office"
      - "building=school"
      - "building=church"
      - "building=hospital"
    min_building_area: 8.0
    max_building_area: 15000.0
    cache_enabled: true
    cache_dir: null
    cache_ttl_days: 30

  rge_alti:
    enabled: true
    use_wcs: true
    use_local: false
    wcs_url: "https://wxs.ign.fr/altimetrie/geoportail/r/wcs"
    coverage_id: "ELEVATION.ELEVATIONGRIDCOVERAGE.HIGHRES"
    api_key: "pratique"
    resolution: 1.0
    local_dtm_dir: null
    cache_enabled: true
    cache_dir: null
    cache_ttl_days: 90

    augment_ground_points: true
    augmentation_spacing: 0.5 # ⬇️ V3 MAX: Réduit de 2.0m → 0.5m (16x plus de points!)
    augmentation_areas:
      - "vegetation"
      - "gaps"
      - "buildings"
      - "all" # ⬆️ V3 MAX: Ajouter des points PARTOUT

    compute_height_from_dtm: true
    dtm_height_priority: "high" # ⬆️ V3 MAX: Priorité haute pour le DTM

  bd_foret_enabled: false
  rpg_enabled: false
  orthophoto_rgb: true
  orthophoto_nir: true
  orthophoto_cache_dir: null

# ============================================================================
# GROUND TRUTH
# ============================================================================
ground_truth:
  enabled: true
  method: "strtree"
  chunk_size: 5_000_000
  cache_dir: null
  cache_ttl_days: 30
  cache_compression: true
  preclassify: true
  show_progress: true
  use_gpu: false

  adaptive_mode: true
  fuzzy_boundary_enabled: true
  fuzzy_boundary_inner: 0.0
  fuzzy_boundary_outer: 2.5
  fuzzy_decay_function: "gaussian"
  adaptive_expansion_enabled: true
  max_expansion_distance: 3.5
  expansion_confidence_threshold: 0.65
  intelligent_rejection_enabled: true
  rejection_confidence_threshold: 0.45
  reject_vegetation_in_polygons: true
  reject_outliers_in_polygons: true

  rge_alti:
    enabled: true
    augment_ground: true
    augmentation_strategy: "all" # ⬆️ V3 MAX: "all" au lieu de "intelligent" pour MAXIMUM de points
    augmentation_spacing: 0.5 # ⬇️ V3 MAX: Réduit de 2.0m → 0.5m (16x plus de points!)
    min_spacing_to_existing: 0.5 # ⬇️ V3 MAX: Réduit de 1.5m → 0.5m (plus dense)
    augmentation_priority:
      vegetation: true
      buildings: true
      water: true # ⬆️ V3 MAX: Activer water
      roads: true # ⬆️ V3 MAX: Activer roads
      gaps: true
      all: true # ⬆️ V3 MAX: Ajouter "all"
    max_height_difference: 5.0 # ⬆️ V3 MAX: Augmenté de 3.0m → 5.0m (plus tolérant)
    validate_against_neighbors: false # ⬇️ V3 MAX: Désactiver validation stricte
    synthetic_ground_class: 2
    mark_as_synthetic: true

  bd_topo:
    enabled: true
    classification_mapping:
      buildings: 6
      roads: 11
      railways: 10
      water: 9
      low_vegetation: 3
      medium_vegetation: 4
      high_vegetation: 5
      bridges: 17
      parking: 11
      cemeteries: 2
      sports: 11
      power_lines: 14
    road_buffer: 3.0
    railway_buffer: 2.5
    power_line_buffer: 6.0
    building_buffer: 1.2
    water_buffer: 1.5
    road_width_fallback: 5.0
    railway_width_fallback: 4.0
    road_min_width: 1.5
    road_max_width: 60.0

  cadastre:
    enabled: true
    min_parcel_area: 8.0
    min_parcel_points: 15
    group_by_parcel: true
    export_parcel_stats: true

  integration:
    method: "priority_based"
    priority:
      bd_topo: 1
      cadastre: 2
      orthophoto: 4
      geometric_rules: 5
    confidence_threshold: 0.65

  quality_control:
    enabled: true
    validate_geometries: true
    check_coverage: true
    min_coverage_ratio: 0.15

  parallel_fetch: true
  max_parallel_requests: 8

# ============================================================================
# OUTPUT CONFIGURATION
# ============================================================================
output:
  format: "laz"
  save_enriched: true
  save_patches: false
  save_metadata: true
  save_stats: true
  compression: null
  validate_output: true
  save_fusion_report: true
  save_quality_scores: true
  save_adapted_polygons: true
  save_dtm_augmentation_report: true
  save_dtm_grid: false
  save_height_comparison: true
  include_dtm_height: true
  include_local_height: true
  include_dtm_elevation: true
  include_synthetic_flag: true
  save_adaptive_report: true
  include_confidence_scores: true
  extra_dims:
    - name: "BuildingConfidence"
      type: "float32"
      description: "Building classification confidence (0-1)"
    - name: "IsWall"
      type: "uint8"
      description: "1 if point is likely a wall"
    - name: "IsRoof"
      type: "uint8"
      description: "1 if point is likely a roof"
    - name: "DistanceToPolygon"
      type: "float32"
      description: "Signed distance to nearest building polygon (m)"
    - name: "AdaptiveExpanded"
      type: "uint8"
      description: "1 if classified via adaptive expansion"
    - name: "IntelligentRejected"
      type: "uint8"
      description: "1 if rejected despite being in polygon"
  export_parcel_stats: true
  parcel_stats_format: "csv,geojson,html"

# ============================================================================
# LOGGING
# ============================================================================
logging:
  level: INFO
  show_progress: true
  detailed_timing: true
  enable_performance_metrics: true
  enable_profiling: false

# ============================================================================
# PREPROCESSING & STITCHING
# ============================================================================
preprocess:
  enabled: false
  remove_duplicates: true
  remove_outliers: true
  outlier_std_multiplier: 3.0

stitching:
  enabled: false
  buffer_size: 10.0
  blend_overlap: true

# ============================================================================
# OPTIMIZATIONS
# ============================================================================
optimizations:
  enable_caching: true
  cache_max_size_mb: 100
  enable_parallel_processing: false
  max_workers: 1
  enable_auto_tuning: false
  adaptive_parameters: true
  enable_performance_metrics: true
  enable_profiling: false

validation:
  strict_validation: true
  check_gpu_availability: false
  check_memory_requirements: true

hardware:
  auto_detect: true
  prefer_gpu: false
  fallback_cpu: true

# ============================================================================
# HYDRA CONFIGURATION
# ============================================================================
hydra:
  run:
    dir: outputs/asprs_bdtopo_cadastre_cpu_v3/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    name: asprs_bdtopo_cadastre_cpu_v3_very_aggressive
