# ========================================================================
# LOD3 Training Patches Configuration - 150m Scale (Full Context)
# ========================================================================
# Purpose: Generate ML training patches with complete building context
#
# Key Features:
# - Large patch size (150m) for full buildings and urban context
# - Full point capacity (32k) for comprehensive geometric analysis
# - Efficient overlap (10%) for large-scale coverage
# - Fewer augmentations (3) as patches already capture variation
# - Larger k-neighbors (30) for contextual feature computation
#
# Use Case:
# - Training on large commercial/industrial buildings
# - Complete building classification
# - Urban context and layout analysis
# - Part of multi-scale training strategy (Phase 3)
#
# Output Example:
#   LHD_FXX_0649_6863_hybrid_patch_0001.npz (32,768 points)
#   LHD_FXX_0649_6863_hybrid_patch_0001.laz
# ========================================================================

processor:
  lod_level: LOD3
  architecture: hybrid
  use_gpu: true
  num_workers: 2 # Lower for large patches (more memory intensive)
  patch_size: 150.0 # Large patches for full building context
  patch_overlap: 0.1 # Efficient overlap for large scale
  num_points: 32768 # Full PointNet++ capacity
  augment: true
  num_augmentations: 3 # Fewer needed (large patches capture variation)
  pin_memory: true

features:
  mode: full
  k_neighbors: 30 # Larger neighborhood for contextual features
  search_radius: 1.8 # Larger radius for 150m patches (wider context)
  include_extra: true
  use_rgb: true
  use_infrared: true
  compute_ndvi: true
  sampling_method: fps
  normalize_xyz: true
  normalize_features: true
  gpu_batch_size: 1000000
  use_gpu_chunked: true

preprocess:
  enabled: true
  sor_k: 12 # More thorough filtering for large patches
  sor_std: 2.0 # Standard threshold for complete buildings
  ror_radius: 1.0 # Larger radius appropriate for 150m scale
  ror_neighbors: 5 # More stringent for large context
  voxel_enabled: false
  voxel_size: 0.1

stitching:
  enabled: true
  buffer_size: 15.0 # Medium buffer for 150m patches
  auto_detect_neighbors: true
  auto_download_neighbors: true
  cache_enabled: true

output:
  format: npz,laz
  processing_mode: patches_only
  save_stats: true
  save_metadata: true
  compression: null

input_dir: /mnt/c/Users/Simon/ign/enriched_tiles
output_dir: /mnt/c/Users/Simon/ign/patches_150m
