# ========================================================================
# Architectural Heritage Analysis (V5.1)
# ========================================================================
# Purpose: Process heritage sites with architectural style classification
#          for analysis and visualization (not training)
#
# Key Features:
# - Constant encoding (memory efficient)
# - Full-resolution processing (no subsampling)
# - Multi-format output with style annotations
# - Style statistics and distribution analysis
#
# Use Cases:
# - Architectural heritage documentation
# - Urban planning and conservation
# - Historical building analysis
# - 3D GIS integration with style metadata
#
# Usage:
#   ign-lidar-hd process --config-file examples/config_architectural_analysis_v5.0.yaml
#
# Package Version: 3.1.0
# Config Version: 5.1.0
# Date: October 18, 2025
# ========================================================================

# Inherit from FULL preset (Hydra defaults system)
defaults:
  - presets/full
  - _self_

# Override processor settings for analysis mode
processor:
  patch_size: null # No patching - enrich full tiles
  patch_overlap: 0.0
  num_points: null
  augment: false # No augmentation for analysis
  num_augmentations: 0
  num_workers: 4 # More workers for faster processing

# Enable architectural style detection (constant encoding)
features:
  include_architectural_style: true
  style_encoding: constant # Memory-efficient constant encoding

# Output configuration for analysis
output:
  processing_mode: tiles_only # Process full tiles only
  format: laz,ply,las # Multiple formats for GIS integration
  save_stats: true # Save style statistics
  save_metadata: true # Save style distribution metadata

# Hydra output directory
hydra:
  run:
    dir: outputs/architectural_analysis/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    name: architectural_analysis
# ========================================================================
# All other settings inherited from full preset:
# - GPU acceleration enabled
# - LOD3 classification (30 classes)
# - Full geometric + spectral features
# - Architectural style detection
# - Optimized ground truth classification
# - Geometric reclassification refinement
# - Statistical + radius outlier removal
# - Tile stitching with 15m buffer
# ========================================================================
