# ========================================================================
# Multi-Scale Hybrid Training Configuration
# ========================================================================
# Purpose: Train hybrid model with different feature sets per scale
#
# Strategy:
# - 50m patches: LOD3 full features (35 features) - fine details
# - 100m patches: LOD3 full features (35 features) - medium context
# - 150m patches: LOD2 simplified (11 features) - coarse context
#
# This configuration demonstrates intelligent feature scaling:
# - Small patches need all details for architectural features
# - Large patches benefit from simplified features for generalization
# ========================================================================

processor:
  lod_level: LOD3
  architecture: multiscale_hybrid
  use_gpu: true
  num_workers: 2

  # Multi-scale patches
  patch_configs:
    - size: 50.0
      num_points: 24000
      weight: 0.4
      feature_mode: lod3
    - size: 100.0
      num_points: 32000
      weight: 0.35
      feature_mode: lod3
    - size: 150.0
      num_points: 32000
      weight: 0.25
      feature_mode: lod2

  patch_overlap: 0.1
  augment: true
  num_augmentations: 3
  pin_memory: true

features:
  # Default to LOD3 (can be overridden per patch size)
  mode: lod3
  k_neighbors: 30
  search_radius: 1.5 # Radius search eliminates scan line artifacts
  include_extra: true

  # Spectral features
  use_rgb: true
  use_infrared: true
  compute_ndvi: true

  # Sampling and normalization
  sampling_method: fps
  normalize_xyz: true
  normalize_features: true

  # GPU optimization
  gpu_batch_size: 1000000
  use_gpu_chunked: true

preprocess:
  enabled: true
  sor_k: 12
  sor_std: 2.0
  ror_radius: 1.0
  ror_neighbors: 4
  voxel_enabled: false

stitching:
  enabled: true
  buffer_size: 15.0
  auto_detect_neighbors: true
  auto_download_neighbors: true
  cache_enabled: true

output:
  format: npz,laz
  processing_mode: patches_only
  save_stats: true
  save_metadata: true
  compression: null

input_dir: /mnt/c/Users/Simon/ign/enriched_tiles
output_dir: /mnt/c/Users/Simon/ign/patches_multiscale_hybrid
