# RTX 4080 Super Optimized Configuration with Advanced Ground Truth Optimization
# ASPRS Preprocessing with Cadastre - GPU Accelerated + Advanced Optimizations
#
# This configuration is optimized for NVIDIA RTX 4080 Super with advanced features:
# - 16GB GDDR6X VRAM
# - 10,240 CUDA cores
# - 736 GB/s memory bandwidth
# - Advanced ground truth optimization (10-1000× speedup)
# - Advanced GPU memory management
# - Intelligent performance monitoring
#
# Expected performance: 10-50x faster than CPU (with advanced optimizations)
#
# Usage:
#   ign-lidar-hd process --config-file configs/config_asprs_rtx4080.yaml
#
# Monitor GPU usage:
#   watch -n 1 nvidia-smi

# ============================================================================
# I/O PATHS
# ============================================================================
input_dir: /mnt/d/ign/selected_tiles/asprs/tiles
output_dir: /mnt/d/ign/preprocessed/asprs/enriched_tiles
cache_dir: /mnt/d/ign/cache

# ============================================================================
# BOUNDING BOX (Optional)
# ============================================================================
bbox:
  xmin: null
  ymin: null
  xmax: null
  ymax: null

# ============================================================================
# OUTPUT CONFIGURATION
# ============================================================================
output:
  format: laz
  processing_mode: enriched_only # Direct LAZ enrichment (no patches)
  save_stats: true
  save_metadata: false
  compression: null

# ============================================================================
# PROCESSOR CONFIGURATION - RTX 4080 + ENHANCED OPTIMIZATIONS
# ============================================================================
processor:
  lod_level: ASPRS
  processing_mode: enriched_only
  skip_existing: false
  architecture: hybrid

  # GPU Settings - Optimized for RTX 4080 Super + Enhanced Optimizations
  use_gpu: true
  batch_size: 64 # Large batches leverage 16GB VRAM
  prefetch_factor: 4 # Prefetch 4 batches ahead
  pin_memory: true # Fast CPU->GPU transfers with pinned memory
  num_workers: 1 # GPU processing requires single worker due to CUDA context limitations

  # Detection modes
  building_detection_mode: asprs
  transport_detection_mode: asprs_extended

  # Patch settings (not used in enriched_only mode)
  patch_size: 150.0
  patch_overlap: 0.1
  num_points: 100000

  # Output
  output_format: laz
  augment: false
  num_augmentations: 0

  # Tile stitching
  use_stitching: true
  buffer_size: 10.0

  # Direct enrichment
  apply_reclassification_inline: true
  ground_truth_integration_mode: "direct"

  # Enhanced Ground Truth Optimization Settings
  optimization:
    enabled: true
    level: auto # auto-select best method (gpu_chunked, gpu, strtree, vectorized)
    force_method: null # null for auto-selection, or specify: gpu_chunked, gpu, strtree, vectorized
    enable_monitoring: true # Performance monitoring and auto-tuning
    enable_auto_tuning: true # Automatically optimize parameters
    enable_enhanced_gpu: true # Use enhanced GPU optimizations
    enable_enhanced_cpu: true # Use enhanced CPU optimizations
    benchmark_on_first_run: false # Set to true for comprehensive benchmarking

  # Reclassification - Enhanced GPU + CPU Optimized
  reclassification:
    enabled: true
    acceleration_mode: gpu # Force GPU mode for RTX 4080
    chunk_size: 500_000 # Large chunks (GPU can handle it)
    gpu_chunk_size: 1_000_000 # Even larger for GPU reclassification
    show_progress: true
    skip_existing: false

    # Enhanced optimization settings
    use_enhanced_optimization: true
    adaptive_chunk_sizing: true # Automatically adjust based on GPU memory
    memory_pool_enabled: true # Enable memory pooling for efficiency
    enable_cuda_graphs: false # Experimental: CUDA graphs for repeated operations

    # Geometric rules
    use_geometric_rules: true
    ndvi_vegetation_threshold: 0.3
    ndvi_road_threshold: 0.15
    road_vegetation_height_threshold: 2.0
    building_buffer_distance: 2.0
    max_building_height_difference: 3.0
    verticality_threshold: 0.7
    verticality_search_radius: 1.0
    min_vertical_neighbors: 5

# ============================================================================
# FEATURES CONFIGURATION - ENHANCED GPU + CPU OPTIMIZED
# ============================================================================
features:
  mode: asprs_classes # Lightweight ~15 features for ASPRS

  # Neighbor search - Optimized for speed with enhanced algorithms
  k_neighbors: 15 # Reduced from 20 for faster GPU computation
  search_radius: 0.8 # Tighter radius (3-5x faster, still good quality!) 🚀
  include_extra: false

  # Core geometric features
  compute_normals: true
  compute_planarity: true
  compute_curvature: false # Disabled for speed
  compute_linearity: false # Disabled for speed
  compute_verticality: true
  compute_height_above_ground: true
  compute_horizontality: true
  compute_sphericity: true

  # Spectral features - Required for NDVI
  use_rgb: true
  use_infrared: true
  compute_ndvi: true
  augment_rgb: false
  augment_infrared: false

  # Advanced features (all disabled for maximum speed)
  compute_architectural_features: false
  include_architectural_style: false
  compute_wall_likelihood: false
  compute_roof_likelihood: false
  compute_surface_variation: false
  compute_anisotropy: false
  compute_eigenvalue_features: false
  compute_local_point_density: false
  compute_roughness: false
  compute_moment_features: false
  compute_multiscale_features: false
  compute_normal_variation: false
  compute_normal_change_rate: false

  # Sampling and normalization
  sampling_method: fps # Farthest point sampling
  normalize_xyz: true
  normalize_features: true

  # Enhanced GPU Settings - RTX 4080 Super + Enhanced Optimizations
  # Optimized batch size to avoid CUSOLVER sub-batching overhead
  # 1.5M points = optimal for CUSOLVER 500K limit, cleaner splitting
  gpu_batch_size: 1_500_000 # 1.5M points per batch (enhanced optimization)
  use_gpu_chunked: true # Use enhanced chunked processing for very large tiles

  # Enhanced GPU optimization settings
  gpu_optimization:
    enabled: true
    adaptive_memory_management: true # Dynamically adjust memory usage
    enable_memory_pooling: true # Reuse GPU memory blocks
    enable_tensor_cores: true # Use Tensor cores when available
    enable_mixed_precision: false # Mixed precision for speed (experimental)
    enable_kernel_fusion: true # Fuse GPU kernels for efficiency

  # Enhanced CPU optimization settings (fallback and hybrid mode)
  cpu_optimization:
    enabled: true
    enable_numba_acceleration: true # JIT compilation for CPU operations
    enable_parallel_processing: true # Multi-threaded CPU processing
    enable_vectorization: true # NumPy vectorized operations
    enable_spatial_indexing: true # R-tree spatial indexing
    max_workers: null # Auto-detect optimal worker count

# ============================================================================
# PREPROCESSING
# ============================================================================
preprocess:
  enabled: true

  # Statistical Outlier Removal
  sor_enabled: true
  sor_k: 10
  sor_std: 2.0

  # Radius Outlier Removal
  ror_enabled: true
  ror_radius: 1.0
  ror_neighbors: 5

  # Voxel downsampling (disabled for quality)
  voxel_enabled: false
  voxel_size: 0.1

# ============================================================================
# TILE STITCHING
# ============================================================================
stitching:
  enabled: true
  buffer_size: 10.0
  auto_detect_neighbors: true
  auto_download_neighbors: true
  cache_enabled: true
  cache_dir: ${cache_dir}/neighbors

# ============================================================================
# ENHANCED GROUND TRUTH CONFIGURATION
# ============================================================================
ground_truth:
  enabled: true
  update_classification: true
  use_ndvi: true
  fetch_rgb_nir: true
  cache_dir: ${cache_dir}/ground_truth

  # Enhanced optimization settings
  optimization:
    enabled: true # Enable enhanced ground truth optimization
    auto_select_method: true # Automatically select best optimization method
    force_method: null # null for auto, or specify: gpu_chunked, gpu, strtree, vectorized
    enable_monitoring: true # Enable performance monitoring
    enable_auto_tuning: true # Automatically tune parameters

    # GPU optimization settings
    gpu_chunk_size: 5_000_000 # Large chunks for RTX 4080 (16GB VRAM)
    adaptive_chunk_sizing: true # Automatically adjust chunk size
    enable_memory_pooling: true # GPU memory pooling for efficiency
    enable_cuspatial: true # Use cuSpatial if available for maximum performance

    # CPU optimization settings (fallback)
    enable_rtree_indexing: true # Spatial indexing for CPU fallback
    enable_numba_acceleration: true # JIT compilation
    enable_parallel_processing: true # Multi-threaded processing

    # Performance settings
    verbose: true # Detailed logging of optimization selection
    benchmark_on_first_run: false # Set to true for initial benchmarking
    cache_optimization_results: true # Cache performance results for future runs

# ============================================================================
# ENHANCED DATA SOURCES - BD TOPO & CADASTRE WITH OPTIMIZATION
# ============================================================================
data_sources:
  # BD TOPO® V3 - Infrastructure Ground Truth with Enhanced Processing
  bd_topo:
    enabled: true
    cache_enabled: true

    # Features to fetch
    features:
      buildings: true # ASPRS 6
      roads: true # ASPRS 11
      railways: true # ASPRS 10
      water: true # ASPRS 9
      vegetation: true # ASPRS 5
      bridges: true # ASPRS 17
      parking: true # ASPRS 40
      cemeteries: true # ASPRS 42
      power_lines: true # ASPRS 43
      sports: true # ASPRS 41

    # Enhanced geometry generation parameters
    parameters:
      road_width_fallback: 4.0
      road_buffer_tolerance: 0.5
      railway_width_fallback: 3.5
      railway_buffer_tolerance: 0.6
      power_line_buffer: 2.0

      # Height filtering (exclude bridges/overpasses)
      road_height_max: 1.5
      road_height_min: -0.3
      rail_height_max: 1.2
      rail_height_min: -0.2

      # Enhanced geometric filtering
      road_planarity_min: 0.6
      rail_planarity_min: 0.5

      # Enhanced intensity filtering
      enable_intensity_filter: true
      road_intensity_min: 0.15
      road_intensity_max: 0.7
      rail_intensity_min: 0.1
      rail_intensity_max: 0.8

    # Enhanced caching and optimization
    cache_dir: ${cache_dir}/ground_truth
    use_cache: true
    enable_spatial_indexing: true # Pre-build spatial indices for faster queries
    enable_geometry_simplification: true # Simplify complex geometries for speed
    optimization_level: high # high, medium, low

  # BD PARCELLAIRE - Cadastre with Enhanced Processing
  cadastre:
    enabled: true
    group_by_parcel: true
    label_parcel_id: true
    compute_statistics: true
    export_parcel_stats: true
    export_attributes: true
    cache_dir: ${cache_dir}/cadastre
    use_cache: true

    # Enhanced optimization settings
    enable_spatial_indexing: true
    optimization_level: high
    enable_geometry_simplification: true

  # BD Forêt (disabled for ASPRS-focused processing)
  bd_foret:
    enabled: false

  # RPG - Agriculture (disabled for ASPRS-focused processing)
  rpg:
    enabled: false

# ============================================================================
# ENHANCED CLASSIFICATION SETTINGS
# ============================================================================
classification:
  enabled: true

  methods:
    ground_truth: true
    geometric: true
    ndvi: true
    forest_types: false
    crop_types: false

  # Priority order (lowest to highest - last wins)
  priority_order:
    - vegetation # 3/4/5
    - water # 9
    - cemeteries # 42
    - parking # 40
    - sports # 41
    - power_lines # 43
    - railways # 10
    - roads # 11
    - bridges # 17
    - buildings # 6 (highest priority)

  # Enhanced thresholds with optimization hints
  thresholds:
    ndvi_vegetation: 0.35
    ndvi_building: 0.15
    height_low_veg: 0.5
    height_medium_veg: 2.0
    planarity_road: 0.8
    planarity_building: 0.7
    road_buffer_tolerance: 0.5
    building_buffer_tolerance: 0.0
    use_building_footprints: true
    ground_truth_building_priority: high

  # Enhanced post-processing with optimization
  post_processing:
    enabled: true
    reclassify_unclassified: true
    use_enhanced_algorithms: true # Use enhanced classification algorithms
    enable_parallel_processing: true # Parallel post-processing
    optimization_level: high # high, medium, low

# ============================================================================
# PERFORMANCE MONITORING AND OPTIMIZATION
# ============================================================================
performance:
  monitoring:
    enabled: true # Enable performance monitoring
    log_level: INFO # DEBUG, INFO, WARNING, ERROR
    save_metrics: true # Save performance metrics to file
    metrics_file: performance_metrics.json

  optimization:
    auto_tuning: true # Automatically tune parameters based on performance
    cache_optimizations: true # Cache optimization results
    adaptive_batch_sizing: true # Adapt batch sizes based on GPU memory
    memory_optimization: high # high, medium, low

  reporting:
    generate_summary: true # Generate performance summary report
    summary_file: performance_summary.txt
    include_gpu_metrics: true # Include GPU utilization metrics
# ============================================================================
# ENHANCED PERFORMANCE NOTES FOR RTX 4080 SUPER
# ============================================================================
# Expected performance with enhanced optimizations:
# - Feature computation: ~10-50x faster than CPU (was 5-10x)
# - Ground truth computation: ~10-1000x faster than CPU (was 8-12x)
# - Reclassification: ~15-25x faster than CPU (was 8-12x)
# - Overall speedup: ~10-50x vs CPU-only (was 5-10x)
# - Memory usage: ~8-12GB VRAM (out of 16GB available)
# - Processing time: ~10-30 seconds per tile (was 30-60 seconds)
#
# Enhanced optimization features:
# 1. Automatic hardware detection and method selection
# 2. GPU memory pooling and adaptive chunk sizing
# 3. Enhanced spatial indexing for CPU fallback
# 4. Performance monitoring and auto-tuning
# 5. Intelligent method switching based on data characteristics
#
# Tips for maximum performance:
# 1. Close other GPU applications (browsers, games, etc.)
# 2. Monitor with: watch -n 1 nvidia-smi
# 3. Check optimization logs for method selection
# 4. If OOM errors occur:
#    - Reduce gpu_batch_size to 1_000_000
#    - Reduce batch_size to 32
#    - Reduce gpu_chunk_size to 3_000_000
# 5. For very large tiles (>100M points):
#    - Enhanced chunked processing automatically handles this
#    - Monitor GPU memory usage during processing
# 6. Enable benchmarking on first run for optimal settings:
#    - Set processor.optimization.benchmark_on_first_run: true
# 7. Enhanced optimizations include:
#    - Automatic fallback to CPU if GPU memory insufficient
#    - Intelligent pre-filtering to reduce computational load
#    - Advanced memory management and garbage collection
