# IGN LiDAR HD - Default Processing Configuration
# Unified configuration merging processing_config.yaml + example_enrichment_full.yaml
# Date: October 16, 2025
# Version: 3.0.0

# This is the primary configuration file for most use cases.
# For specialized needs, see configs/presets/ directory.

# ============================================================================
# Project Configuration
# ============================================================================

config_version: "3.0.0"
project_name: "ign_lidar_processing"

# ============================================================================
# Processing Mode
# ============================================================================

mode: "enrichment" # Options: enrichment, patches, both

# ============================================================================
# Input/Output Configuration
# ============================================================================

input:
  data_dir: "data/raw/lidar"
  tile_pattern: "*.laz"
  crs: "EPSG:2154" # Lambert 93 (France)

output:
  base_dir: "data/processed"
  format: "laz" # Options: laz, npz, hdf5
  save_enriched: true # Save enriched LAZ files
  save_patches: true # Save patches for ML training
  save_statistics: true # Save per-tile statistics

cache:
  base_dir: "cache"
  enabled: true

# ============================================================================
# Processing Configuration
# ============================================================================

processing:
  num_workers: 4
  max_tiles: null # null = process all tiles
  batch_size: "auto" # auto or integer

  # Performance
  prefetch_factor: 2
  pin_memory: false

# ============================================================================
# Multi-Source Data Integration
# ============================================================================

data_sources:
  # === BD TOPO® V3 - IGN Topographic Database ===
  bd_topo:
    enabled: true
    cache_enabled: true
    cache_dir: "cache/ground_truth"

    # Infrastructure features with ASPRS classification codes
    features:
      buildings: true # ASPRS code 6
      roads: true # ASPRS code 11
      railways: true # ASPRS code 10
      water: true # ASPRS code 9
      vegetation: true # ASPRS code 5
      bridges: true # ASPRS code 17
      parking: true # ASPRS code 40
      cemeteries: false # ASPRS code 42
      power_lines: false # ASPRS code 43
      sports: true # ASPRS code 41

    # Parameters for geometry generation (improved for better classification)
    parameters:
      # Road/Railway widths
      road_width_fallback: 4.0 # Default road width (m)
      railway_width_fallback: 3.5 # Default railway width (m)
      power_line_buffer: 2.0 # Buffer for power lines (m)

      # Buffers for better coverage
      road_buffer_tolerance: 0.5 # Additional buffer for roads (m)
      railway_buffer_tolerance: 0.6 # Additional buffer for railways (m)

      # Height filtering (exclude bridges/overpasses)
      road_height_max: 1.5 # Maximum height for ground-level roads (m)
      road_height_min: -0.3 # Minimum height for roads (m)
      rail_height_max: 1.2 # Maximum height for ground-level railways (m)
      rail_height_min: -0.2 # Minimum height for railways (m)

      # Geometric filtering
      road_planarity_min: 0.6 # Minimum planarity for roads (0-1)
      rail_planarity_min: 0.5 # Minimum planarity for railways (0-1)

      # Intensity filtering (surface reflectance)
      enable_intensity_filter: true
      road_intensity_min: 0.15 # Minimum intensity for roads
      road_intensity_max: 0.7 # Maximum intensity for roads
      rail_intensity_min: 0.1 # Minimum intensity for railways
      rail_intensity_max: 0.8 # Maximum intensity for railways

  # === BD Forêt® V2 - Forest Database ===
  bd_foret:
    enabled: false # Set to true to enable forest enrichment
    cache_enabled: true
    cache_dir: "cache/bd_foret"

    # Enrichment options
    label_forest_type: true # coniferous, deciduous, mixed
    label_primary_species: true # Quercus, Pinus, etc.
    label_secondary_species: false
    label_tertiary_species: false
    estimate_height: true # Height estimation by forest type

    # Add as extra dimensions in LAZ
    export_attributes:
      - forest_type # String
      - primary_species # String
      - estimated_height # Float

  # === RPG - Registre Parcellaire Graphique (Agricultural Parcels) ===
  rpg:
    enabled: false # Set to true to enable agricultural enrichment
    cache_enabled: true
    cache_dir: "cache/rpg"
    year: 2024 # Available: 2024 (latest), 2023, 2022, 2021, 2020

    # Enrichment options
    label_crop_code: true # BLE, MAI, COL, etc.
    label_crop_category: true # cereals, oleaginous, etc.
    label_crop_name: true # Wheat, Corn, etc.
    label_parcel_area: true
    label_organic_farming: true
    apply_asprs_classification: true # Code 44 for agriculture

    # Add as extra dimensions in LAZ
    export_attributes:
      - crop_code # String (3 letters)
      - crop_category # String
      - crop_name # String
      - parcel_area # Float (m²)
      - is_organic # Boolean

  # === BD PARCELLAIRE - Cadastre (Cadastral Parcels) ===
  cadastre:
    enabled: false # Set to true to enable cadastral enrichment
    cache_enabled: true
    cache_dir: "cache/cadastre"

    # Enrichment options
    label_parcel_id: true # Unique 19-char ID
    group_by_parcel: true # Create parcel groups
    compute_parcel_statistics: true

    # Add as extra dimensions in LAZ
    export_attributes:
      - parcel_id # String

    # Parcel statistics export
    export_parcel_stats:
      enabled: true
      format: "geojson" # Options: geojson, csv, both
      include_class_distribution: true
      include_point_density: true
      include_crop_types: true
      include_forest_types: true

# ============================================================================
# Feature Computation
# ============================================================================

features:
  # Geometric features
  geometric:
    enabled: true
    k_neighbors: 20
    search_radius: null # Auto-estimate if null, use k_neighbors if set

    compute:
      height: true # Height above ground
      normals: true # Surface normals
      curvature: true # Surface curvature
      planarity: true # Planarity
      linearity: false
      sphericity: false
      verticality: false

  # Spectral features
  spectral:
    rgb:
      enabled: true
      normalize: true # Normalize to 0-1 range (FIXED)
      include_in_output: true

    nir:
      enabled: false
      include_in_output: false

    ndvi:
      enabled: false # Requires both RGB and NIR
      include_in_output: false

# ============================================================================
# Classification Configuration
# ============================================================================

classification:
  # Classification methods
  methods:
    geometric: true # Use geometric features
    ndvi: false # Use NDVI (requires RGB + NIR)
    ground_truth: true # Use BD TOPO® ground truth
    forest_types: false # Use BD Forêt® (requires bd_foret.enabled)
    crop_types: false # Use RPG (requires rpg.enabled)

  # Classification priority (highest to lowest)
  # Last in list has highest priority
  priority_order:
    - ground # ASPRS 2
    - vegetation # ASPRS 3/4/5
    - agriculture # ASPRS 44
    - sports # ASPRS 41
    - parking # ASPRS 40
    - cemetery # ASPRS 42
    - road # ASPRS 11
    - rail # ASPRS 10
    - power_line # ASPRS 43
    - water # ASPRS 9
    - building # ASPRS 6
    - bridge # ASPRS 17 (highest)

  # Post-processing for unclassified points
  post_processing:
    enabled: true
    reclassify_unclassified: true
    use_ground_truth_context: true
    use_geometric_similarity: true
    min_building_height: 2.5 # Minimum height for building (m)
    min_building_planarity: 0.6 # Minimum planarity for building surfaces

  # Thresholds
  thresholds:
    # NDVI
    ndvi_vegetation: 0.35
    ndvi_building: 0.15

    # Geometry
    height_low_veg: 0.5 # Height for low vegetation (m)
    height_medium_veg: 2.0 # Height for medium vegetation (m)
    planarity_road: 0.8 # Planarity threshold for roads
    planarity_building: 0.7 # Planarity threshold for buildings

    # Ground truth
    building_buffer_tolerance: 0.0 # Strict matching for buildings

# ============================================================================
# Preprocessing Configuration
# ============================================================================

preprocessing:
  enabled: false # Set to true to enable preprocessing steps

  # Classification normalization (always recommended)
  normalize_classification: true # Fix non-standard IGN classification codes
  strict_class_normalization: false # Remap ALL unknown codes to Unclassified

  # Point cloud cleaning
  remove_noise: false # Remove statistical outliers
  remove_duplicates: false # Remove duplicate points
  filter_by_classification: false # Filter specific classes
  normalize_intensity: false # Normalize intensity values

# ============================================================================
# Export Configuration
# ============================================================================

export:
  # LAZ Export
  laz:
    enabled: true
    include_classification: true
    include_extra_dims:
      - ndvi
      - height
      - curvature
      - forest_type
      - crop_code
      - crop_category
      - parcel_id
    compression: true

  # GeoJSON Export (for GIS)
  geojson:
    enabled: true
    export_parcels: true
    include_statistics: true
    include_class_distribution: true
    include_crop_distribution: true

  # CSV Export (for analysis)
  csv:
    enabled: false
    include_all_attributes: true
    separate_by_source: false

  # Patch Export (for ML training)
  patches:
    enabled: false # Enable for ML dataset creation
    patch_size: 50 # Patch size in meters
    stride: 25 # Stride for patch extraction
    min_points: 100 # Minimum points per patch
    output_format: "npz" # Options: npz, hdf5

# ============================================================================
# Intelligent Skip Configuration
# ============================================================================

skip_checker:
  enabled: true

  # What to check for skip
  check_enriched_laz: true
  check_patches: false
  check_statistics: false

  # Validation options
  validate_content: true # Deep validation of files
  validate_features:
    - classification
    - forest_type
    - crop_code
    - parcel_id

  min_file_size_kb: 10 # Minimum file size to consider valid

  # Skip conditions
  skip_if:
    output_exists: true
    output_newer_than_input: true
    validation_passed: true
# ============================================================================
# ASPRS Classification Codes Reference
# ============================================================================

# Standard ASPRS codes:
#   1: Unclassified
#   2: Ground
#   3: Low Vegetation
#   4: Medium Vegetation
#   5: High Vegetation
#   6: Building
#   7: Low Point (noise)
#   9: Water
#  10: Rail
#  11: Road Surface
#  17: Bridge Deck

# Extended codes (used by this package):
#  40: Parking
#  41: Sports Infrastructure
#  42: Cemetery
#  43: Power Line
#  44: Agriculture

# ============================================================================
# Usage Examples
# ============================================================================

# Basic usage (this config):
#   ign-lidar-hd process --config configs/default.yaml
#
# Override specific values:
#   ign-lidar-hd process --config configs/default.yaml \
#     --set data_sources.bd_foret.enabled=true \
#     --set processing.num_workers=8
#
# Use a preset:
#   ign-lidar-hd process --config configs/presets/full_enrichment.yaml
#
# GPU-optimized processing:
#   ign-lidar-hd process --config configs/presets/gpu_optimized.yaml

# ============================================================================
# Notes
# ============================================================================

# 1. This configuration enables BD TOPO® enrichment by default
# 2. Other data sources (BD Forêt, RPG, Cadastre) are disabled by default
# 3. To enable additional sources, set their 'enabled' flag to true
# 4. Cache is enabled by default to speed up repeated processing
# 5. For minimal/fast processing, use configs/presets/minimal.yaml
# 6. For all data sources, use configs/presets/full_enrichment.yaml
