# Complete Enrichment Configuration - ASPRS with All Features
# For enriching LAZ files with BD TOPO®, BD Forêt®, RPG, and Cadastre
# Date: October 15, 2025
# Updated: Latest dataset versions (BD TOPO V3, BD Forêt V2, RPG 2024, Cadastre current)
#
# Usage:
#   python -m ign_lidar.cli.commands.process \
#     --config-file configs/enrichment_asprs_full.yaml \
#     input_dir=D:/ign/raw \
#     output_dir=D:/ign/preprocessed/asprs

# ============================================================================
# Hydra Defaults - Override base configuration
# ============================================================================

defaults:
  - processor: default
  - features: full
  - preprocess: default
  - stitching: enabled
  - output: default
  - ground_truth: enabled # ⚠️ CRITICAL: Enable ground truth data sources
  - _self_
  - optional experiment: null

# ============================================================================
# Processing Mode
# ============================================================================

mode: "enriched" # Only create enriched LAZ files, no patches
# Options: "enriched_only", "both", "patches_only"

# ============================================================================
# Input/Output Directories
# ============================================================================

input_dir: "D:/ign/raw"
output_dir: "D:/ign/preprocessed/asprs"
cache_dir: "D:/ign/cache"

# ============================================================================
# Processing Configuration
# ============================================================================

processor:
  lod_level: "ASPRS"
  processing_mode: "enriched_only" # enriched_only | both | patches_only
  num_workers: 1
  use_gpu: true

  # Patch settings (ignored in enriched_only mode)
  patch_size: 150.0
  num_points: 16384
  augment: false

  # Output
  output_format: "laz"

  # Stitching (optional)
  use_stitching: false
  buffer_size: 10.0

# ============================================================================
# Feature Configuration
# ============================================================================

features:
  mode: "asprs_classes" # full | lod2 | lod3 | minimal

  # RGB/NIR
  use_rgb: true
  use_infrared: true
  compute_ndvi: true

  # Geometric features
  include_extra_features: true
  k_neighbors: 20

  # Architectural styles (optional)
  include_architectural_style: false

# ============================================================================
# Multi-Source Data Integration
# ============================================================================

data_sources:
  # === BD TOPO® V3 - Ground Truth Classification ===
  bd_topo:
    enabled: true
    cache_enabled: true

    # All available features
    features:
      buildings: true # ASPRS 6
      roads: true # ASPRS 11 ⚠️ CRITICAL
      railways: true # ASPRS 10 ⚠️ CRITICAL
      water: true # ASPRS 9
      vegetation: true # ASPRS 5
      bridges: true # ASPRS 17
      parking: true # ASPRS 40
      cemeteries: true # ASPRS 42 (disabled by default)
      power_lines: true # ASPRS 43 (disabled by default)
      sports: true # ASPRS 41

    # Geometry generation parameters (improved for better classification)
    parameters:
      road_width_fallback: 4.0 # Default road width (m)
      road_buffer_tolerance: 0.5 # Additional buffer for roads (m)
      railway_width_fallback: 3.5 # Default railway width (m)
      railway_buffer_tolerance: 0.6 # Additional buffer for railways (m)
      power_line_buffer: 2.0 # Buffer for power lines (m)

      # Height filtering (exclude bridges/overpasses)
      road_height_max: 1.5 # Maximum height for ground-level roads (m)
      rail_height_max: 1.2 # Maximum height for ground-level railways (m)

      # Geometric filtering
      road_planarity_min: 0.6 # Minimum planarity for roads
      rail_planarity_min: 0.5 # Minimum planarity for railways

      # Intensity filtering
      enable_intensity_filter: true

    # Cache settings
    cache_dir: "cache/ground_truth"
    use_cache: true

  # === BD Forêt® V2 - Forest Type Classification ===
  bd_foret:
    enabled: true
    cache_enabled: true

    # Enrichment options
    label_forest_type: true # coniferous, deciduous, mixed
    label_primary_species: true # Quercus, Pinus, Fagus, etc.
    label_secondary_species: false # (optional)
    label_tertiary_species: false # (optional)
    estimate_height: true # Height estimation by forest type

    # Export as extra LAZ dimensions
    export_attributes: true
    attributes_to_export:
      - forest_type # String
      - primary_species # String
      - estimated_height # Float

    cache_dir: "cache/bd_foret"
    use_cache: true

  # === RPG - Agricultural Parcels and Crop Types ===
  rpg:
    enabled: true
    cache_enabled: true
    year: 2024 # Available: 2020, 2021, 2022, 2023, 2024 (LATEST)

    # Classification options
    apply_asprs_classification: true # Apply ASPRS code 44 for agriculture
    label_crop_code: true # BLE, MAI, COL, etc.
    label_crop_category: true # cereals, oleaginous, etc.
    label_crop_name: true # Wheat, Corn, Rapeseed, etc.
    label_parcel_area: true
    label_organic_farming: true

    # Export as extra LAZ dimensions
    export_attributes: true
    attributes_to_export:
      - crop_code # String (3 letters)
      - crop_category # String
      - crop_name # String
      - parcel_area # Float (m²)
      - is_organic # Boolean

    cache_dir: "cache/rpg"
    use_cache: true

  # === BD PARCELLAIRE - Cadastral Parcels ===
  cadastre:
    enabled: true
    cache_enabled: true

    # Parcel grouping options
    group_by_parcel: true # Group points by cadastral parcel
    label_parcel_id: true # Add parcel ID to each point
    label_parcel_area: true # Add parcel area
    label_commune_code: true # Add commune INSEE code
    compute_statistics: true # Compute per-parcel statistics
    export_parcel_stats: true # Export statistics to separate file

    # Export as extra LAZ dimensions
    export_attributes: true
    attributes_to_export:
      - parcel_id # String
      - parcel_area # Float (m²)
      - commune_code # String (INSEE code)

    cache_dir: "cache/cadastre"
    use_cache: true

# ============================================================================
# Classification Settings
# ============================================================================

classification:
  # Enable advanced classification
  enabled: true

  # Methods
  methods:
    geometric: true # Use geometric features
    ndvi: false # Use NDVI for vegetation
    ground_truth: true # Use BD TOPO® ground truth (CRITICAL)
    forest_types: true # Use BD Forêt® for forest refinement
    crop_types: true # Use RPG for agriculture

  # Thresholds
  thresholds:
    # NDVI
    ndvi_vegetation: 0.35
    ndvi_building: 0.15

    # Geometric
    height_low_veg: 0.5
    height_medium_veg: 2.0
    planarity_road: 0.8
    planarity_building: 0.7

    # Ground truth
    road_buffer_tolerance: 0.5 # Additional buffer for road classification (m)
    railway_buffer_tolerance: 0.5 # Additional buffer for railway classification (m)

  # Priority order (lowest to highest - last one wins in overlaps)
  priority_order:
    - vegetation # ASPRS 3/4/5
    - water # ASPRS 9
    - cemeteries # ASPRS 42
    - parking # ASPRS 40
    - sports # ASPRS 41
    - agriculture # ASPRS 44
    - power_lines # ASPRS 43
    - railways # ASPRS 10 ⚠️ HIGH PRIORITY
    - roads # ASPRS 11 ⚠️ HIGH PRIORITY
    - bridges # ASPRS 17
    - buildings # ASPRS 6 (highest priority)

# ============================================================================
# Output Settings
# ============================================================================

output:
  # Enriched LAZ settings
  enriched:
    save: true
    output_dir: "enriched_tiles" # Relative to output_dir
    compression: true

    # What to include in enriched LAZ
    include_classification: true # Update ASPRS classification
    include_rgb: true # RGB colors
    include_extra_dimensions: true # Forest types, crops, parcels, etc.

  # Statistics and reports
  save_statistics: true
  save_tile_reports: true
  save_summary_report: true
  reports_dir: "reports"

# ============================================================================
# Preprocessing (Optional)
# ============================================================================

preprocess:
  enabled: false

  # Classification normalization
  normalize_classification: true # Fix non-standard classification codes (e.g., class 67)
  strict_class_normalization: false # If true, remap ALL unknown codes to Unclassified (1)

  # Preprocessing options
  remove_noise: false
  remove_duplicates: false
  filter_by_classification: false
  normalize_intensity: false

# ============================================================================
# Advanced Options
# ============================================================================

# Tile stitching (for boundary consistency)
stitching:
  enabled: false
  buffer_size: 10.0
  auto_download_neighbors: false

# Logging
log_level: "INFO" # DEBUG | INFO | WARNING | ERROR
verbose: true

# Performance
bbox: null # Optional bounding box filter: [xmin, ymin, xmax, ymax]
max_tiles: null # Optional: limit number of tiles to process
