# Example Configuration: Multi-Source Enrichment Pipeline
# Complete example showing all data sources integrated
# Date: October 15, 2025
# Updated: Latest dataset versions (BD TOPO V3, BD Forêt V2, RPG 2024, Cadastre current)

# This configuration demonstrates:
# 1. RGB/NIR normalization and NDVI computation
# 2. BD TOPO® classification (10 feature types)
# 3. BD Forêt® forest type enrichment
# 4. RPG agricultural parcel and crop type enrichment
# 5. BD PARCELLAIRE cadastral parcel grouping
# 6. Intelligent skip with deep validation

# ============================================================================
# Quick Start Settings
# ============================================================================

mode: "enrichment" # enrichment, patches, or both

# Input/Output
input_dir: "data/raw/versailles"
output_dir: "data/enriched/versailles"
cache_dir: "cache"

# Processing
n_workers: 4
max_tiles: null # null = process all

# ============================================================================
# Multi-Source Data Integration
# ============================================================================

data_sources:
  # === BD TOPO® V3 ===
  bd_topo:
    enabled: true
    cache_enabled: true

    # Infrastructure features
    features:
      buildings: true # ASPRS code 6
      roads: true # ASPRS code 11
      railways: true # ASPRS code 10
      water: true # ASPRS code 9
      vegetation: true # ASPRS code 5
      bridges: true # ASPRS code 17
      parking: true # ASPRS code 40
      cemeteries: false # ASPRS code 42
      power_lines: false # ASPRS code 43
      sports: true # ASPRS code 41

    # Parameters for geometry generation
    parameters:
      road_width_fallback: 4.0 # Default road width (m)
      railway_width_fallback: 3.5 # Default railway width (m)
      power_line_buffer: 2.0 # Buffer for power lines (m)

    # Cache directory
    cache_dir: "cache/ground_truth"

  # === BD Forêt® V2 ===
  bd_foret:
    enabled: true
    cache_enabled: true

    # Enrichment options
    label_forest_type: true # coniferous, deciduous, mixed
    label_primary_species: true # Quercus, Pinus, etc.
    label_secondary_species: false
    label_tertiary_species: false
    estimate_height: true # Height estimation by forest type

    # Add as extra dimensions in LAZ
    export_attributes:
      - forest_type # String
      - primary_species # String
      - estimated_height # Float

  # === RPG (Registre Parcellaire Graphique) ===
  rpg:
    enabled: true
    cache_enabled: true
    year: 2024 # Available: 2024 (LATEST), 2023, 2022, 2021, 2020

    # Enrichment options
    label_crop_code: true # BLE, MAI, COL, etc.
    label_crop_category: true # cereals, oleaginous, etc.
    label_crop_name: true # Wheat, Corn, etc.
    label_parcel_area: true
    label_organic_farming: true
    apply_asprs_classification: true # Code 44 for agriculture

    # Add as extra dimensions in LAZ
    export_attributes:
      - crop_code # String (3 letters)
      - crop_category # String
      - crop_name # String
      - parcel_area # Float (m²)
      - is_organic # Boolean

  # === BD PARCELLAIRE (Cadastre) ===
  cadastre:
    enabled: true
    cache_enabled: true

    # Enrichment options
    label_parcel_id: true # Unique 19-char ID
    group_by_parcel: true # Create parcel groups
    compute_parcel_statistics: true

    # Add as extra dimensions in LAZ
    export_attributes:
      - parcel_id # String

    # Parcel statistics export
    export_parcel_stats:
      enabled: true
      format: "geojson" # geojson, csv, or both
      include_class_distribution: true
      include_point_density: true
      include_crop_types: true
      include_forest_types: true

# ============================================================================
# Feature Computation
# ============================================================================

features:
  # Geometric features
  geometric:
    enabled: true
    k_neighbors: 20

    compute:
      height: true # Height above ground
      normals: true # Surface normals
      curvature: true # Surface curvature
      planarity: true # Planarity
      linearity: false
      sphericity: false
      verticality: false

  # Spectral features
  spectral:
    rgb:
      enabled: true
      normalize: true # FIX: Normalize to 0-1 range
      include_in_output: true

    nir:
      enabled: true
      normalize: true
      include_in_output: true

    ndvi:
      enabled: true
      compute_from_rgb_nir: true
      include_in_output: true
      threshold_vegetation: 0.35

# ============================================================================
# Classification Configuration
# ============================================================================

classification:
  enabled: true

  # Classification methods (in order of application)
  methods:
    - geometric # Height + planarity based
    - ndvi # Vegetation index based
    - ground_truth # BD TOPO® overlay
    - forest_types # BD Forêt® refinement
    - agriculture # RPG overlay

  # Priority order (last wins in case of conflict)
  priority:
    1: unclassified # Code 1
    2: ground # Code 2
    3: low_vegetation # Code 3
    4: medium_vegetation # Code 4
    5: high_vegetation # Code 5
    6: agriculture # Code 44
    7: sports # Code 41
    8: parking # Code 40
    9: cemetery # Code 42
    10: road # Code 11
    11: rail # Code 10
    12: power_line # Code 43
    13: water # Code 9
    14: building # Code 6
    15: bridge # Code 17 (highest priority)

# ============================================================================
# Output Configuration
# ============================================================================

output:
  # LAZ output with all enrichments
  laz:
    enabled: true
    suffix: "_enriched"

    # Standard fields
    include_classification: true # ASPRS codes
    include_rgb: true
    include_nir: true

    # Extra dimensions to add
    extra_dimensions:
      # Geometric
      - name: height
        type: float32
        description: "Height above ground (m)"

      - name: curvature
        type: float32
        description: "Surface curvature"

      # Spectral
      - name: ndvi
        type: float32
        description: "NDVI vegetation index"

      # Forest attributes
      - name: forest_type
        type: str
        description: "Forest type (coniferous/deciduous/mixed)"

      - name: primary_species
        type: str
        description: "Primary tree species"

      # Agriculture attributes
      - name: crop_code
        type: str
        description: "Crop code (3 letters)"

      - name: crop_category
        type: str
        description: "Crop category"

      - name: crop_name
        type: str
        description: "Crop name"

      - name: is_organic
        type: uint8
        description: "Organic farming (0/1)"

      # Cadastre attributes
      - name: parcel_id
        type: str
        description: "Cadastral parcel ID"

  # GeoJSON output (parcel statistics)
  geojson:
    enabled: true
    filename: "parcel_statistics.geojson"

    include:
      parcel_geometry: true
      parcel_id: true
      commune: true
      section: true
      numero: true
      area_m2: true
      point_count: true
      point_density: true
      class_distribution: true
      dominant_class: true
      forest_types: true
      crop_types: true

  # CSV output (detailed point attributes)
  csv:
    enabled: false # Can be large
    filename: "point_attributes.csv"

    columns:
      - x
      - y
      - z
      - classification
      - ndvi
      - height
      - forest_type
      - crop_code
      - parcel_id

  # Summary statistics
  summary:
    enabled: true
    filename: "processing_summary.json"

    include:
      tile_count: true
      point_count: true
      classification_distribution: true
      forest_coverage: true
      agriculture_coverage: true
      parcel_count: true
      processing_time: true

# ============================================================================
# Intelligent Skip Configuration
# ============================================================================

skip:
  enabled: true

  # What to check
  check_enriched_laz: true
  check_all_features: true # Deep validation

  # Feature validation
  required_features:
    - classification
    - height
    - curvature
    - ndvi
    - forest_type # If forest enabled
    - crop_code # If agriculture enabled
    - parcel_id # If cadastre enabled

  # File validation
  min_file_size_mb: 0.01 # 10 KB minimum
  validate_file_integrity: true

  # Skip conditions
  skip_if_exists: true
  skip_if_valid: true
  reprocess_on_error: true

# ============================================================================
# Cache Configuration
# ============================================================================

cache:
  enabled: true
  base_dir: "cache"

  # WFS cache
  wfs:
    enabled: true
    ttl_days:
      bd_topo: 30
      bd_foret: 365
      rpg: 365
      cadastre: 180

    subdirs:
      bd_topo: "ground_truth"
      bd_foret: "bd_foret"
      rpg: "rpg"
      cadastre: "cadastre"

  # Cleanup
  auto_cleanup: false
  max_size_gb: 10

# ============================================================================
# Performance Configuration
# ============================================================================

performance:
  # Memory
  max_points_in_memory: 50000000 # 50M points
  chunk_size: 10000000 # 10M points per chunk

  # Parallelization
  parallel:
    tiles: true # Process multiple tiles in parallel
    n_workers: 4

  # Spatial indexing
  use_spatial_index: true
  spatial_index_type: "rtree" # rtree or kdtree

# ============================================================================
# Logging Configuration
# ============================================================================

logging:
  level: "INFO" # DEBUG, INFO, WARNING, ERROR

  console:
    enabled: true
    level: "INFO"

  file:
    enabled: true
    path: "logs/enrichment.log"
    level: "DEBUG"

  # Per-module levels
  modules:
    data_fetcher: "INFO"
    wfs_ground_truth: "WARNING"
    bd_foret: "INFO"
    rpg: "INFO"
    cadastre: "INFO"
    skip_checker: "INFO"
    classification: "INFO"

# ============================================================================
# Error Handling
# ============================================================================

error_handling:
  on_fetch_error: "warn_and_continue" # warn_and_continue, skip_tile, raise
  on_classification_error: "use_fallback" # use_fallback, skip_tile, raise
  on_export_error: "raise" # raise, warn_and_continue

  # Fallback values
  fallbacks:
    forest_type: "unknown"
    crop_code: "UNK"
    parcel_id: "unassigned"

# ============================================================================
# Quality Control
# ============================================================================

quality_control:
  enabled: true

  # Checks
  min_classified_ratio: 0.5 # 50% of points must be classified
  check_forest_coverage: true
  check_agriculture_coverage: true
  check_parcel_assignment: true

  # Reporting
  report_problematic_tiles: true
  problematic_tiles_file: "logs/problematic_tiles.txt"
