# Output Mode: Patches Only
#
# This mode only creates ML training patches (NPZ/HDF5).
# No enriched LAZ files are saved - standard ML training workflow.
#
# Use cases:
# - ML model training
# - Standard dataset creation
# - When enriched LAZ not needed

processing_mode: patches_only
format: npz
save_enriched: false
save_patches: true

# Patch settings (can be overridden)
patch_size: 150.0 # meters
patch_overlap: 0.1 # 10%
num_points: 16384 # points per patch
