# LOD3 Enhanced Building Classification Configuration
# ==================================================
# This configuration enables advanced architectural feature detection
# for buildings including roof types, chimneys, and balconies.
#
# Phase 2.4 Integration - v3.4.0
#
# Features:
#   - Roof type detection (flat, gabled, hipped, complex)
#   - Chimney and superstructure detection
#   - Balcony and horizontal protrusion detection
#
# Use case: Detailed urban modeling with architectural details

# ============================================================================
# Core Configuration
# ============================================================================

# Input/Output directories
input_dir: /data/lidar_tiles
output_dir: /data/output_lod3_enhanced

# Processing configuration
processor:
  lod_level: LOD3 # LOD3 required for enhanced features
  processing_mode: both # Create both patches and enriched LAZ

  # Patch configuration
  patch_size: 150.0
  num_points: 16384
  patch_overlap: 0.1

  # GPU acceleration (recommended for LOD3)
  use_gpu: true
  use_gpu_chunked: true
  gpu_batch_size: 1000000

  # Output format
  output_format: "npz,laz" # Both formats for flexibility
  architecture: pointnet++

# ============================================================================
# Feature Configuration
# ============================================================================

features:
  # Feature computation mode
  mode: lod3 # Full LOD3 feature set required

  # Geometric features
  k_neighbors: 30
  search_radius: 3.0

  # Additional features for enhanced classification
  include_extra_features: true
  include_architectural_style: true

  # Optional: RGB and NIR for better classification
  use_rgb: false
  use_infrared: false
  compute_ndvi: false

# ============================================================================
# Data Sources (Ground Truth)
# ============================================================================

data_sources:
  # BD TOPO® (IGN building footprints)
  bd_topo:
    enabled: true
    features:
      buildings: true # Required for building detection
      roads: true
      water: true
      vegetation: true

  # Other data sources (optional)
  bd_foret_enabled: false
  rpg_enabled: false
  cadastre_enabled: false

# ============================================================================
# Advanced Classification Configuration
# ============================================================================

advanced:
  # Enhanced LOD3 building classification
  classification:
    # Enable enhanced building detection
    enhanced_building:
      # ======================================================================
      # Feature Toggles
      # ======================================================================
      enable_roof_detection: true
      enable_chimney_detection: true
      enable_balcony_detection: true

      # ======================================================================
      # Roof Detection Parameters
      # ======================================================================
      roof_flat_threshold:
        15.0 # Max angle for flat roof (degrees)
        # Lower = stricter flat roof definition
        # 10.0: Very flat roofs only (urban high-density)
        # 15.0: Standard flat roofs (residential default)
        # 20.0: Moderately pitched considered flat (industrial)

      roof_dbscan_eps:
        0.3 # Roof plane segmentation distance (meters)
        # 0.2: Fine-grained (complex roofs)
        # 0.3: Standard (default)
        # 0.5: Coarse (simple roofs)

      roof_dbscan_min_samples:
        30 # Min points per roof plane
        # 20: Detect smaller planes
        # 30: Standard (default)
        # 50: Large planes only

      # ======================================================================
      # Chimney Detection Parameters
      # ======================================================================
      chimney_min_height_above_roof:
        1.0 # Min height above roof (meters)
        # 0.5: Small chimneys/vents (urban high-density)
        # 1.0: Standard chimneys (residential default)
        # 1.5: Tall chimneys only
        # 2.0: Large industrial stacks

      chimney_min_points:
        20 # Min points for chimney cluster
        # 15: Smaller features (urban high-density)
        # 20: Standard (default)
        # 30: Robust detection
        # 40: Large features only

      chimney_dbscan_eps: 0.5 # Chimney clustering distance (meters)
      chimney_max_height_above_roof: 10.0 # Max height filter

      # ======================================================================
      # Balcony Detection Parameters
      # ======================================================================
      balcony_min_distance_from_facade:
        0.5 # Min protrusion (meters)
        # 0.3: Small balconies (urban/historic)
        # 0.5: Standard (default)
        # 0.8: Large balconies/terraces only

      balcony_min_points:
        25 # Min points for balcony cluster
        # 20: Detect smaller balconies
        # 25: Standard (default)
        # 30: Robust detection
        # 40: Large terraces only

      balcony_max_depth:
        3.0 # Max protrusion depth (meters)
        # 2.0: Small balconies only
        # 3.0: Standard (default)
        # 5.0: Large terraces/verandas

      balcony_dbscan_eps: 0.5 # Balcony clustering distance
      balcony_min_height_above_ground: 2.0 # Min height filter
      balcony_confidence_threshold: 0.5 # Min confidence score

# ============================================================================
# Building Facade Classification
# ============================================================================

# Note: The enhanced classifier integrates with BuildingFacadeClassifier
# Additional facade-level parameters can be configured here if needed

# ============================================================================
# Output Configuration
# ============================================================================

output:
  save_patches: true
  save_enriched_laz: true

  # LAZ extra dimensions for enhanced features
  laz_extra_dims:
    - name: roof_type
      type: uint8
      description: "Roof type (0=unknown, 1=flat, 2=gabled, 3=hipped, 4=complex)"
    - name: is_chimney
      type: uint8
      description: "Chimney flag (0=no, 1=yes)"
    - name: is_balcony
      type: uint8
      description: "Balcony flag (0=no, 1=yes)"
    - name: balcony_confidence
      type: float32
      description: "Balcony detection confidence score"

# ============================================================================
# Performance Tuning
# ============================================================================

performance:
  # Memory management
  max_memory_gb: 16
  batch_size: 500

  # Parallel processing
  num_workers: 4 # Set to 0 when using GPU

  # Progress reporting
  progress_interval: 10 # Report every N tiles

# ============================================================================
# Usage Examples
# ============================================================================

# Run with this configuration:
#   ign-lidar process --config config_lod3_enhanced_buildings.yaml
#
# Or in Python:
#   from ign_lidar import LiDARProcessor
#   from ign_lidar.config import Config
#
#   config = Config.from_yaml('config_lod3_enhanced_buildings.yaml')
#   processor = LiDARProcessor(config)
#   processor.process_directory()
#
# Customize for different building types:
#   - Residential (default): Use as-is
#   - Urban high-density: Lower thresholds (see comments)
#   - Industrial: Disable balconies, increase chimney thresholds
#   - Historic: Lower confidence thresholds, finer detail detection
#
# Performance expectations:
#   - ~25-35% overhead vs. basic LOD2 classification
#   - ~150-400ms per building (all detectors enabled)
#   - GPU acceleration recommended for large datasets
