processor:
  lod_level: LOD2
  architecture: pointnet++
  use_gpu: false
  num_workers: 4
  patch_size: 150.0
  patch_overlap: 0.1
  num_points: 16384
  augment: false
  num_augmentations: 3
  batch_size: auto
  prefetch_factor: 2
  pin_memory: false
features:
  mode: full
  k_neighbors: 20
  include_extra: true
  use_rgb: true
  use_infrared: false
  compute_ndvi: false
  sampling_method: random
  normalize_xyz: false
  normalize_features: false
  gpu_batch_size: 1000000
  use_gpu_chunked: true
preprocess:
  enabled: true
  sor_k: 12
  sor_std: 2.0
  ror_radius: 1.0
  ror_neighbors: 4
  voxel_enabled: false
  voxel_size: 0.1
stitching:
  enabled: true
  buffer_size: 15.0
  adaptive_buffer: true
  min_buffer: 5.0
  max_buffer: 25.0
  auto_detect_neighbors: true
  auto_download_neighbors: false
  neighbor_search_radius: 50.0
  max_neighbors: 8
  use_grid_pattern: true
  cache_enabled: true
  cache_size: 1000
  parallel_loading: true
  prefetch_neighbors: true
  overlap_threshold: 0.1
  boundary_smoothing: true
  edge_artifact_removal: true
  seamless_blending: true
  memory_limit: 8192
  chunk_processing: true
  gc_frequency: 10
  compute_boundary_features: true
  boundary_feature_radius: 5.0
  cross_tile_neighborhoods: true
  preserve_tile_metadata: true
  verbose_logging: true
  save_boundary_masks: false
  save_stitching_stats: true
  timing_analysis: false
output:
  format: npz
  processing_mode: enriched_only
  compression: null
  skip_existing: true
input_dir: data/
output_dir: enriched/
num_workers: 4
verbose: true
log_level: INFO
bbox:
  xmin: null
  ymin: null
  xmax: null
  ymax: null
