# Tile Stitching Disabled Configuration
#
# No tile stitching (faster but edge artifacts)

enabled: false
buffer_size: 10.0
auto_detect_neighbors: false
auto_download_neighbors: false
cache_enabled: false
