# Enhanced Tile Stitching Configuration
#
# Advanced tile stitching with optimized boundary processing
# and intelligent neighbor detection for seamless tile mosaics

enabled: true

# Buffer configuration
buffer_size: 15.0 # Increased buffer for better feature computation
adaptive_buffer: true # Adapt buffer size based on point density
min_buffer: 5.0 # Minimum buffer size in low-density areas
max_buffer: 25.0 # Maximum buffer size in high-density areas

# Neighbor detection
auto_detect_neighbors: true # Automatically detect adjacent tiles
neighbor_search_radius: 50.0 # Search radius for neighbor detection (meters)
max_neighbors: 8 # Maximum number of neighbors to process
use_grid_pattern: true # Use IGN grid pattern for faster neighbor detection

# Performance optimization
cache_enabled: true # Cache loaded neighbor tiles
cache_size: 1000 # Maximum number of cached tiles (in MB)
parallel_loading: true # Load neighbor tiles in parallel
prefetch_neighbors: true # Pre-load likely neighbors

# Quality settings
overlap_threshold: 0.1 # Minimum overlap ratio to consider as neighbor
boundary_smoothing: true # Apply smoothing at tile boundaries
edge_artifact_removal: true # Remove edge artifacts
seamless_blending: true # Blend features at boundaries

# Memory management
memory_limit: 8192 # Memory limit in MB for stitching operations
chunk_processing: true # Process large tiles in chunks
gc_frequency: 10 # Run garbage collection every N tiles

# Advanced features
compute_boundary_features: true # Compute special features at boundaries
boundary_feature_radius: 5.0 # Radius for boundary feature computation
cross_tile_neighborhoods: true # Enable cross-tile neighborhood queries
preserve_tile_metadata: true # Keep original tile metadata in output

# Debugging and monitoring
verbose_logging: true # Detailed logging for debugging
save_boundary_masks: false # Save boundary point masks (debug)
save_stitching_stats: true # Save stitching statistics
timing_analysis: false # Detailed timing analysis (performance debug)
