# ========================================================================
# LOD2 Patches Generation - 50m Scale
# ========================================================================
# Purpose: Generate 50m training patches for LOD2 building classification
#
# Focus: Building details (walls, roof types, chimneys, dormers)
# Scale: 50m - Ideal for individual buildings
# Points: 16,384 per patch
# ========================================================================

defaults:
  - processor: default
  - features: full
  - preprocess: disabled
  - stitching: enabled
  - output: default
  - _self_

input_dir: /mnt/d/ign/preprocessed/lod2/enriched_tiles
output_dir: /mnt/d/ign/patches/lod2/50m

processor:
  skip_existing: true
  lod_level: LOD2
  architecture: hybrid
  use_gpu: true
  num_workers: 4

  patch_size: 50.0
  patch_overlap: 0.15 # Higher overlap for building boundaries
  num_points: 16384

  augment: true
  num_augmentations: 3
  augmentation_types:
    - rotation
    - flip
    - jitter
    - scale # Small scale variations for buildings

  pin_memory: true

features:
  mode: precomputed

preprocess:
  enabled: false

stitching:
  enabled: true
  buffer_size: 8.0
  auto_detect_neighbors: true
  auto_download_neighbors: false
  cache_enabled: true
  cache_dir: /mnt/d/ign/cache/neighbors

output:
  format: npz,laz # NPZ for training, LAZ for visualization
  processing_mode: patches_only
  save_stats: true
  save_metadata: true
  compression: false # No compression for NPZ (faster training)

  split_data: true
  train_split: 0.70
  val_split: 0.15
  test_split: 0.15
  organize_by_split: true

quality:
  min_points_per_patch: 8192
  min_classes_per_patch: 2
  min_building_ratio: 0.20 # At least 20% building points
  max_ground_ratio: 0.80

logging:
  level: INFO
  log_file: /mnt/d/ign/logs/lod2_patches_50m.log
  progress_bar: true
