# ============================================================================
# IGN LiDAR HD v3.2+ - Basic GPU Configuration
# ============================================================================
# GPU-accelerated processing with LOD2 features.
# Perfect for: Users with GPU (12GB+ VRAM), medium-large datasets (10-50 tiles)
#
# What this does:
# - LOD2 classification (12 features, 15 building classes)
# - GPU acceleration (10-20x faster than CPU)
# - Multi-scale artifact suppression (2 scales)
# - No external data sources (works offline)
#
# Expected performance: ~30-60 sec per 18M point tile (GPU: RTX 3080+)
# Requirements: NVIDIA GPU with 12GB+ VRAM, CUDA 11.8+, CuPy installed
# ============================================================================

# ============================================================================
# REQUIRED PARAMETERS
# ============================================================================
input_dir: "/path/to/your/laz/tiles" # ⚠️ REQUIRED - modify this
output_dir: "/path/to/output" # ⚠️ REQUIRED - modify this

# ============================================================================
# ESSENTIAL SETTINGS
# ============================================================================

# Classification mode
mode: "lod2" # LOD2 building classification

# Processing mode
processing_mode: "patches_only" # Only create ML training patches

# Hardware (GPU)
use_gpu: true # Enable GPU acceleration ⚡
num_workers: 0 # MUST be 0 with GPU (no multiprocessing + CUDA)

# Patch settings
patch_size: 50.0 # 50m × 50m patches
num_points: 16384 # 16k points per patch
patch_overlap: 0.1 # 10% overlap

# ============================================================================
# FEATURE CONFIGURATION (LOD2 + MULTI-SCALE)
# ============================================================================
features:
  feature_set: "standard" # ~12 LOD2 features
  k_neighbors: 30
  search_radius: null # Auto-calculate

  # Spectral features disabled (offline processing)
  use_rgb: false
  use_nir: false
  compute_ndvi: false

  # Multi-scale artifact suppression
  multi_scale: true
  scales:
    - fine # Fine details (k=30, r=2.0m)
    - coarse # Context (k=80, r=4.0m)

# ============================================================================
# GPU OPTIMIZATIONS (AUTO-CONFIGURED)
# ============================================================================
enable_optimizations: true
enable_async_io: true # +12-14% performance
enable_batch_processing: true # +25-30% performance (GPU)
batch_size: 4 # Process 4 tiles in parallel
enable_gpu_pooling: true # +8.5% performance (GPU memory pooling)
gpu_pool_max_size_gb: 4.0 # GPU memory pool size

print_optimization_stats: true # Show performance gains

# ============================================================================
# ADVANCED SETTINGS (OPTIONAL)
# ============================================================================
advanced:
  # Preprocessing (outlier removal)
  preprocessing:
    enabled: true
    sor_k: 12
    sor_std: 2.0
    ror_radius: 1.0
    ror_neighbors: 4
    voxel_enabled: false

  # Performance tuning (auto-configured, but can override)
  performance:
    gpu_batch_size: 25000000 # 25M points per GPU batch (adjust for VRAM)
    gpu_memory_target: 0.85 # Use 85% of VRAM
    vram_limit_gb: 10 # Conservative limit for 12GB GPU
    chunk_size: 5000000 # Chunk large tiles (5M points)

  # Multi-scale advanced
  multi_scale_advanced:
    aggregation_method: "variance_weighted"
    variance_penalty_factor: 2.0
    artifact_variance_threshold: 0.15
    reuse_kdtrees_across_scales: true
    parallel_scale_computation: false # GPU: serial is faster

# ============================================================================
# USAGE
# ============================================================================
# Basic:
#   ign-lidar-hd process -c examples/quickstart/02_gpu_basic.yaml \
#     input_dir="/data/tiles" \
#     output_dir="/data/output"
#
# For 16GB+ VRAM GPU:
#   ign-lidar-hd process -c examples/quickstart/02_gpu_basic.yaml \
#     input_dir="/data/tiles" \
#     output_dir="/data/output" \
#     advanced.performance.vram_limit_gb=14 \
#     advanced.performance.gpu_batch_size=30000000
#
# Troubleshooting:
#   - OOM errors: Reduce gpu_batch_size or vram_limit_gb
#   - Slow performance: Check GPU utilization (nvidia-smi)
#   - CUDA errors: Ensure CuPy is installed (conda install -c conda-forge cupy)
# ============================================================================
# DATA SOURCES (ALL DISABLED FOR OFFLINE PROCESSING)
# ============================================================================
data_sources:
  bd_topo:
    enabled: false

  dtm:
    enabled: false

  orthophoto:
    enabled: false
# ============================================================================
# GPU MEMORY TUNING
# ============================================================================
# For different GPU memory sizes:
#
# 12GB VRAM (RTX 3080 Ti, RTX 3060 12GB):
#   gpu_batch_size: 20_000_000
#   vram_limit_gb: 10
#   chunk_size: 4_000_000
#
# 16GB VRAM (RTX 4080, A5000):
#   gpu_batch_size: 30_000_000
#   vram_limit_gb: 14
#   chunk_size: 5_000_000
#
# 24GB VRAM (RTX 4090, A6000):
#   gpu_batch_size: 50_000_000
#   vram_limit_gb: 22
#   chunk_size: 10_000_000
#
# ============================================================================
# USAGE
# ============================================================================
# ign-lidar-hd process -c examples/quickstart/02_gpu_basic.yaml
#
# For 16GB GPU:
# ign-lidar-hd process -c examples/quickstart/02_gpu_basic.yaml \
#   processor.gpu_batch_size=30000000 \
#   processor.vram_limit_gb=14 \
#   input_dir="/data/tiles"
#
# For 24GB GPU:
# ign-lidar-hd process -c examples/quickstart/02_gpu_basic.yaml \
#   processor.gpu_batch_size=50000000 \
#   processor.vram_limit_gb=22 \
#   input_dir="/data/tiles"
# ============================================================================
